src/toil/common.py
src/toil/worker.py

Continued from https://github.com/BD2KGenomics/toil-old/pull/16

Work directory flag

---

README.md
src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/gridengine.py
src/toil/batchSystems/lsf.py
src/toil/batchSystems/mesos/__init__.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/mesos/executor.py
src/toil/batchSystems/multijob.py
src/toil/batchSystems/parasol.py
src/toil/batchSystems/singleMachine.py
src/toil/common.py
src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/awsJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/jobWrapper.py
src/toil/leader.py
src/toil/resource.py
src/toil/test/batchSystems/abstractBatchSystemTest.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/sort/sort.py
src/toil/test/sort/sortTest.py
src/toil/test/src/jobWrapperTest.py
src/toil/utils/toilKill.py
src/toil/utils/toilRestart.py
src/toil/utils/toilStats.py
src/toil/utils/toilStatus.py
src/toil/worker.py

This hopefully undoes the mess created by 
https://github.com/BD2KGenomics/toil/commit/89e5dd151387a7e81882faf1e7fa33626dfcbab2

Undo the batchjob mess (resolves #204)

---

src/toil/common.py
src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/awsJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/test/jobStores/jobStoreTest.py

Users can specify a file containing a key to use with S3's server side encryption on the AWS jobStore.

Encrypt AWS job store with SSE

---

src/toil/job.py
src/toil/jobStores/fileJobStore.py
src/toil/test/sort/sort.py
src/toil/test/sort/sortTest.py
src/toil/test/utils/utilsTest.py

Fixes commit message in from PR #276.

Distinguishes between wrapped functions in toil stats and fixes bug in stats collation (resolves #256, resolves #146)

---

src/toil/test/utils/utilsTest.py

Reducing the utils test size by 10x, does not hang on my box with (resolves #279)

---

src/toil/jobStores/awsJobStore.py

Retry SDB domain creation on 500 errors (resolves #285)

---

Makefile
src/toil/common.py
src/toil/job.py
src/toil/test/sort/sort.py
src/toil/test/src/jobServiceTest.py
src/toil/test/utils/utilsTest.py
src/toil/worker.py

was set to equal 1. This is fixed, as is the serviceTestIssue. Hannes,
please test this now works for you on pyCharm.

Fixed utilsTest/sortTest and serviceTest (resolves #272)

---

src/toil/batchSystems/mesos/batchSystem.py

If jobs don't meet mesos' minimum resource requirements, round up and log

Verify jobs meet mesos' minimum resource requirements (resolves #208)

---

src/toil/job.py
src/toil/resource.py
src/toil/test/sort/lib.py
src/toil/test/sort/sortTest.py
src/toil/test/utils/utilsTest.py
src/toil/worker.py

User module fixes

---

src/toil/jobStores/azureJobStore.py

We now retry Azure ops 5 times on timeout and other TCP socket errors (as does Boto). HTTP error codes are handled by the Azure API, so they aren't retried.

Azure jobStore now retries on the same exceptions Boto does (resolves #341)

---

src/toil/jobStores/azureJobStore.py

The leader ended up crashing when a worker happeend to log anything. Maybe we should add stats strings to the job store unit test?

azure stats strings were being passed as strings, not fds (resolves #385)

---

src/toil/jobStores/azureJobStore.py

Not at my dev machine right now, so hopefully the tests actually pass.

idempotent job deletion for Azure (resolves #422)

---

src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/test/sort/sort.py
src/toil/test/src/jobFileStoreTest.py

Resolves #484, #464, #483
Also:
Improves readGlobalFile to make more general.
Improves sort test to better use the filestore. 
Allows readGlobalFile to read to any specified user location.
Allows disabling of read caching.

Resolves #483, resolves #484, resolves #464

---

src/toil/test/batchSystems/batchSystemTest.py

- Replace the batchSystem tests that involve issuing jobs with a single test that uses issueBatchJob, getIssuedBatchJobIDs, getRunningBatchJobIDs, getUpdatedBatchJobIDs, and killBatchJobs together.
- Don't let jobs go to sleep for arbitrary lengths of time - make the running time of the test be limited only by how fast the batch system can run the API calls. 
- Avoid race conditions that occur when getRunningJobIDs() or getIssuedJobIDs() are called after wait_for_jobs(). Using two batchSystem API calls was leaving a window open for the job to change status before the second call.

Consolidate batchSystem tests (resolves #354)

---

src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/aws/sdbUtils.py

Monkey-patch SBDConnection.put_attributes to use POST instead of GET (resolves #502)

---

README.rst
setup.py
src/toil/__init__.py
src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/lsf.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/mesos/executor.py
src/toil/batchSystems/parasol.py
src/toil/batchSystems/singleMachine.py
src/toil/common.py
src/toil/cwl/cwltoil.py
src/toil/job.py
src/toil/leader.py
src/toil/lib/bioio.py
src/toil/test/__init__.py
src/toil/test/mesos/helloWorld.py
src/toil/test/mesos/mesosTest.py
src/toil/test/sort/lib.py
src/toil/test/sort/sort.py
src/toil/test/sort/sortTest.py
src/toil/test/src/jobWrapperTest.py
src/toil/test/utils/utilsTest.py
src/toil/utils/toilMain.py
src/toil/worker.py

Tweak and hopefully simplify the various import-related hacks in Toil (resolves #420, resolves #425)

---

src/toil/jobStores/conftest.py
src/toil/test/jobStores/jobStoreTest.py

Fix: Test collection fails if boto isn't installed (resolves #530)

---

contrib/azure/README.md
src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/mesos/test/__init__.py
src/toil/batchSystems/parasol.py
src/toil/common.py
src/toil/test/batchSystems/batchSystemTest.py

Rename --masterIP to --mesosMaster and add support for host names (resolves #545)

---

src/toil/common.py
src/toil/jobStores/aws/jobStore.py
src/toil/test/jobStores/jobStoreTest.py

Regression from e60e396d0ce6523bc153fe3de2f5a8876e12785d
Resolves #542

Validate AWS job store name (resolves #542)

---

Makefile
setup.py
src/toil/batchSystems/gridengine.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/mesos/executor.py
src/toil/batchSystems/parasol.py
src/toil/batchSystems/parasolTestSupport.py
src/toil/common.py
src/toil/test/__init__.py
src/toil/test/batchSystems/batchSystemTest.py

Resolves #473, #547 plus a few minor things.

Added support for setEnv in GridEngine and Parasol (resolves #473, resolves #547)

---

src/toil/batchSystems/singleMachine.py
src/toil/common.py
src/toil/test/batchSystems/batchSystemTest.py

While the issue may be invalid, an additional test that proves it doesn't hurt.
Connected to #548.
Resolves #559.

Service jobs supposedly hanging (connected to #548, resolves #559)

---

src/toil/common.py
src/toil/job.py
src/toil/worker.py

Also consolidated computation of effective requirements between job and config.
Resolves #551.

Cache defaults to disk if disk is lower than defaultCache (resolves #551)

---

setup.cfg
setup.py
src/toil/batchSystems/parasol.py
src/toil/batchSystems/parasolTestSupport.py
src/toil/test/__init__.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/sort/sortTest.py

Resolves #449 
Note that I just created a new toil-jenkins-slave AMI with the parasol binaries that have 
https://github.com/hannes-ucsc/kentUtils/commit/5e2177332be3525034d36911c67955ac0e789d37
in it to accelerate the Parasol tests. This will be the first build on an instance booted from that AMI.

Numerous Parasol improvements (resolves #449)

---

setup.py
src/toil/cwl/cwltoil.py

Fix for cwltool update that adds InlineJavascriptRequirement.
Resolves #576

Fix for cwltool update that adds InlineJavascriptRequirement (resolves #576)

---

contrib/azure/README.md
contrib/azure/agent-0.json
contrib/azure/agent-gt0.json
contrib/azure/azuredeploy.json
contrib/azure/azuredeploy.parameters.json
contrib/azure/configure-mesos-cluster.sh
contrib/azure/jumpbox-linux.json
contrib/azure/jumpbox-none.json
contrib/azure/jumpbox-windows.json
contrib/azure/master.json
src/toil/jobStores/azureJobStore.py
src/toil/test/jobStores/jobStoreTest.py

Continued from #573, resolves #570

Update Azure template in contrib; fix hang in Azure job store's readFile (resolves #570)

---

src/toil/batchSystems/singleMachine.py

Single Machine will now hang when requested memory is greater than physically installed memory on the machine.
Resolves #550

Modified single machine maxMemory to physically installed memory (resolves #550)

---

src/toil/jobStores/azureJobStore.py
src/toil/test/jobStores/jobStoreTest.py

Use binary instead of string type for Azure table storage properties (resolves #577)

---

src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/azureJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/leader.py
src/toil/test/utils/utilsTest.py
src/toil/utils/toilStats.py
src/toil/worker.py

Use JSON for stats and logging (resolves #427, resolves #125)

---

docs/conf.py
docs/index.rst
docs/jobStore.rst
jenkins.sh

Fix sys.path insertion in conf.py; assert that toil is imported correctly in conf.py (resolves #519)

---

contrib/azure/configure-mesos-cluster.sh

This PR updates the install scripts for setting up an Azure cluster to be more robust.

Azure cluster config

---

src/toil/jobStores/azureJobStore.py

Retry when Azure reports a service is unavailable (resolves #583)

---

src/toil/leader.py

Resolves #609 
Also ensures that Toil fails if collator fails.

Fix AttributeError in stats/logging collator process (resolves #609)

---

src/toil/leader.py

Fix AttributeError in stats/logging collator process (resolves #609 on branch 3.1.x)

---

src/toil/batchSystems/mesos/batchSystem.py

Fix: Mesos tasks aren't sorted by type (resolves #625)

---

src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/azureJobStore.py
src/toil/leader.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/utils/toilRestart.py

Continued from #585, resolves #584.

Fix slow restart against the AzureJobStore (resolves #584)

---

src/toil/jobStores/azureJobStore.py

Resolves #636, continued from #590.

Add support for multiple Azure storage accounts (resolves #636)

---

src/toil/common.py
src/toil/job.py
src/toil/lib/bioio.py
src/toil/realtimeLogger.py
src/toil/test/src/realtimeLoggerTest.py

Continued from #515
Resolves #359

Add real-time logging facility (resolves #359)

---

src/toil/common.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/fileJobStore.py

Add config.workflowID to distinguish between consecutive successful workflows (resolves #647)

---

src/toil/test/src/systemTest.py

Add test for atomicity of renames of non-empty directories (resolves #649)

---

src/toil/lib/bioio.py
src/toil/test/jobStores/jobStoreTest.py

Silence boto, even at log level DEBUG (resolves #554)

---

src/toil/leader.py
src/toil/worker.py

Continued from https://github.com/BD2KGenomics/toil/pull/696, I targeted the wrong branch

Always report logToMaster messages (resolves #683)

---

src/toil/common.py
src/toil/leader.py
src/toil/test/src/retainTempDirTest.py
src/toil/worker.py

Resolves #686, #690
Continued from https://github.com/BD2KGenomics/toil/pull/687, I initially selected the wrong target branch. The tests in this PR are cleaner but the functionality is the same.

Issues/3.1.x/686 clean work dir 690 improper exception (resolves #686, resolves #690)

---

src/toil/cwl/cwltoil.py

Resolves #712 
- Support complex scatter.
- Support multiple sources on workflow steps.
- Support valueFrom on workflow step input.
Passes CWL draft-3 conformance tests in local run.

Support remaining CWL draft-3 workflow features (resolves #712)

---

src/toil/batchSystems/mesos/batchSystem.py

Log insufficient Mesos offers (resolves #669)

---

src/toil/jobStores/abstractJobStore.py

Includes sphinx/rst annotation for parameters, return values, and exceptions raised as well as documentation for Toil exceptions.

Improved documentation for AbstractJobStore (resolves #745)

---

setup.py
src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py
src/toil/test/cwl/revtool.cwl

Add cwltoil import file jobstore (resolves #711)

---

docs/index.rst
docs/installation.rst
docs/running.rst

Add documentation about running CWL workflows on Toil (resolves #740)

---

setup.py
src/toil/jobStores/azureJobStore.py
src/toil/test/jobStores/jobStoreTest.py

Updated Azure to latest stable build (v1.0.3)

---

docs/developing.rst
docs/index.rst
src/toil/common.py
src/toil/cwl/cwltoil.py
src/toil/job.py
src/toil/test/sort/sortTest.py
src/toil/test/src/importExportFileTest.py
src/toil/test/src/jobWrapperTest.py
src/toil/test/src/toilContextManagerTest.py

Resolves #766
The importExportFileTest now spawns a job that creates an output file. This output file is then exported.

Improved file staging docs and tests (resolves #766)

---

docs/developing.rst
docs/toilAPI.rst
src/toil/common.py
src/toil/job.py
src/toil/test/src/promisesTest.py

Resolves #817, continued from #818.

Fix stale promise job store cache (resolves #817)

---

src/toil/common.py
src/toil/job.py
src/toil/test/mesos/helloWorld.py
src/toil/test/src/regularLogTest.py
src/toil/worker.py

Fix logging functionality (resolves #803, resolves #836)

---

setup.py
src/toil/cwl/cwltoil.py

Passes CWL conformance tests with AWS/Mesos batch system.  Calls
setLoggingFromOptions(options) to set up toil logging.  Bump cwltool version
dependency.

Ensure default are properly staged and unstaged. (resolves #601)

---

src/toil/job.py
src/toil/test/src/jobServiceTest.py

Continued from #843
Resolves #844
Adds a test in toil.test.jobServiceTest.testServiceSerialization which now passes
illustrating the issues.

Fix service promise serialization (resolves #844)

---

src/toil/batchSystems/abstractBatchSystem.py

Remove out of date doc comment (connected to #547)

---

src/toil/batchSystems/mesos/batchSystem.py
src/toil/test/batchSystems/batchSystemTest.py

Fix off by factor 1024 in Mesos disk allocation (resolves #854)

---

src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/azureJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/test/__init__.py
src/toil/test/jobStores/jobStoreTest.py

Support was added by adding functionality to AbstractJobStore._supportsUrl, AbstractJobStore._readFromUrl.

Added support for importing of http(s):// URLs (resolves #722)

---

src/toil/leader.py

Also fixes wonky try except (Resolves #801)

Positive log message for reporting number of failed jobs (Resolves #663, resolves #801)

---

src/toil/cwl/cwltoil.py

There has been a discussion in Common Workflow Language [Gitter](https://gitter.im/common-workflow-language/common-workflow-language) channel about `cwltoil` not passing around the `--no-container` option. This causes that even if you explicitely specify `--no-container`, if there is a `DockerRequirement` hint in your workflow, `cwltool` will try to use Docker. This PR should solve the problem.
As an addition, thanks to the use of `kwargs`, its possible to extend the options passed to `cwltool` if desired. 
@tetron could you please give this a look? Its tested in our `HPC` and working (the option, not the entire workflow yet).
Thanks!

--no-container no longer ignored by cwltoil

---

Makefile
docs/installation.rst
setup.py
src/toil/common.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/googleJobStore.py
src/toil/leader.py
src/toil/test/__init__.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/sort/sortTest.py

Implement Google job store (resolves #605, resolves #832)

---

src/toil/batchSystems/abstractBatchSystem.py
src/toil/common.py
src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/resource.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/mesos/helloWorld.py
src/toil/test/sort/sort.py
src/toil/test/sort/sortTest.py
src/toil/test/src/jobCacheTest.py
src/toil/test/src/jobFileStoreTest.py
src/toil/test/src/userDefinedJobArgTypeTest.py
src/toil/worker.py

Resolves #586, continued from #656.

Eliminate cache requirement (resolves #586)

---

src/toil/test/src/jobCacheTest.py

resolves #896
Previously failed to account for failure of cleanup jobs in the test.

Fix regression in AwsJobStoreCacheTest (resolves #896)

---

src/toil/cwl/cwltoil.py

This should make available the `--preserve-environment` option that is causing #839 
Ping @dleehr

Add --preserve-environment option (resolves #839)

---

src/toil/test/src/jobCacheTest.py

resolves #893 
This may show as conflicting with master, but that will be resolved when #898 is merged

Add Google job store to cache tests (resolves #893)

---

.gitignore
Makefile
jenkins.sh
run_tests.py
setup.py
src/toil/test/__init__.py

- Also obsoletes setup.py for running tests

Run some tests in parallel (resolves #901)

---

src/toil/job.py
src/toil/test/src/jobCacheTest.py

resolves #911
Setup new error and catch that in the tests instead

Fix brittle assertion error in cache tests (resolves #911)

---

.gitignore
docs/running.rst

Document __name__ == '__main__' boilerplate in user scripts (resolves #617)

---

src/toil/jobStores/azureJobStore.py
src/toil/test/jobStores/jobStoreTest.py

continues #833 
resolves #593, resolves #543, resolves #714, resolves #478, resolves #860

Various Azure fixes (resolves #593, resolves #543, resolves #714, resolves #478, resolves #860)

---

src/toil/__init__.py
src/toil/resource.py

Hot deployment fixes against 3.1.x

---

src/toil/test/src/jobCacheTest.py

resolves #925
Modified the test to have no retries, leading to only a single failed job instead of 2.
Modified the delete mutably and immutably read file tests to not be non-deterministic

Fix AssertionError in evict Tests (resolves #925)

---

src/toil/test/__init__.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/src/jobCacheTest.py

Add @experimental test decorator; honor test exclusion in import/export tests

---

src/toil/common.py
src/toil/test/sort/sortTest.py
src/toil/test/src/toilContextManagerTest.py

Resolves #941 and some smaller cosmetic issues.

Don't shutdown batch system after it failed to init (fixes #941)

---

src/toil/__init__.py
src/toil/job.py
src/toil/resource.py

Hot-deployment fixes against master

---

src/toil/test/jobStores/jobStoreTest.py
src/toil/test/sort/sortTest.py
src/toil/test/src/jobCacheTest.py

Added more @experimental test exclusions (fixes #947)

---

src/toil/test/src/jobCacheTest.py

- removed vanity header
- fix line wrapping
- improved readability by breaking up overly long expressions
- fix string interpolation vs concatenation crazyness
- automated hack that lets us use static methods as job functions
- use _getTestJobStore abstract method, don't piggy back on _getTestJobStorePath
- removed unused variables
- suppressed illegitimate PyCharm warnings

Cosmetically improve jobCacheTest

---

src/toil/common.py

Fix the caching is not supported on this batch system error (resolves #931)

---

src/toil/__init__.py
src/toil/resource.py
src/toil/test/src/resourceTest.py

Add support for hot-deploying virtualenvs (resolves #937)

---

src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/aws/utils.py
src/toil/jobStores/googleJobStore.py
src/toil/test/__init__.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/src/promisedRequirementTest.py

Fix various import/export robustness issues

---

src/toil/jobStores/aws/utils.py

This is based on the assumption that those errors are intermittent and caused by the server side. Alternatively, there is the possibility that they are caused by a threading issue or a connection leak. In the latter case, retrying would aggravate the situation.

Retry certain SSL errors (fixes #978)

---

src/toil/jobStores/aws/jobStore.py

Retry when S3 bucket creation yells BucketAlreadyOwnedBy (fixes #955)

---

docs/developing.rst
src/toil/common.py
src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/src/importExportFileTest.py

Resolves #837 
Continues #838
The first commit contains Jake's original and my fixes.

Added optional sharedFileName parameter to importFile (resolves #837)

---

docs/spark.rst
src/toil/job.py
src/toil/lib/spark.py
src/toil/test/__init__.py
src/toil/test/lib/sparkTest.py

Resolves #774.
Ping @benedictpaten

Add Spark cluster service (resolves #774)

---

setup.py
src/toil/jobStores/aws/jobStore.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/src/importExportFileTest.py
src/toil/test/src/multipartTransferTest.py

Copies within the same region should now be much faster.

Multipart copy now uses a thread pool (resolves #859)

---

src/toil/cwl/cwltoil.py

Tweak cwltools writeFile logging (fixes #988)

---

src/toil/job.py
src/toil/test/src/promisedRequirementTest.py

resolves #1014
the return value of writeGlobalFile is now a class  jobStoreFile that has an
__repr__ magic method returning the jobStoreFIleID string, and has a class
variable size that describes the size of the file in bytes. Naive implementation
at the moment.

Add attributes to return value of writeGlobalFile (resolves #1014)

---

src/toil/job.py

Fix overkill functionalization in FileID (resolves #1014)

---

setup.py
src/toil/common.py
src/toil/job.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/aws/utils.py
src/toil/resource.py
src/toil/test/__init__.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/src/jobTest.py
src/toil/test/src/promisesTest.py
src/toil/test/src/resourceTest.py

Resolves #631
Resolves #1021
Resolves #996 
Resolves #1023

Various smallish bug fixes

---

src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/utils.py
src/toil/test/jobStores/jobStoreTest.py

Resolves #1010
Possibly more to be added.

Cherrypicks from 3.1.x

---

src/toil/job.py
src/toil/test/src/promisedRequirementTest.py

Fix promise requirement race condition (resolves #1039)

---

docs/conf.py
docs/jobStore.rst
setup.py
src/toil/common.py
src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/azureJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/jobStores/googleJobStore.py
src/toil/jobStores/utils.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/sort/sortTest.py
src/toil/test/src/jobWrapperTest.py
src/toil/test/utils/utilsTest.py
src/toil/utils/toilClean.py
src/toil/utils/toilKill.py
src/toil/utils/toilStats.py
src/toil/utils/toilStatus.py
src/toil/worker.py

Continues #916
Resolves #785, resolves #789, resolves #834, resolves #869, resolves #904, resolves #1011, resolves #891.

Deconvolute job store creation and loading (resolves #785 et al)

---

src/toil/job.py

resolves #1046
Harbinger file deletion now occurs only with the cache lock held.

Fix harbinger file deletion race condition (resolves #1046)

---

jenkins.sh
src/toil/__init__.py
src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/singleMachine.py
src/toil/test/batchSystems/batchSystemTest.py

Add singleMachine disk tracking (resolves #770)

---

src/toil/leader.py

Failing pipelines with an error within a job were quite difficult to
debug as they require digging into the jobStore to identify error
messages. This path improves the output to report the underlying failure
at the top level to more easily identify the problem.
Original failures look like:
```
Exception in thread Thread-1:
[...]
raise RuntimeError("The termination flag is set, exiting")
RuntimeError: The termination flag is set, exiting
[...]
File "/home/chapmanb/bio/toil/venv/local/lib/python2.7/site-packages/toil-3.3.0a1-py2.7.egg/toil/leader.py", line 69
7, in mainLoop
raise FailedJobsException(config.jobStore, len(toilState.totalFailedJobs), toilState.totalFailedJobs)
toil.leader.FailedJobsException: The job store …
```

Provide more useful messages for job failures

---

Makefile
jenkins.sh
run_tests.py
setup.py
src/toil/provisioners/aws/provisioner.py
src/toil/test/__init__.py
src/toil/test/provisioners/aws/provisionerTest.py
src/toil/version.py

Added integration test (resolves #1055)

---

docs/running.rst

toil-sort-example.py currently crashes on the latest toil version. This PR fixes some parts that got broken by caching and/or jobStore changes.

Update toil-sort-example to account for caching/jobStore changes (resolves #1080)

---

src/toil/cwl/cwltoil.py

This fixes problems on shared filesystem batch scheduler systems which
do not automatically transfer TMPDIR from the parent. Failing to do this
results in jobs run on non-shared local temporary directories which are
not accessible to the parent fileStorage manager. This avoids the issue
by explicitly setting and passing a temporary directory in the defined
outdir. Required for distributed runs on SGE clusters so supplements #1105
with the necessary CWL specific fixes.

CWL: Pass local temporary directory to jobs

---

src/toil/batchSystems/gridengine.py
src/toil/test/jobStores/jobStoreTest.py

Thanks to Jing for providing access to the Cancer Browser AWS account. Also fixes a minor logging issue with SGE.
Resolves #1116 
Resolves #1114

Change testInaccessibleLocation to different bucket (fixes #1116)

---

docs/installation.rst

Fix CGCloud installation instructions in docs (resolves #1053)

---

src/toil/lib/bioio.py

Log the log level of the root and the 'toil' logger (resolves #1120)

---

Makefile
docker/Dockerfile.py
src/toil/common.py
src/toil/resource.py
src/toil/test/__init__.py
src/toil/test/provisioners/cgcloud/provisionerTest.py
src/toil/test/src/hotDeploymentTest.py

Resolves #1127
Also adds general unit test support for running Toil scripts in appliances.

Fix hotdeployment for --restart

---

src/toil/job.py
src/toil/resource.py
src/toil/test/__init__.py
src/toil/test/src/hotDeploymentTest.py

Fix hot-deployment of venv with jobs from distinct root packages (resolves #1152)

---

src/toil/common.py
src/toil/resource.py
src/toil/test/jobStores/jobStoreTest.py

Resolves #1127 on releases/3.3.x

Persist user module to job store so --restart can use it (resolves #1127)

---

src/toil/version.py

Include fix to cgcloud-lib for IAM role leak (resolves #1147)

---

src/toil/leader.py

resolves #760 on releases/3.3.x

Catch NoSuchJobException caused by stale SDB read (resolves #760)

---

src/toil/fileStore.py
src/toil/job.py
src/toil/test/sort/sort.py
src/toil/test/src/jobServiceTest.py
src/toil/test/src/promisedRequirementTest.py

Fixes this bug in both Job and Service resource requirements

Use config to discover proper resource values (resolves #1119)

---

contrib/azure/configure-mesos-cluster.sh

This fixes #1126 in my testing.

Mark Mesos nodes as non-preemptable

---

run_tests.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/common.py
src/toil/job.py
src/toil/leader.py
src/toil/provisioners/clusterScaler.py
src/toil/test/__init__.py
src/toil/test/provisioners/cgcloud/provisionerTest.py

Resolves #1086
Continues #1112

Eliminate double autoscaling by fixing issued job code (resolves #1086)

---

docs/developing.rst
docs/installation.rst

Document user script deployment (resolves #567, resolves #537)

---

src/toil/jobStores/abstractJobStore.py
src/toil/test/jobStores/jobStoreTest.py

Here's my FTP support with a test using a random Internet FTP server, while we wait for @JakeNarkizian to redesign the tests that download things.
Resolves #1209

Add ftp and test

---

src/toil/provisioners/aws/__init__.py

Run volume-mounting.service before docker.service (resolves #1230)

---

src/toil/provisioners/aws/awsProvisioner.py

Enable TTY mode when SSH-ing into Toil Appliance (resolves #1227)

---

src/toil/provisioners/aws/awsProvisioner.py

Retry spot request tagging (resolves #1231)

---

src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/mesos/__init__.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/common.py
src/toil/resource.py
src/toil/test/__init__.py
src/toil/test/src/hotDeploymentTest.py
src/toil/test/src/resourceTest.py

Obsoletes fix for #1127.
Consider cherry picking to 3.3.x if possible.

Fix hot-deployment of modified user script with --restart (resolves #1207)

---

src/toil/provisioners/aws/awsProvisioner.py

Better handle case where TOIL_APPLIANCE_SELF is unset (resolves #1229)

---

src/toil/leader.py
src/toil/provisioners/clusterScaler.py

Periodically check on scaler thread continuance (resolves #1208)

---

docker/Dockerfile.py
jenkins.sh
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/provisioners/cgcloud/provisionerTest.py
src/toil/test/src/hotDeploymentTest.py
src/toil/test/src/resourceTest.py

Prevent virtualenv from silently upgrading pip (resolves #1270)

---

jenkins.sh

Force removal of files left over by test containers (fixes #1276)

---

src/toil/common.py
src/toil/job.py
src/toil/leader.py
src/toil/test/src/hotDeploymentTest.py

Fixes related to encapsulated jobs (fixes #1259, fixes #1278)

---

docs/installation.rst

resolves #1281
I added a separate area to specify Docker installation instructions. Let me know if this is too much or what I can do to improve!

Add docker installation instructions (resolves #1281)

---

src/toil/test/__init__.py

Resolves #1309 
For example: http://jenkins.cgcloud.info/job/toil-branches/branch/master/275/testReport/src.toil.test.src.hotDeploymentTest/

Use `inspect` instead of `images` for @needs_appliance (fixes #1309)

---

src/toil/leader.py
src/toil/test/src/jobTest.py
src/toil/test/src/restartDAGTest.py
src/toil/test/src/resumabilityTest.py

@benedictpaten this adds a couple simple test cases for #1122

Add tests for stranded successors in DAGs (resolves #1122, resolves #1289, resolves #1294)

---

version_template.py

Explicitly require setuptools >=8.0 (resolves #1323)

---

src/toil/worker.py

Resolves #1211
Restores original stderr to fd 2

Fix copy-paste typo (resolves #1211)

---

src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py

Continues #1025
Support restarting a cwltoil workflow with the `--restart` flag,
updates work by @tetron in #1025 and fixes #1100. Adds a test
to demonstrate restart capability by manipulating paths to cause the
initial run of the revsort workflow to fail.
Still a work in progress as the test fails consistently when restarting.
I could use help debugging what I'm missing to correctly restart to
finish this. If you run the test:
```
make test tests=src/toil/test/cwl/cwlTest.py::CWLTest::test_restart
```
It completes the expected failure step, but the restart fails with an
EOFError when unpickling a job store (similar to #676 and #1039):
```
INFO toil.jobStores.fileJobStore: Path to job store directory is '/tmp/user/1001/toil-test-toil.test.cwl.cwlTest.CWLTest-test_restart-l0vC5G/jobStore'. …
```

Support CWL workflow restarts (resolves #1241, resolves #1100)

---

src/toil/batchSystems/lsf.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/mesos/executor.py
src/toil/batchSystems/parasol.py
src/toil/batchSystems/singleMachine.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/azureJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/leader.py

I also updated some log messages to include the job name & removed redundant logging of the jobstore ID.

Improve log messages, fix simple azure bug (resolves #1331, resolves #1268)

---

src/toil/test/src/fileStoreTest.py

Skip failing async caching test 

---

src/toil/test/src/fileStoreTest.py

resolves #1344
The monkey patch to job.fileStore.jobStore.updateFileStream was propagating to
the next job and causing the next job to wait 20s to resolve the promise it was
passed.  Monkey patching job.fileStore.HarbingerFile.read limits the patch to the
scope of the current job and fixes this issue.

Fix bug in testAsyncWriteWithCaching (resolves #1344)

---

src/toil/common.py

Handle relative paths in --workDir (resolves #1110)

---

setup.cfg
src/toil/fileStore.py
src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/resource.py
src/toil/test/src/hotDeploymentTest.py

Fix deserialization of deferred functions with encapsulated jobs (resolves #1308)

---

src/toil/jobStores/aws/jobStore.py

Retry 409s configuring versioning of job store buckets (resolves #1093)

---

docs/developing.rst
docs/running.rst
src/toil/provisioners/aws/__init__.py
src/toil/provisioners/aws/awsProvisioner.py

Documentation, AWS provisioner improvements

---

src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/test/jobStores/jobStoreTest.py

Tweak bucket creation and versioning configuration (resolves #1272)

---

src/toil/test/__init__.py
src/toil/test/src/hotDeploymentTest.py

Fix race in appliance test cleanup

---

src/toil/common.py
src/toil/resource.py

Periodically refresh user script resource

---

Makefile
src/toil/common.py
src/toil/provisioners/abstractProvisioner.py
src/toil/provisioners/aws/__init__.py
src/toil/provisioners/clusterScaler.py
src/toil/test/provisioners/aws/awsProvisionerTest.py

Gather cluster usage statistics

---

docker/Dockerfile.py
docs/cli.rst
src/toil/provisioners/__init__.py
src/toil/provisioners/abstractProvisioner.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/utils/utilsTest.py
src/toil/utils/toilMain.py
src/toil/utils/toilRsyncCluster.py

Add `toil rsync-cluster` (fixes #1258)

---

docs/developing.rst

Document that hot-deployment does not handle eggs 

---

src/toil/__init__.py
src/toil/common.py
src/toil/worker.py

Resolves #1354:
1. Config is now logged on one long line instead of on several lines
2. Fixed bug where config would be logged twice

Improve logging of config

---

src/toil/provisioners/clusterScaler.py

Insure proper scaler thread is joined 

---

Makefile
docker/Dockerfile.py
docker/waitForKey.sh
src/toil/provisioners/abstractProvisioner.py
src/toil/provisioners/aws/__init__.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/provisioners/aws/awsProvisionerTest.py

Resolves #1377, resolves #1378

Securely propagate SSE-C keys when using AWS provisioner

---

src/toil/batchSystems/mesos/batchSystem.py
src/toil/provisioners/abstractProvisioner.py
src/toil/provisioners/aws/awsProvisioner.py

Insure provisioner spins down nodes whenever possible

---

src/toil/batchSystems/mesos/batchSystem.py

Standardize how preemptable nodes are discovered

---

src/toil/batchSystems/lsf.py

Add missing abstract method for LSF batch system

---

src/toil/common.py
src/toil/fileStore.py

Enhance logs output when Toil runs out of disk (resolves #1428)

---

src/toil/leader.py
src/toil/test/utils/utilsTest.py
src/toil/utils/toilStatus.py

Revamp Toil status

---

src/toil/provisioners/aws/__init__.py

Improve zone discovery logic

---

src/toil/test/utils/utilsTest.py
src/toil/utils/__init__.py

* Utils will use aws provisioner by default

Improve toil cluster utils

---

src/toil/batchSystems/__init__.py
src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/gridengine.py
src/toil/batchSystems/slurm.py
src/toil/batchSystems/torque.py
src/toil/common.py
src/toil/job.py
src/toil/serviceManager.py
src/toil/test/__init__.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/sort/sortTest.py
src/toil/test/src/miscTests.py

This is a preliminary run at adding PBS/Torque support, designed off the SLURM and SGE classes.  Tests have also been added.
Resolves #1163

Initial PBS/Torque support and AbstractBatchSystem refactoring

---

src/toil/test/batchSystems/batchSystemTest.py

Increase wait time before failing test 

---

src/toil/provisioners/abstractProvisioner.py

Spin down nodes at the end of billing cycle 

---

src/toil/batchSystems/slurm.py

Resolves #1463
@lassancejm can you check if this fixes your issue?

Fix bugs in Slurm arg envars 

---

src/toil/fileStore.py
src/toil/test/src/fileStoreTest.py

Resolves #1469 
First commit just adds test.

Handle race between async writeGlobalFile and exportFile

---

src/toil/fileStore.py

Handle job state discovery race 

---

src/toil/lib/docker.py
src/toil/test/lib/dockerTest.py

Current interface not affected, but if parameters argument is a list of lists, instead of a list, then it will be treated as chain of piped commands.  
This is based on  work by @cmarkello here: https://github.com/cmarkello/toil-lib/commit/75c21593abb1c5856d5e4be01ef5c1018cc13104 and is required for toil-vg, where we often pipe a bunch of vg commands together.

Support chains of piped commands in dockerCall

---

index.html

Landing page is looking for stylesheet at http://bd2kgenomics.github.io/static/styles.css instead of http://bd2kgenomics.github.io/toil/static/styles.css

Fix landing page stylesheet (partially addresses #1419)

---

src/toil/batchSystems/abstractBatchSystem.py
src/toil/provisioners/abstractProvisioner.py
src/toil/test/provisioners/aws/awsProvisionerTest.py

Resolves #1485 
First commit updates test to see if it will now replicate the error I saw.

Fix typos in cluster stats mechanism

---

index.html

Add Google Analytics code to landing page (fixes #1419)

---

src/toil/provisioners/aws/awsProvisioner.py

Update CoreOS to new version 

---

src/toil/common.py
src/toil/provisioners/abstractProvisioner.py
src/toil/provisioners/aws/awsProvisioner.py

Handle AWS request limit exceeded

---

src/toil/jobStores/azureJobStore.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/sort/sortTest.py
src/toil/test/src/fileStoreTest.py

Remove ‘experimental’ decorator from Azure tests

---

docs/contributing/source.rst

@chapmanb I have a rough draft of the steps needed to launch a local cluster. Let me know if you have any problems with the setup or any other feedback!

Add notes on launching a local Mesos/Toil cluster

---

src/toil/jobStores/aws/jobStore.py
src/toil/test/jobStores/jobStoreTest.py

Validate key on instantiation 

---

src/toil/jobStores/azureJobStore.py

Bind to Azure resources prior to deletion 

---

src/toil/job.py

The purpose of this PR is to give all jobs access to the underlying fileStore but as a protected class attribute. Before, serviceJob and jobFunctionWrapingJob needed access to the fileStore and the thought was to give access to all jobs as a class attribute. But this creates two sorts of truths—the jobStore that a user passes in to run, and the one associated with the class. By making it protected, it can be safely ignored and is available if the user knows what they are doing. ServiceJob and jobFunctionWrappingJob have a property to mask the protected class to keep one source of truth since they need explicit access to the class attribute.
Changes:
- The protected attribute `_fileStore` is added to `Job` and is set in Job._runner
- `Job.Defer` now uses correct fileStore attribute.
- a …

make fileStore a protected field for Job (resolves #1224)

---

src/toil/resource.py

Fix uninformative assert with require (resolves #1232)

---

src/toil/cwl/cwltoil.py

Add option to disable strict CWL checking

---

src/toil/lib/docker.py
src/toil/test/lib/dockerTest.py

Remove DockerCall dependency on FileStore.jobID

---

src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/provisioners/aws/awsProvisionerTest.py

First commit just adds test. Resolves #1545

Ensure root EBS volume is cleaned up

---

src/toil/batchSystems/singleMachine.py

Use list of items rather than generator 

---

src/toil/jobStores/aws/jobStore.py

Ensure bindBucket is only called when needed 

---

src/toil/jobStores/azureJobStore.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/resource.py

Connected to #1561 
Resolves #1564

Retry Azure importFile, improve Boto throttlePredicate 

---

src/toil/test/provisioners/aws/awsProvisionerTest.py

Retry eventually consistent volume deletion

---

src/toil/common.py

Add disable hot-deployment support (resolves #1569)

---

docs/cli.rst
docs/contributing/contributing.rst
docs/developing.rst
docs/install/cloud.rst
docs/running/cloud.rst
src/toil/jobStores/abstractJobStore.py

Documentation improvements

---

src/toil/lib/docker.py
src/toil/test/lib/dockerTest.py

Resolves #1585
First commit just adds test

Ensure outputs from dockerCall are not owned by root

---

docker/Dockerfile.py
src/toil/test/utils/utilsTest.py

Set appropriate workdir default in Toil Appliance

---

docker/Dockerfile.py
src/toil/batchSystems/mesos/__init__.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/mesos/executor.py
src/toil/test/mesos/MesosDataStructuresTest.py

Resolves #1531 
Resolves #1554

Improve efficiency of Mesos batch system

---

src/toil/provisioners/aws/awsProvisioner.py

Fixes #1609.
(sorry for creating so many tiny PRs in quick succession--just have been running into a lot of separate, easily fixable issues)

Respect AZ config setting (when not using spot instances)

---

docs/developing.rst
docs/jobStore.rst
docs/toilAPI.rst
src/toil/batchSystems/abstractBatchSystem.py
src/toil/job.py
src/toil/jobStores/abstractJobStore.py

Mostly addresses Sphinx build errors and some stylistic changes.

Miscellaneous documentation fixes (linked to #1528)

---

docs/contributing/contributing.rst
docs/install/cloud.rst

Adds step by step instructions for developing with the Toil Appliance.

Add instructions for developing with Toil Appliance (resolves #1611)

---

src/toil/job.py

Quick stab at improving the error message. The current EOFError is really hard to debug, especially since the traceback leads to the unpickling of the job as a whole rather than the unpickling of the promise. This error message points back to the fulfilling job (which presumably hasn't run yet).
Unfortunately, the unpickler goes a bit haywire when you throw an exception during class creation, and the exception gets stacked in on itself with the tuple returned by `Promise.__reduce__`. The output looks like this (`C` is passed a promise from sibling `B`):
```
=========> Failed job 'C' o/h/jobFxT0UY 
---TOIL WORKER OUTPUT LOG---
INFO:toil:Running Toil version 3.7.0a1-3d8272872287e7b0bd2725aa0f857062c69c0a50.
WARNING:toil.resource:Can't find resource for leader path '/home/joel/toil-fresh' …
```

Create an unfulfilled promise sentinel (resolves #517, #1607)

---

src/toil/batchSystems/torque.py
src/toil/common.py

The commercial version of PBS only seems to support JSON output.
The oss version, only does XML.
This PR takes into account this quirk and tries to accomodate for different versions (privative and open).
Thanks @cjfields and @ohofmann for your support.
@cjfields Could you please try this version/commit in your NCSA system just in case I broke something?
@toil_mantainers, the `--disableCache` option is problematic, I would love advice on how to handle it: https://github.com/BD2KGenomics/toil/compare/master...brainstorm:pbspro?expand=1#diff-ec7c0fff4aad88175b4920cd3d1e5f8fR824
I'm aware it has been an issue in the past and @chapmanb managed to address it in PR https://github.com/BD2KGenomics/toil/pull/1090, but I'm not able to let the code below uncommented.

PBSPro support

---

setup.py
src/toil/cwl/cwltoil.py

Synchronizes with latest cwltool and schema-salad containing
fixes for Javascript expression analysis.

CWL: update to latest cwltool/schema-salad

---

src/toil/batchSystems/lsf.py

As with the other batch systems

Add TOIL_LSF_ARGS support (resolves #1639)

---

src/toil/batchSystems/slurm.py

Return tuple instead of None in _getJobDetailsFromScontrol 

---

contrib/azure/agent-0.json
contrib/azure/agent-gt0.json
contrib/azure/azuredeploy.json
contrib/azure/azuredeploy.parameters.json
contrib/azure/configure-mesos-cluster.sh
contrib/azure/master.json

This closes #1644 and #1646, and also lets you deploy some Python packages to your Azure nodes (for things that Toil can't hot-deploy because they need binaries or something).

Update Azure template

---

src/toil/jobStores/aws/jobStore.py

Lower timeout for domain binding in Toil Clean

---

src/toil/job.py

Set proper value for service job preemptable requirement 

---

src/toil/jobStores/fileJobStore.py

Use hard links instead of copied files on import to file job store

---

src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/aws/utils.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/jobStores/jobStoreTest.py

Use chunked transfer in AWS job store importing 

---

run_tests.py
src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/mesos/__init__.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/common.py
src/toil/provisioners/__init__.py
src/toil/provisioners/abstractProvisioner.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/provisioners/clusterScaler.py
src/toil/serviceManager.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/provisioners/clusterScalerTest.py

Work in progress, opening to get an idea of what tests I broke

Improve cluster state tracking

---

src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/singleMachine.py
src/toil/jobStores/fileJobStore.py
src/toil/provisioners/__init__.py
src/toil/provisioners/aws/awsProvisioner.py

Miscellaneous improvements to logging

---

src/toil/test/provisioners/clusterScalerTest.py

The test was flaky because both the preemptable and non-preemptable
scalers would attempt to remove from the same list of workers. This
keeps track of which nodes belong to which scaler, which should fix
the problem.

Fix race in ClusterScaler test (resolves #1719)

---

docs/batchSystem.rst
docs/running/running.rst
src/toil/batchSystems/torque.py

Environmental variable allowing passing of TORQUE scheduler specific parameters
https://github.com/BD2KGenomics/toil/issues/1658

Export TOIL_TORQUE_ARGS

---

run_tests.py

Slight improvement to logging messages in run_tests.py.
@ejacox as you requested.

Add better logging messages to run_tests.py (resolves #1700)

---

src/toil/leader.py
src/toil/test/src/checkpointTest.py
src/toil/worker.py

This adds unit tests for the two bugs described in #1598. Hopefully they both fail!

Checkpointed restart bugs (#1598)

---

setup.py

They ship a manylinux1 wheel which makes install/testing faster

use latest pynacl

---

src/toil/provisioners/aws/awsProvisioner.py

This uses a truncated exponential back-off which was recommended [here](https://forums.aws.amazon.com/thread.jspa?messageID=406788&#406788).

backoff exponentially if AWS throttles (resolves #1837)

---

src/toil/provisioners/aws/awsProvisioner.py

This allows real time logging to work.
(resolves #1818)

Open up UDP traffic within AWS clusters (resolves #1818)

---

docs/architecture.rst
setup.py
src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py

Work in progress, not ready to merge.
Update cwltoil to complete CWL v1.0.1

CWL v1.0.1 support

---

setup.py
src/toil/cwl/cwltoil.py

Fixes related to failing ci.commonwl.org build.  Not ready to merge, requires a cwltool update (in the pipeline).

Fix file permission bugs, handle directory literals correctly.

---

src/toil/batchSystems/options.py
src/toil/common.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/mesos/mesosTest.py
src/toil/test/mesos/stress.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/sort/sortTest.py
src/toil/test/src/promisedRequirementTest.py

Note this is the same as #1668 but reopened.

Set mesosMasterAddress default to private IP (resolves #1664)

---

src/toil/cwl/cwltoil.py

A recent change in 3.10.1 (https://github.com/BD2KGenomics/toil/commit/a909bada25940803f3dc9351fb8b6cd72e3769f0)
caused temporary output directories to get removed prior to finalizing a
Toil step, resulting in missing file errors when the outputs reference
files in the temporary directory. This fixes the issue by putting
them in the defined tempdir. cc @tetron for review.

CWL: avoid early removal of the temporary outdir

---

docker/Dockerfile.py
docs/running/amazon.rst
run_tests.py
src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/common.py
src/toil/leader.py
src/toil/provisioners/__init__.py
src/toil/provisioners/abstractProvisioner.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/provisioners/clusterScaler.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/provisioners/clusterScalerTest.py
src/toil/test/sort/sort.py
src/toil/test/utils/utilsTest.py
src/toil/utils/toilLaunchCluster.py

Not ready for review yet - this is kind of a mess after resolving merge conflicts. Opening PR to see test results.

Allow clusters with multiple node types

---

src/toil/batchSystems/abstractGridEngineBatchSystem.py

D'oh, I didn't notice this when I made #1882.

Fix GridEngine batchSystem when CWL extra isn't installed

---

docs/gettingStarted/install.rst

Clarification on basic/extras installation difference.  

---

Makefile

test_local -> test_offline

---

setup.cfg
src/toil/batchSystems/singleMachine.py
src/toil/common.py
src/toil/test/cwl/cwlTest.py
src/toil/worker.py

[MRG] forkless mode for debugging

---

Makefile
docs/contributing/contributing.rst
docs/developingWorkflows/developing.rst
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/src/multipartTransferTest.py

I tried some of the work arounds that @jessebrennan was suggesting. They were getting complicated quickly. The only needed extra is aws to avoid the errors. This PR just makes a note of that. 
Fixed some bad links in the docs, too.

Py.test collection errors (closes #1919)

---

docs/gettingStarted/quickStart.rst

Cactus: https://github.com/ComparativeGenomicsToolkit/cactus, a reference-free whole-genome multiple alignment program.

Adding a Cactus Example of Running a Workflow with Autoscaling

---

src/toil/cwl/cwltoil.py

Remove unneeded directory literals

---

setup.py

- Fixing workflow default behavior
- Generalize "overrides" by putting them under "requirements" field

bump cwltool to v.1.0.20180108222053

---

src/toil/cwl/cwltoil.py

Needed for running CWL workflows on OS X

expose cwltool's --tmpdir-prefix

---

setup.py

Fixes problems with the default runner for cwl (cwl-runner).

Remove cwl-runner. (#1994)

---

Makefile

I bumped into this issue today, and since it links to a solutiom (which seems to work in my install) I decided to put out a pull request for it.

Check for venv in both py2 and 3. resolves #1985

---

docs/conf.py
setup.py

Added the `sphinxcontrib-fulltoc` requirement.

Sphinx requirement.  Addresses #2020.

---

src/toil/cwl/cwltoil.py

Fixes https://github.com/BD2KGenomics/toil/issues/1786

toil-cwl-runner & fileStore: always link imports

---

setup.py

Hey, #2005 was already closed but I ran into this also and fixed it.

Added protobuf requirement. Addresses #2005.

---

docs/gettingStarted/install.rst

Provide instructions for installing toil without root privileges, as per @mr-c 's instructions.
Thank you @mr-c !

Add doc install instructions for non-root users.  Addresses #2034.

---

src/toil/cwl/cwltoil.py

Fix scheduling related to CWLJobWrapper

---

docs/gettingStarted/quickStart.rst

Made a few fixes to the CWL/AWS documentation.  Notably that one file should be `.yaml` instead of `.cwl`.

AWS/CWL documentation fixes.  Addresses #2073.

---

docker/Dockerfile.py
docs/gettingStarted/install.rst
setup.py

Add mesos reqs to the three cloud reqs.

Add mesos reqs.  Addresses #2054 and #2070.

---

src/toil/cwl/cwltoil.py

From https://gitter.im/bd2k-genomics-toil/Lobby?at=5a8b25cb35dd17022ec7e3c3
~~create a minimal conformance test that triggers this bug~~ Moved to https://github.com/common-workflow-language/common-workflow-language/issues/637

partial fix for MultipleInputFeatureRequirement on workflow outputs

---

src/toil/provisioners/clusterScaler.py

Toil check() should just raise.  Addresses #2097.

---

setup.py
src/toil/cwl/cwltoil.py

Not updating the conformance tests until https://github.com/BD2KGenomics/toil/pull/2053 is merged

get latest cwltool updates, March 2018 edition

---

src/toil/cwl/cwltoil.py

Attention @uniqueg for testing

expose singularity for CWL to toil-cwl-runner

---

dashboard/prometheus/Dockerfile
dashboard/prometheus/run.sh
src/toil/provisioners/aws/__init__.py

Addresses #1987.
Now we can use grafana again.

Update prometheus to fix metrics.  Addresses #1987.

---

src/toil/lib/docker.py

Addresses #2127.
Also attempts to add stdout and stderr piping to `apiDockerCall`.

Amend apiDockerCall.  Addresses #2127.

---

Makefile
src/toil/leader.py

Not ready to merge.  Just for discussion.
fixes #2084

Main loop refactor

---

docs/running/cloud/amazon.rst

Linked the latest docs to #2150 and noticed the instructions were misformatted.

Fix misformatting.

---

src/toil/jobStores/fileJobStore.py

This will hopefully fix #1927, or at least make it less likely to happen. If Toil actually does have a file in the job store open while the job store is being deleted (and it's not just hitting a race condition against the NFS silly rename file cleanup) then it's not really possible for Toil to remove job stores on NFS, and we'll have to find where/why Toil has files open and make it close them.

Add a more robust deleter to the file job store

---

src/toil/test/jobStores/jobStoreTest.py

Added a test for shared file encryption. AWS and Google use server side and Azure uses client side.

Added encryption test.

---

setup.py

Update subprocess backport to 3.5.0.  Addresses #2075.

---

Makefile
setup.py
src/toil/cwl/cwltoil.py

Follow up on https://github.com/BD2KGenomics/toil/pull/2053

 Better support default + source on CWL workflow.step

---

setup.py

Update boto3.  Addresses #2230.

---

src/toil/__init__.py
src/toil/test/src/dockerCheckTest.py

Addresses #2245.
This should cover some of the more exotic repositories out there.

Check non-io docker images.  Addresses #2245.

---

src/toil/cwl/cwltoil.py

Adds an option to specify cloud bucket endpoints for the final outputs
of a CWL workflow. This works (and has been tested) for the following
cases:
AWS S3:
```toil-cwl-runner --destBucket s3://my-bucket-name workflow.cwl config.yaml```
Azure Blob Storage
```toil-cwl-runner --destBucket wasb://container_name@account_name.blob.core.windows.net workflow.cwl config.yaml```
Google Storage:
```toil-cwl-runner --destBucket gs://my-bucket-name workflow.cwl config.yaml```
Make sure you have the right authentication for all three bucket types,
as is detailed in the docs.
Note that the JSON dump at the end still reports that the files are
stored locally, which is something that should be changed eventually
when using the --destBucket option.

Add CWL destBucket runtime option (resolves #2241)

---

src/toil/wdl/wdl_functions.py

Adding a docstring.  Mostly testing jenkins with a fresh PR.

Testing jenkins.

---

docs/gettingStarted/quickStart.rst

Update documentation to clarify how to run the sort example properly.

Create note clarifying purpose of options, recommend deleteing input. Resolves #1928

---

docs/appendices/environment_vars.rst
docs/gettingStarted/quickStart.rst
docs/running/cloud/azure.rst
docs/running/cloud/clusterUtils.rst
src/toil/lib/bioio.py
src/toil/provisioners/azure/__init__.py
src/toil/provisioners/azure/azureProvisioner.py
src/toil/test/provisioners/azureProvisionerTest.py

Adds an environment variable for the user to specify a zone in which instances will be spun up.

Issues/2122 add azure environ var (partially resolves #2122)

---

src/toil/wdl/wdl_analysis.py
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py

Addresses  #2312.
Also added in some handling of optional variables.  Took out strict resource requirements as well until I have more time to handle them properly since they have a few problems that need to be dealt with.

Wdl parsing error.  Addresses  #2312.

---

src/toil/cwl/cwltoil.py

@DailyDreaming hopefully this is what you want. Can you test and confirm?

Expose CWL option --no-match-user (resolve #2290)

---

src/toil/provisioners/azure/__init__.py
src/toil/provisioners/azure/azureProvisioner.py
src/toil/utils/__init__.py
src/toil/utils/toilLaunchCluster.py

Reverts DataBiosphere/toil#2320

Revert "Enable support for specifying zone in all environment variables. Resolves #2319 and# 2295"

---

setup.py

Creating this to deal with strict conflict problems with subprocess32 and other projects in setuptools.

Casual dependency.

---

docs/developingWorkflows/toilAPIBatchsystem.rst

could also be
https://web.archive.org/web/20151204220920/https://blogs.oracle.com/templedf/entry/configuring_a_new_parallel_environment

fixed Oracle SGE parallel environment blog link

---

src/toil/lib/retry.py

Fix https://github.com/DataBiosphere/toil/issues/2350

Retry HTTP connections on BadStatusLine errors

---

src/toil/batchSystems/lsf.py

log LSF job id to error on failure, resolves #2359

---

src/toil/cwl/cwltoil.py
src/toil/job.py
src/toil/lib/encryption/_nacl.py
src/toil/resource.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/worker.py

There are multiple places in Toil where files and directories are left behind.
This PR would clean up those files.

Clean up directories and files left behind by Toil (Resolves #2275)

---

src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/gridengine.py
src/toil/batchSystems/lsf.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/options.py
src/toil/batchSystems/slurm.py

Set the default duration for batch systems with getWaitDuration().  Resolves #2362.  Resolves #2358.

---

src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/slurm.py

Will fix #2381 for all abstractGridEngineBatchSystems

first attempt at adding retries for batch commands

---

docs/developingWorkflows/developing.rst

Fixed syntax error in tutorial code

---

docker/Dockerfile.py

Default to bash on the leader node rather than sh.  Addresses #2434.

---

src/toil/leader.py

`checkForDeadlocks` currently gets run every leader iteration. That wasn't really the original intention -- it was meant to be run only when "nothing happened", i.e. there were no jobs completed or issued that iteration. I think this check may have disappeared in the leader refactor a while back.
`checkForDeadlocks` is fairly expensive because it needs to traverse all running jobs. That means it gets slower as more jobs are running; running the check every iteration makes you hit a hard cap of how many jobs you can actually keep running at any given time. How high that cap is depends on how long your jobs take to finish. In my case it seemed to be at about 300-400 simultaneous jobs. The autoscaler is totally unaware of this, meaning it provisions a *ton* of unusable capacity -- in my …

Fix massive slowdown when many jobs are running

---

dashboard/prometheus/prometheus.yml
dashboard/prometheus/run.sh
src/toil/common.py
src/toil/provisioners/aws/__init__.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/sort/sort.py
src/toil/test/sort/sortTest.py
src/toil/test/utils/utilsTest.py
src/toil/utils/toilStatus.py

Specify region in prometheus.  Addresses #2436.

---

src/toil/cwl/cwltoil.py
src/toil/leader.py
src/toil/test/cwl/cwlTest.py

Addresses  #2477.
Adds the CWL `--preserve-entire-environment` option to toil.

Add preserve-entire-environment option from cwltool.  Addresses  #2477.

---

setup.py
src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py

Right the referenced cwltool version has not been yet released

Update cwltool version to the latest

---

src/toil/common.py
src/toil/provisioners/aws/__init__.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/provisioners/azure/azureProvisioner.py
src/toil/provisioners/gceProvisioner.py

Addresses #2486.
Let me know if this doesn't fix the error @mr-c !

Safeguard unintentional boto imports.  Addresses #2486.

---

Makefile

This should fix #2559 and also replace #2554.

Update pytest and related modules

---

src/toil/utils/toilStats.py

Tolerate missing jobs/workers in stats expando

---

src/toil/jobStores/aws/jobStore.py

Fixes #2596 
Tested on small and large buckets.

Speed up S3 bucket deletion.

---

version_template.py

Ensure TOIL_DOCKER_REGISTRY variable is in version_template.

---

setup.py

Loosen and update the 'requests' package version.

---

contrib/admin/test-pr
docs/contributing/contributing.rst

This will fix #2606.
I had to import a PR for testing, so instead of just doing it I wrote a script.
While I was touching the contributing docs to reference the script, I fixed #2605.

Improve PR import

---

docs/running/cloud/amazon.rst
src/toil/provisioners/aws/awsProvisioner.py

Add a ToilNodeType tag to distinguish leader vs. workers.

---

src/toil/test/cwl/cwlTest.py

Lengthened out the timeout by 10 min (+600 secs)

Lengthening timeout

---

.gitlab-ci.yml
Makefile
run_tests.py
src/toil/test/docs/scriptsTest.py
src/toil/test/lib/dockerTest.py

Separating tests out into  sensible groups.

Rearrange Gitlab Testing.

---

src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/mesos/MesosDataStructuresTest.py
src/toil/test/provisioners/clusterScalerTest.py
src/toil/test/src/checkpointTest.py
src/toil/test/src/fileStoreTest.py
src/toil/test/src/helloWorldTest.py
src/toil/test/src/importExportFileTest.py
src/toil/test/src/jobEncapsulationTest.py
src/toil/test/src/jobFileStoreTest.py
src/toil/test/src/jobGraphTest.py
src/toil/test/src/jobTest.py
src/toil/test/src/miscTests.py
src/toil/test/src/promisedRequirementTest.py
src/toil/test/src/promisesTest.py
src/toil/test/src/realtimeLoggerTest.py
src/toil/test/src/regularLogTest.py
src/toil/test/src/retainTempDirTest.py
src/toil/test/src/systemTest.py
src/toil/test/src/userDefinedJobArgTypeTest.py
src/toil/test/src/workerTest.py
src/toil/test/utils/toilDebugTest.py
src/toil/test/utils/utilsTest.py

Added @travis_test decorators on tests that passed on both travis and gitlab.

Shift tests to travis

---

docker/Dockerfile.py

open new pull request to update ubuntu18.04

Update to ubuntu18.04

---

docker/Dockerfile.py

Updated 16.04 to 18.04 again because the merge didn't go through last time.

updated ubuntu

---

src/toil/cwl/cwltoil.py

Added CWL features

---

src/toil/leader.py
src/toil/utils/toilStatus.py

Changed potential confusing message

changed log output to avoid confusion 

---

src/toil/jobStores/aws/jobStore.py

Added few checks to avoid partial download.

Check for Partial Download

---

docker/Dockerfile.py

Reverted back to ubuntu 16.04.

Revert back to ubuntu16.04

---

src/toil/jobStores/aws/jobStore.py

Reverts DataBiosphere/toil#2731

Revert "Check for Partial Download"

---

docs/running/cliOptions.rst
docs/running/debugging.rst

Closes #2735 
* Document the flag in the CLI reference
* Mention it in the debugging page

Document --debugWorker

---

docs/appendices/environment_vars.rst
docs/developingWorkflows/developing.rst
docs/running/cwl.rst
docs/running/wdl.rst
src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/lib/threading.py

All found by @mr-c for the toil Debian package

More typos

---

src/toil/test/wdl/toilwdlTest.py
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py

WDL basename suffixes honored.

---

src/toil/batchSystems/torque.py

closes #2760 
Added and passed in jobID for torque wrapper.

Passed/Added jobID into Wrapper

---

src/toil/batchSystems/abstractBatchSystem.py

PR that will fix jenkins conformance test.

Conformance test fix

---

src/toil/cwl/cwltoil.py

expose --default-container to toil-cwl-runner

---

setup.py

Closes #2780 .
@jvivian Here ya are.  In the future, any requirement bumps are fine to submit PRs for (the issue can probably even be skipped).

Bump psutil >= 3.0.1, <6.

---

docs/running/cwl.rst

@mr-c perhaps you could let me know how this information could be improved?

Additional documentation for CWL integration

---

src/toil/cwl/cwltoil.py

Fix for passing default values between Workflows (resolves #2814)

---

src/toil/batchSystems/kubernetes.py

This will fix #2835 by making sure only a reasonable number of lowercase ASCII characters, ASCII digits, and `.-` make it to Kubernetes job names.

Turn usernames into non-spooky Kubernetes name components

---

docs/running/cwl.rst

This helps troubleshoot a vexing problem folks on macOS may run into.

Add note about cwltoil and Docker on macOS

---

src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/kubernetes.py
src/toil/test/__init__.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/sort/sortTest.py
src/toil/test/src/deferredFunctionTest.py
src/toil/test/src/fileStoreTest.py
src/toil/test/utils/utilsTest.py

This is the first part of #2837.
I still need the code to setup CI to run the tests, but these tests should test the Kubernetes batch system.
I had to tweak the batch system tests slightly to avoid assuming the batch system runs commands on the machine the tests are running on, and to separate different kinds of AWS access.

Write tests for Kubernetes

---

src/toil/test/jobStores/jobStoreTest.py

Tolerate unnecessary bucket cleanup

---

src/toil/test/src/jobServiceTest.py

Maybe this will make it not fail and fix #2882?

Report more info from and robustify the ToyService

---

contrib/admin/test-pr

Add back the test-pr script referenced in the docs

---

.gitlab-ci.yml
Makefile
setup_gitlab_docker.py
src/toil/batchSystems/kubernetes.py
src/toil/test/batchSystems/batchSystemTest.py
version_template.py

This should fully fix #2837 by enabling the Kubernetes batch system CI tests.
It also moves most of the batch system tests off of Travis, since Travis was always skipping them due to not having e.g. mesos installed. Gitlab at least might run them.

Configure Kubernetes for testing

---

Makefile

Set Docker vars back to ?=

---

src/toil/fileStores/abstractFileStore.py

Actually call the implemented size polling method

---

src/toil/fileStores/cachingFileStore.py

Make sure to commit when giving away files

---

docs/contributing/contributing.rst
src/toil/fileStores/cachingFileStore.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/jobStores/googleJobStore.py
src/toil/lib/misc.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/src/miscTests.py
src/toil/test/src/resumabilityTest.py

Use atomic file copy when writing to posix file system.
Fixes #2897

Issues/2897 Use atomic file copy when writing to posix file system.

---

src/toil/__init__.py

Attempts to fix Cactus that is trying to pickle an open Boto connection.

Fix botocredAdapter

---

src/toil/test/jobStores/jobStoreTest.py

This should actually fix #2893.

Use status to properly get the HTTP status code from boto

---

src/toil/test/src/jobServiceTest.py

Increased numb of retries and the intervals between fails.

Fix Intermittent Failures

---

setup.py

I've tested this with `pip install .[mesos]` and it seems to work.

Compile http-parser so that it doesn't break pip dependencies.

---

src/toil/deferred.py

This fixes #2929 by requiring that the deferred function state file names start with a particular prefix, which is not `.nfs`.

Exclude .nfs files from deferred function search

---

.gitlab-ci.yml
docker/Dockerfile.py
src/toil/__init__.py
src/toil/resource.py
src/toil/test/docs/scriptsTest.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/provisioners/gceProvisionerTest.py
src/toil/test/src/autoDeploymentTest.py
src/toil/test/src/resourceTest.py
src/toil/test/utils/ABCWorkflowDebug/debugWorkflow.py
src/toil/test/utils/utilsTest.py
src/toil/test/wdl/toilwdlTest.py
version_template.py

This is a start on #2742. @DailyDreaming I know it is assigned to you, but I was waiting around for tests to run and I figured I would see if it is actually easy.

Make an appliance for Python 3

---

README.rst
docs/index.rst

add announce mailing list to have a low-volume way to reach users
fixes #2943

added information of announce mailing lists

---

src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/gridengine.py
src/toil/batchSystems/lsf.py
src/toil/batchSystems/slurm.py
src/toil/batchSystems/torque.py

This is #2945 with master merged in so it will actually pass CI tests.

Slurm Job Names

---

setup_gitlab_docker.py
setup_gitlab_ssh.py

Recently did a pull from master and found my changes to get ssh working were overwritten in my python3 branch, so I'm submitting both of these to master on their own.
Docker setup changes just make debugging a bit easier since the try except swallows the custom errors that were in there before.

Update the ssh and docker setup files.

---

src/toil/test/__init__.py
src/toil/test/cwl/cwlTest.py

A minor bug now that I understand it, however this should amend the test to actually work in the way it intended.  Issue is here for more info: https://github.com/DataBiosphere/toil/issues/2974

Actually fail on rev and not du in CWL restart test.

---

src/toil/batchSystems/mesos/executor.py

Encode framework message as utf-8 as well.

---

src/toil/lib/threading.py

I didn't actually mean to PR all these critical-level logging calls in #2982.

Remove logging I had added for testing

---

src/toil/fileStores/abstractFileStore.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/jobStores/googleJobStore.py
src/toil/lib/misc.py

This ought to fix #2986.
Review question: should we also return the size on upload?

Size downloads during download

---

src/toil/fileStores/cachingFileStore.py

While running a new large job, I noticed failures still happening in `_executePendingUploads`, and realized that we're using the default timeout of 5s in those cases. Changing this fixed those errors. We could also wrap all `SELECT` statements in the retry block as well, but this seems to be working pretty good for now.
Issue #2910 
```
Exception in thread Thread-8:
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.6/dist-packages/toil/fileStores/cachingFileStore.py", line 1726, in startCommitThread
self._executePendingUploads(con, cur)
File …
```

Add timeouts to all SQLite connect statements.

---

src/toil/batchSystems/kubernetes.py

Fix connection between Kubernetes and Leader.  #2884

Kubernetes connection with Leader

---

.gitlab-ci.yml
docker/Dockerfile.py
setup.py
src/toil/batchSystems/kubernetes.py

Hopefully these work, will just wait on tests to confirm.

Use forked pymesos and http-parser dependencies.

---

src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/gridengine.py
src/toil/batchSystems/lsf.py
src/toil/batchSystems/slurm.py
src/toil/batchSystems/torque.py
src/toil/lib/misc.py
src/toil/test/src/miscTests.py

**WARNING: this has not been tests I have no access to test batch systems.  People who use them will have to test them before merging into master.**
Log results from HPC batch system commands before parsing.
Check status of calls to batch system commands.
Add popen_communicate that does both subprocess Popen and communicate and
checks for errors.  Also includes stderr in exception that is raised.

Attempt to make batch system more robust and debuggable

---

Makefile
docs/appendices/environment_vars.rst
setup.py
src/toil/batchSystems/kubernetes.py
src/toil/batchSystems/options.py
src/toil/common.py
src/toil/lib/threading.py
src/toil/test/docs/scripts/example_cachingbenchmark.py
src/toil/test/src/threadingTest.py

This will eventually fix #2988.

Kubernetes Shared Caching

---

src/toil/batchSystems/mesos/batchSystem.py
src/toil/utils/toilMain.py

Once toil-http-parser was fixed, apparently the deprecated `iteritems` was no longer imported in batchsystems:
```
Could not retrieve logs due to: ''dict' object has no attribute 'iterkeys''.
File "/usr/local/lib/python3.6/dist-packages/toil/batchSystems/mesos/batchSystem.py", line 774, in _handleFailedExecutor
for filename in filesDict.iterkeys():
AttributeError: 'dict' object has no attribute 'iterkeys'
```
Instead of adding back the `six` import, I took out the old py2 stuff and did a little refactoring.

Refactor and remove deprecated iteritems.

---

src/toil/__init__.py
src/toil/resource.py

I think that this should fix #3034. I should probably test manually it once the Docker builds.

Detect more kinds of virtual environment and normalize prefixes

---

src/toil/batchSystems/gridengine.py

always honor TOIL_GRIDENGINE_PE and never assume a site-dependent default

---

src/toil/worker.py

This will fix #3051 by making job failures (that don't break the worker) legible to the batch system. You also might be able to see them with any sort of cluster analytics you might have.

Exit the worker with 1 when jobs fail so the batch system can see

---

src/toil/batchSystems/kubernetes.py

This should fix #3066.
When the Docker builds I still need to actually try it on Kubernetes to make sure it really does pass along the errors promptly instead of retrying them.

Handle anticipated 404 errors without retrying

---

src/toil/provisioners/aws/awsProvisioner.py
src/toil/provisioners/gceProvisioner.py
src/toil/test/provisioners/aws/awsProvisionerTest.py

Test and reimplement AMI finding via Flatcar JSON feed

---

src/toil/cwl/cwltoil.py

chaining doesn't make sense for CWL

---

src/toil/batchSystems/lsf.py
src/toil/batchSystems/lsfHelper.py

This is a collection of stability fixes on the LSF batchsystem that we have implemented through our experience of using it on our LSF cluster. 
Resolves: #3097
Resolves: #3098 
Resolves: #3099 
Resolves: #3100

Improve lsf batchsystem stability

---

src/toil/cwl/cwltoil.py

move conditional execution test to before fill_in_defaults

---

src/toil/batchSystems/kubernetes.py

This should fix #3125 by wrapping calls to the Kubernetes watch API with something that will suppress network-y errors that happen inside the `stream()` generator itself, so that a disconnect during a stream operation doesn't crash the whole workflow. Instead, it will just end the watch early (rather than starting a new watch for any remaining timeout, which is more work).

Wrap Kubernetes watches to fix #3125

---

src/toil/statsAndLogging.py

Potential fix for https://github.com/DataBiosphere/toil/issues/3129

potential fix for log file being linked more than once

---

setup.py

Fixes #3138 
This PR also allows for a bit more flexibility in the dependencies; if this is undesired I can clamp them back down.

Update dependencies and loosen restrictions slightly

---

src/toil/cwl/cwltoil.py

Fixes #3141 
Related: https://github.com/common-workflow-language/cwl-v1.2/pull/48

ensure that falsey (but non-null) values are considered

---

src/toil/test/wdl/toilwdlTest.py
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py

This completes part 1 for #3150 and #3151.

Add ceil() and floor() WDL functions

---

src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/aws/utils.py
src/toil/test/jobStores/jobStoreTest.py

@adamnovak This was merged prematurely.  Undoing this until review comments are addressed: https://github.com/DataBiosphere/toil/pull/3153
@w-gao Please reopen the pull request.  Sorry about that, but Adam merged while I was mid-review.

Revert "Move AWS job store uploads/downloads to boto3".

---

docs/running/cliOptions.rst
docs/running/introduction.rst
src/toil/batchSystems/options.py
src/toil/batchSystems/registry.py
src/toil/test/sort/sortTest.py
src/toil/test/src/promisedRequirementTest.py
src/toil/test/src/regularLogTest.py

Added choices argparse to list of uniqueNames().

batchSystem generates a key error instead of a usage message 

---

src/toil/test/wdl/builtinTest.py
src/toil/test/wdl/standard_library/write_json.json
src/toil/test/wdl/standard_library/write_json_as_command.wdl
src/toil/test/wdl/standard_library/write_lines.json
src/toil/test/wdl/standard_library/write_lines_as_command.wdl
src/toil/test/wdl/standard_library/write_map.json
src/toil/test/wdl/standard_library/write_map_as_command.wdl
src/toil/test/wdl/standard_library/write_tsv.json
src/toil/test/wdl/standard_library/write_tsv_as_command.wdl
src/toil/wdl/wdl_analysis.py
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py

WDL functions added:
- write_lines(),
- write_tsv(),
- write_json(), and
- write_map()
This completes #3162, #3163, #3164, and #3165.

Add WDL write functions and builtin tests

---

src/toil/lib/ec2.py
src/toil/provisioners/aws/awsProvisioner.py

Just fixing a couple of small bugs in PR #3145 that I noticed after rebasing to head.

Fix boto3 migration bugs.

---

src/toil/batchSystems/kubernetes.py

A/C:
Add labels to pods and jobs.
Refactor existing search to work with the labels. 
Issue Ticket:
https://github.com/DataBiosphere/toil/issues/3232

Adding Labels to Pods/Jobs

---

src/toil/test/wdl/builtinTest.py
src/toil/test/wdl/standard_library/sub.json
src/toil/test/wdl/standard_library/sub_as_input.wdl
src/toil/test/wdl/standard_library/sub_as_input_with_file.wdl
src/toil/test/wdl/toilwdlTest.py
src/toil/wdl/wdl_analysis.py
src/toil/wdl/wdl_functions.py

Add WDL builtin test 'sub'.

---

src/toil/lib/retry.py

Make kubernetes & botocore packages fully optional

---

src/toil/test/wdl/builtinTest.py
src/toil/test/wdl/standard_library/size.json
src/toil/test/wdl/standard_library/size_as_command.wdl
src/toil/test/wdl/standard_library/size_as_output.wdl
src/toil/wdl/wdl_analysis.py
src/toil/wdl/wdl_functions.py

Add WDL builtin test 'size'. 

---

docs/appendices/environment_vars.rst

Add kube_watch_enabled into documentation

---

src/toil/test/wdl/builtinTest.py
src/toil/test/wdl/standard_library/transpose.json
src/toil/test/wdl/standard_library/transpose_as_input.wdl
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py

Add transpose() WDL function

---

setup.py
src/toil/cwl/cwltoil.py

Should fix #3223 once https://github.com/common-workflow-language/cwltool/pull/1350 is added to new cwltool version.

Automatically infer singularity for kubernetes

---

.gitlab-ci.yml
Makefile
common.mk
setup.py
src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/options.py
src/toil/batchSystems/registry.py
src/toil/common.py
src/toil/jobStores/aws/jobStore.py
src/toil/lib/ec2nodes.py
src/toil/test/batchSystems/batchSystemTest.py

This changes our tests to use `make` and to enable code coverage by default.  This also includes some minor refactors.

Add coverage and refactor.

---

src/toil/batchSystems/options.py
src/toil/common.py

Expose --statePollingWait param through toil

---

src/toil/lib/misc.py
src/toil/provisioners/aws/__init__.py

Was closing old branches, guess I forgot to submit this one.
* Replace custom mean and std_deviation with built-ins.

Remove custom math functions and replace with built ins.

---

src/toil/test/wdl/builtinTest.py
src/toil/test/wdl/standard_library/zip.json
src/toil/test/wdl/standard_library/zip_as_input.wdl
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py

Add WDL zip() function + tests.

---

src/toil/test/wdl/builtinTest.py
src/toil/test/wdl/standard_library/cross.json
src/toil/test/wdl/standard_library/cross_as_input.wdl
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py
src/toil/wdl/wdl_types.py

Closes #3199. 
* Add cross() WDL function.

Add WDL cross() function + tests.

---

src/toil/lib/memoize.py

Removed functions that appear to be unused.
* Clean up memoize.py.

Clean up memoize.py.

---

setup.py
src/toil/test/cwl/cwlTest.py

* Update to the latest cwltool (3.0.20201121085451 -> 3.0.20201203173111).

Update to the latest cwltool.

---

src/toil/batchSystems/lsf.py
src/toil/job.py

Resolve #3383 - Regular division for memory calculation

---

src/toil/jobStores/googleJobStore.py
src/toil/test/jobStores/jobStoreTest.py

Fix failing Google jobstore tests

---

.gitlab-ci.yml

* Add deadsnakes ppa for new CI/CD in Ubuntu 20.04.

Add deadsnakes ppa for new CI/CD in Ubuntu 20.04.

---

src/toil/test/wdl/builtinTest.py
src/toil/test/wdl/standard_library/as_map.json
src/toil/test/wdl/standard_library/as_map_as_input.wdl
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py

Closes #3201.
* Add as_map() WDL function.

Add WDL as_map() function.

---

.gitlab-ci.yml

This should fix the currently failing CI/CD.
* Update apt and fix the currently failing CI/CD.
```
```

Apt update first.

---

.gitlab-ci.yml
Makefile
contrib/admin/mypy-with-ignore.py
src/toil/lib/resources.py
src/toil/test/utils/toilDebugTest.py
src/toil/utils/toilDebugFile.py
src/toil/wdl/wdl_functions.py

This should make all new files and all currently passing files beholden to mypy, and creates an additional linting step prior to any code test runs, so failure should be fairly quick if mypy complains.
Note that this PR contains an explicit list of ignored files.  Removing the ignored files from the list is progress made towards having the entire project under mypy.  It's a bit of work so I expect it will be done in chunks.  It's also hard to account for files which lack typing entirely (and thus pass).
* Add mypy checking step to cicd.  Consolidate glob functions into one.
```
```

Add mypy checking.

---

requirements-dev.txt
src/toil/lib/io.py

Not needed, a continuation of https://github.com/DataBiosphere/toil/pull/3458
```
```

fix type hints, upgrade mypy

---

src/toil/provisioners/aws/awsProvisioner.py

* `toil destroy-cluster` will no longer destroy all tagged autoscaling groups in the entire AWS account
```
```

Stop deleting all ASGs with tags

---

src/toil/test/wdl/builtinTest.py
src/toil/test/wdl/standard_library/collect_by_key.json
src/toil/test/wdl/standard_library/collect_by_key_as_input.wdl
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdl_synthesis.py

Closes #3203. 
I checked against cromwell and miniwdl and it seems like this is another case where cromwell diverges from the spec (Cromwell returns a `Array[Pair[X, Array[Y]]]` instead of `Map[X, Array[Y]]` according to the [spec](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#-mapp-arrayy-collect_by_keyarraypairp-y)). 
* Add WDL collect_by_key() function.
```
```

Add WDL collect_by_key() function + tests.

---

.travis.yml
Makefile
requirements-dev.txt

Replaces https://github.com/DataBiosphere/toil/pull/3491
* Code contributions are now automatically checked for missing or incorrect type hints
```
```

diff-cover mypy

---

.gitlab-ci.yml
Makefile
setup.cfg
src/toil/common.py
src/toil/fileStores/abstractFileStore.py
src/toil/fileStores/cachingFileStore.py
src/toil/fileStores/nonCachingFileStore.py
src/toil/job.py
src/toil/lib/humanize.py

Resolves #3030 .
* Add extra context for disk usage warning.
```
```

Add extra context for disk usage warning.

---

src/toil/jobStores/aws/utils.py

Resolves #3483 and #1837.
```
```

Retry on s3 throttling.

---

.gitlab-ci.yml
src/toil/lib/ec2.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/lib/test_ec2.py

* Use back-up flatcar AMI if not found.
```
```

Use back-up flatcar AMI if not found.

---

src/toil/lib/retry.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/src/jobFileStoreTest.py
src/toil/test/src/jobServiceTest.py
src/toil/test/src/promisedRequirementTest.py

Current flaky issues that this adds retries for:
- #3511: SingleMachinePromisedRequirementsTest.testConcurrencyStatic
- #3478: MaxCoresSingleMachineBatchSystemTest.test
- #3461: testJobFileStore
- #3372: KubernetesBatchSystemTest.testRunJobs
- #3361: SingleMachineBatchSystemJobTest.testConcurrencyWithDisk
- #3127: jobServiceTest.JobServiceTest-testServiceParallelRecursive
* Add decorator for flaky tests.
```
```

Add decorator for flaky tests.

---

src/toil/test/provisioners/aws/awsProvisionerTest.py

Fix #3523 by only looking for the Flatcar AMI when we have AWS credentials
* Flatcar image finding tests don't run without AWS credentials
```
```

Insist on credentials for testing AMI finding

---

src/toil/batchSystems/kubernetes.py

Should fix #3521
* Pods are now deleted when the Kubernetes batch system shuts down, when it has batch delete permission
```
```

Add a propagation policy to batch delete

---

src/toil/common.py

This ~is built on top of #3482 and~ will fix #3499.
~I may want to rebase it onto master instead; I've been using this branch to run workflows but I don't think I actually need some of the underlying commits for that to work.~
* User script will only be deployed on restart if actually supported by the new batch system
```
```

Skip hot deploy if impossible on restart

---

src/toil/test/jobStores/jobStoreTest.py

Adds a unittest for #2707.
* Add test for parallel file import on S3
```
```

Add test for parallel file import on S3

---

docs/appendices/environment_vars.rst
docs/conf.py
docs/vendor/sphinxcontrib/__init__.py
docs/vendor/sphinxcontrib/fulltoc.py
requirements-dev.txt
src/toil/job.py

Resolves #3532.  Main problem seems to have been that `docutils` updated to `0.17` and wasn't pinned, so we need to stick with `0.16`.
Error looks like:
```
$ make docs
cd docs && make html
make[1]: Entering directory '/builds/databiosphere/toil/docs'
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v3.3.1
Encoding error:
'ascii' codec can't decode byte 0xc2 in position 69: ordinal not in range(128)
The full traceback has been saved in /tmp/sphinx-err-x24a2szt.log, if you want to report the issue to the developers.
make[1]: Leaving directory '/builds/databiosphere/toil/docs'
make[1]: *** [Makefile:55: html] Error 2
make: *** [Makefile:193: docs] Error 2
```
https://ucsc-ci.com/databiosphere/toil/-/jobs/80902 …

Fix make docs.  Clear up warnings.

---

.travis.yml
Makefile

We'll be launching a campaign to introduce type hinting to the entire code base, file by file.  In the meantime, this should help things by not immediately failing all new PRs.  I think our type hinting is just too bad right now for the diff to be this strict.  I think it will be good to raise it back once we've made some good progress on adding type hinting to the rest of the code base.
* Make mypy more tolerant.
```
```

Make mypy more tolerant.

---

contrib/toil-cwl-runner/README.rst
contrib/toil-cwl-runner/pyproject.toml
contrib/toil-cwl-runner/setup.cfg
setup.py

Fixes #3566
* To prevent typo-squatting, `pip install toil-cwl-runner` acts as a shortcut for `pip install toil[cwl]`
```
```

pip install toil-cwl-runner → toil[cwl]

---

src/toil/cwl/cwltoil.py

The MPI configuration file needs to be loaded by `MpiConfig.load()`, so this PR adds the import and call, following those done in `cwltool`. This fixes the issue with the MPI config file being ignored (see #3517).
* [CWL] Fix loading of MPI config, if specified
```
```

Use cwltool's MpiConfig.load() to handle MPI config file

---

docs/running/cloud/amazon.rst
src/toil/provisioners/node.py

Not a fix but could potentially close #2006. Users should have ssh-agent set up if needed. 
* Provide additional info when "Permission denied" error is encountered
```
```

Provide additional info when "Permission denied" error is encountered

---

.gitlab-ci.yml
src/toil/common.py
src/toil/jobStores/abstractJobStore.py
src/toil/lib/aws/__init__.py
src/toil/lib/ec2.py
src/toil/provisioners/aws/__init__.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/provisioners/aws/boto2Context.py
src/toil/test/docs/scriptsTest.py

Resolves #3565.
* Fix cwl and wdl dependency bleed and add stand alone tests.
```
```

Fix cwl and wdl dependency bleed and add stand alone tests.

---

docs/appendices/environment_vars.rst
src/toil/common.py

This will fix #3585. I had to use this when debugging toil-vg runs for the Giraffe paper.
* Work directory paths can be overridden with `TOIL_WORKDIR_OVERRIDE` when using `toil debug-job` to run a job outside its workflow
```
```

Allow workdir override

---

src/toil/jobStores/aws/jobStore.py

This will fix #3583. I used this change to run toil-vg for the Giraffe paper.
* Malformed AWS jobs with missing `overlargeID`s can be deleted
```
```

Allow cleaning up a job whose overlargeID fell off

---

contrib/admin/mypy-with-ignore.py
src/toil/lib/conversions.py

Adds type hints to src/toil/lib/encryption/conversions.py so it can be checked under mypy during linting.
Should fix #3589.
Type hints added to:
* `convert_units()`
```
```

Add type hints to conversions.py

---

.gitlab-ci.yml
src/toil/wdl/versions/v1.py

* Update cactus test to fix broken bucket links.
```
```

Update cactus test to fix broken bucket links.

---

docs/running/cloud/amazon.rst

I accidentally broke the "Running in AWS" documentation numbering in #3579, and this PR attempts to fix it. 
* 
```
```

Fix AWS docs numbering

---

contrib/admin/mypy-with-ignore.py
src/toil/utils/toilKill.py

Adds type hints to src/toil/utils/toilKill.py so it can be checked under mypy during linting.
Fixes #3600.
Type hints added to:
* `main()`
```
```

Add type hints to toilKIll.py

---

src/toil/batchSystems/singleMachine.py

Fixes jobCommand unpack

---

src/toil/batchSystems/lsfHelper.py

Resolves: #3604
Description in #3604 
```
```

fix non integers lsf memory requested

---

src/toil/batchSystems/lsfHelper.py

Removed extra memory multiplication

---

src/toil/common.py

(resolves #3602)
* `getNodeId()` now will always return something interpretable as a UUID
```
```

Enforce valid uuid from getNodeId()

---

contrib/admin/mypy-with-ignore.py
src/toil/utils/toilClean.py

Adds type hints to src/toil/utils/toilClean.py so it can be checked by mypy during linting.
Should fix #3613.
Type hints added to:
* `main()`
```
```

Add type hints to toilClean.py

---

contrib/admin/mypy-with-ignore.py
src/toil/utils/toilDestroyCluster.py

Added type hints to src/toil/utils/toilDestroyCluster.py so it can be checked by mypy during linting.
Fixes #3621.
Type hints added to:
* `main()`
```
```

Add type hints to toilDestroyCluster.py

---

contrib/admin/mypy-with-ignore.py
src/toil/utils/toilSshCluster.py
src/toil/utils/toilUpdateEC2Instances.py

Add type hints for utils files so they can be checked under mypy during linting.
Fixes #3632, #3633, will be adding more
```
```

Add type hints for utils files 

---

contrib/admin/mypy-with-ignore.py
src/toil/lib/threading.py

Add type hints to src/toil/lib/threading.py so it can be checked under mypy during linting.
Fixes #3648.
```
```

Add type hints to threading.py

---

contrib/admin/mypy-with-ignore.py
src/toil/lib/ec2nodes.py

Add type hints to src/toil/lib/ec2nodes.py so it can be checked under mypy during linting.
Fixes #3646.
```
```

Add type hints to ec2nodes.py

---

contrib/admin/mypy-with-ignore.py
src/toil/utils/toilDebugFile.py

Adds type hints to src/toil/utils/toilDebugFile.py so it can be checked under mypy during linting.
Fixes #3631.
```
```

Add type hints to toilDebugFile.py

---

src/toil/test/docs/scripts/tutorial_staging.py
src/toil/test/docs/scriptsTest.py

Changes the encoding from binary to string in `tutorial_staging.py` and adds it under testing: https://github.com/DataBiosphere/toil/blob/master/src/toil/test/docs/scriptsTest.py
Resolves #3650.
```
```

Set encoding to string in tutorials

---

.github/PULL_REQUEST_TEMPLATE.md

* The pull request template is now more clear on where to write the proposed changelog entry and who should write it.
```
```

Better explain where to write the changelog entry

---

contrib/admin/mypy-with-ignore.py
src/toil/jobStores/abstractJobStore.py

Added type hints to src/toil/jobStores/abstractJobStore.py so it can be checked under mypy during linting.
Fixes #3658.
```
```

Add type hints to abstractJobStore.py

---

contrib/admin/mypy-with-ignore.py
src/toil/utils/toilLaunchCluster.py

Adds type hints to src/toil/utils/toilLaunchCluster.py so it can be checked under mypy during linting.
Fixes #3630.
```
```

Add type hints to toilLaunchCluster.py

---

docs/running/cliOptions.rst
src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/lsf.py
src/toil/batchSystems/options.py
src/toil/common.py

re-work of #3607 
Resolves: #3606
Description in #3606
* Added --coalesceStatusCalls for the LSF batch system
```
```

 Add lsf batch status call

---

contrib/admin/mypy-with-ignore.py
src/toil/statsAndLogging.py

Adds type hints to `src/toil/statsAndLogging.py` so it can be checked under mypy during linting.
Fixes #3681.
```
```

Add type hints to statsAndLogging.py

---

contrib/admin/mypy-with-ignore.py
src/toil/realtimeLogger.py

Adds type hints to `src/toil/realtimeLogger.py` so it can be checked under mypy during linting.
Fixes #3683.
```
```

Add type hints to realtimeLogger.py

---

contrib/admin/mypy-with-ignore.py
src/toil/lib/memoize.py

Adds type hints to `src/toil/lib/memoize.py` so it can be checked under mypy during linting.
Fixes #3687.
```
```

Add type hints to memoize.py

---

contrib/admin/mypy-with-ignore.py
src/toil/lib/humanize.py

Adds type hints to `src/toil/lib/humanize.py` so it can be checked under mypy during linting.
Fixes #3690.
```
```

Add type hints humanize.py

---

.gitlab-ci.yml

* Update Toil's main python test version to 3.8.
```
```

Update Toil's main python test version to 3.8.

---

contrib/admin/mypy-with-ignore.py
src/toil/wdl/wdl_types.py

Adds type hints to `src/toil/wdl/wdl_types.py` so it can be checked under mypy during linting.
Fixes #3700.
```
```

Add type hints to wdl_types.py

---

src/toil/test/lib/aws/test_s3.py

The buckets created by `S3Test::test_create_bucket()` are not cleaned up. This PR attempts to fix that. 
```
```

Clean up S3Test::test_create_bucket() buckets

---

docs/running/cwl.rst

Fix CWL in toil docs jobstore usage

---

.gitlab-ci.yml
requirements-dev.txt
setup.py
src/toil/test/cwl/cwlTest.py

This is an alternative to #3719 and will fix #3542 through #3564 if it passes the CWL 1.2 Kubernetes conformance tests consistently. 
* Kubernetes batch system now tested for as much conformance to CWL 1.2 as is possible with Singularity containers
```
```

Turn on all Kubernetes CWL tests that are expected to work on Singularity

---

setup.py
src/toil/cwl/__init__.py
version_template.py

Attempts to close #2555. 
* Warn users if a different cwltool version is installed. 
```
```

Warn users if a different cwltool version is installed

---

src/toil/provisioners/__init__.py
src/toil/provisioners/abstractProvisioner.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/provisioners/gceProvisioner.py
src/toil/test/provisioners/aws/awsProvisionerTest.py

Closes #3714. 
* Add storage system to the AWS provisioner
```
```

Add AWS provisioner storage system

---

docs/appendices/environment_vars.rst
src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/gridengine.py
src/toil/batchSystems/htcondor.py
src/toil/batchSystems/kubernetes.py
src/toil/batchSystems/lsf.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/batchSystems/parasol.py
src/toil/batchSystems/singleMachine.py
src/toil/batchSystems/slurm.py
src/toil/batchSystems/torque.py
src/toil/leader.py
src/toil/test/batchSystems/batchSystemTest.py

Attempts to fix #3573.
* Add per-job environment variables to batch systems & set number of cores based on `job.cores` for OpenMP applications
```
```

Set number of cores based on job.cores for OpenMP applications

---

src/toil/batchSystems/lsfHelper.py

This PR fixes  https://github.com/DataBiosphere/toil/issues/3750 
I tracked and fixed the issue with the help of @ddomenico 
* LSF users don't get errors from `lsadmin` and `bparams` printed in their logs anymore.
```
```

Redirect stderr to /dev/null of lsf conf queries

---

src/toil/batchSystems/registry.py
src/toil/test/batchSystems/batchSystemTest.py

Attempts to fix #3618.
```
```

Add back addBatchSystemFactory function

---

docs/developingWorkflows/developing.rst
src/toil/common.py
src/toil/jobStores/abstractJobStore.py
src/toil/test/src/fileStoreTest.py
src/toil/test/src/importExportFileTest.py

When importing relative file paths without a schema, it can be unclear how Toil is attempting to resolve those paths.  This forces the base importFile method to add a local "file://" schema when no schema is found, to adjust it to an absolute path, and include an appropriate error message (early) helpful to users if the file does not exist.
A short blurb in the docs has also been updated on use.
* Attempt to use absolute local paths when ImportFile does not detect a schema.
```
```

Attempt to use absolute local paths when exportFile/importFile do not detect a schema.

---

src/toil/worker.py

I don't think the workflow should break if everything was successful but we can't clean up.
* Prevent exception from being raised when modifying dir permissions for clean up.
```
```

Prevent exception from being raised when modifying dir permissions for clean up.

---

src/toil/jobStores/fileJobStore.py
src/toil/test/jobStores/jobStoreTest.py

Fix #3794 by preventing hardlinks to symlinks from leaking out of the FileJobStore.
* `readGlobalFile(symlink=False)` can no longer produce a hardlink to a symlink with FileJobStore and linked imports.
```
```

Don't leak symlinks

---

setup.py
src/toil/cwl/__init__.py
src/toil/cwl/cwltoil.py
src/toil/cwl/utils.py

* cwl: add podman support; and other fixes from recent cwltool
```
```

cwl: add podman support; and other fixes from recent cwltool

---

src/toil/cwl/cwltoil.py
src/toil/test/jobStores/jobStoreTest.py

This PR will fix the CWL conformance tests, once we get a non-empty log to figure out why some of them time out on Kubernetes.
```
```

Fix CWL conformance tests

---

Makefile

Resolve remainder of issue #1812 by adding make uninstall to makefile, and removing uninstall part from make clean to adhere to makefile targets.
```
```

Add make uninstall to makefile

---

src/toil/lib/aws/utils.py

Adjust cleanup script.

---

src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/cwl/cwltoil.py
src/toil/test/utils/toilKillTest.py
src/toil/utils/toilKill.py

This PR is to get #3932 and #3893 merged, and fixes some nits I found and some CI failures.
We still won't get the PID of the leader out for job stores other than File, so we can't kill the leader on an AWS job store even if it's on the same machine. In addition to doing that it would be great to have a leader termination flag file in there so we can `toil kill` from any machine that can see the batch system, and not just the same machine, as long as the leader is responsive.
* A fix for issue 3884. The goal of this PR is to give more detailed names for jobnames in HPC schedulers. We would like to be able to check the status of a step of a workflow and/or delete a workflow.
* Fix …

PolusAI Fixes

---

src/toil/cwl/cwltoil.py

* CWL: Small adjustments to logging; include step name & scatter index (if used) in the unitName.
```
```

CWL logging tweaks; include step name & scatter index in the unitName

---

src/toil/common.py

This should again fix #3888 (and any hangups in other workflows run against our Kubernetes cluster) by looking for lost jobs much more often. When the chaos gremlins in our Kubernetes cluster delete our finished jobs before they are supposed to, we will notice and re-issue the jobs (and then notice they are already completed) before the conformance test timeout.
* Toil now looks for lost jobs every minute instead of every hour
```
```

Rescue fast enough to protect conformance tests

---

src/toil/common.py

Fix for --metrics #3943. Rename `nodeType` to `instance_type` in common.py
* Toil-managed cluster scaling should work again with `--metrics`
```
```

Rename nodeType to instance_type

---

contrib/tes/funnel/kubernetes/setup.yml

I made a TES server on our Kubernetes for testing the TES batch system, and I don't want the YAMLs for that to get lost, so here they are.
* TES on Kubernetes setup example now available in contrib
```
```

Add TES server setup example

---

src/toil/batchSystems/torque.py

This fixes #3715 by warning the user if Torque doesn't give a running job a wall clock time, instead of just crashing.
It also changes some weird behavior that we've had forever around the case where we might get "0" instead of an H:M:S duration.
* Torque jobs missing a wall clock time no longer crash Toil
```
```

Tolerate missing wall clock times from Torque

---

src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py
src/toil/test/cwl/echo_string_scatter_capture_stdout.cwl

If you use scatter and collect files, you can now correctly detect duplicates.  Follow the same behavior that cwltool does.
Fix https://github.com/DataBiosphere/toil/issues/3960
```
```

Issue/3960 scatter outputs should not clash (#3)

---

src/toil/worker.py

* CWL: at the end of a job, ask cwltool to cleanup
```
```

ask cwltool to cleanup, if installed

---

docker/Dockerfile.py
docker/singularity-sources.tsv

This will fix #4006.
* Singularity is now installed from https://snapshot.debian.org/ so it can't change.
```
```

Add more static URLs for Singularity debs

---

requirements-server.txt
src/toil/server/wes/abstract_backend.py

This will fix #4010.
* Toil server now typechecks when installed with Werkzeug 2.
* Toil server now requires Werkzeug 2.
```
```

Tolerate and require typed Werkzeug

---

src/toil/cwl/cwltoil.py

square bracket to period separator.  
Fix [issue 4004](https://github.com/DataBiosphere/toil/issues/4003)
```
```

feat: square bracket to period separator

---

Makefile
attic/README.md
src/toil/__init__.py
src/toil/batchSystems/kubernetes.py
src/toil/cwl/cwltoil.py
src/toil/job.py
src/toil/jobStores/utils.py
src/toil/provisioners/abstractProvisioner.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/src/resourceTest.py
version_template.py

Assorted typos to fix issue #3699 
```
```

Fix assorted typos within assorted comments

---

requirements-aws.txt
src/toil/lib/aws/utils.py

Fixes #4028 
* small type change as boto3-stubs fixed a bug; drop unneeded `futures` dependency
```
```

bug is fixed in mypy_boto3

---

src/toil/batchSystems/kubernetes.py
src/toil/test/__init__.py
src/toil/test/batchSystems/batchSystemTest.py

This will fix #3946 by adding label selectors and tolerations for the preemptability labels and taints that Google GKE uses.
* Toil Kubernetes jobs now understand `cloud.google.com/gke-preemptible=true` node labels and taints
```
```

Add and test preemptability constraints

---

src/toil/provisioners/__init__.py
src/toil/provisioners/aws/awsProvisioner.py

* Toil will no longer attempt to start ARM clusters with the non-ARM-supporting Mesos cluster framework.
```
```

Stop people asking for ARM Mesos clusters to fix #4057

---

src/toil/test/batchSystems/batchSystemTest.py

* Concurrency-measuring tests should randomly fail less often
```
```

Leave more time for concurrency measurement to fix #4012

---

src/toil/cwl/cwltoil.py
src/toil/lib/aws/__init__.py

This fixes #4066 and also an untracked bug I found in my AGC integration work.
* Toil can properly get the AWS region when running on ECS on EC2
* `toil-cwl-runner` no longer prints out local paths when uploading output files to a `--destBucket` (#4066)
```
```

More AGC integration

---

src/toil/batchSystems/singleMachine.py

Bringing back the kill loop removed in #3974 when the single_machine batch system exits, but with a timeout this time. This should hopefully fix #4024.
* Bring back kill loop in the single_machine batch system but with a timeout
```
```

Bring back kill loop in the single_machine batch system but with a timeout

---

.gitlab-ci.yml
docker/Dockerfile.py
src/toil/batchSystems/kubernetes.py
src/toil/batchSystems/mesos/batchSystem.py
src/toil/lib/misc.py
src/toil/provisioners/abstractProvisioner.py
src/toil/test/lib/test_misc.py

This will fix #4056 and thus https://github.com/ComparativeGenomicsToolkit/cactus/issues/677, by handling the case where going to get the current user name throws an exception instead of producing a user name. In those cases, we will now use a fake user name string.
I had to revise the test system a bit to support running my new test file that I added to test this feature.
* Toil will no longer crash if the current user isn't in `/etc/passwd`. 
* Toil Docker images now use Ubuntu 20.04 and Mesos 1.11.
```
```

Allow missing username and fix Docker build

---

src/toil/common.py
src/toil/job.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/server/wes/amazon_wes_utils.py
src/toil/test/__init__.py

This will fix #4089 by only importing from typing_extensions if we actually required it at installation. We need and install it on Python <3.8, so we should only use it on Python <3.8.
* Toil now only imports `typing_extensions` if it actually required it as a dependency.
```
```

Only import from typing_extensions on old Python where we install it

---

docs/developingWorkflows/toilAPIBatchsystem.rst

* Update documentation to mention `--export=ALL` for SLURM environments
```
```

Mention --export=ALL for SLURM environments (#4100)

---

.gitlab-ci.yml
Makefile
setup.cfg

Closes #4079. This registers the pytest markers that we use and includes the `--strict-markers` flag to pytest to fail tests that have unrecognized markers.
* Register pytest markers to suppress warnings
```
```

Register pytest markers to suppress warnings

---

docs/running/cliOptions.rst
src/toil/batchSystems/abstractBatchSystem.py
src/toil/common.py
src/toil/jobStores/abstractJobStore.py
src/toil/leader.py
src/toil/test/utils/toilKillTest.py
src/toil/test/utils/utilsTest.py
src/toil/utils/toilKill.py
src/toil/utils/toilStatus.py

Closes #3917. We decided that it is not worth it to have every worker constantly poll the job store and self-terminate, since that could create too many requests to S3 or google storage (if using a cloud job store) and most of the time the leader is able to clean up all its jobs. 
* Make `toil kill` work when the leader is on another machine
```
```

Make `toil kill` work when the leader is on another machine

---

.gitlab-ci.yml
requirements-cwl.txt

This should fix #4106 by pinning what probably was a working networkx version.
* Toil now excludes the broken NetworkX 2.8.1 release, which breaks pickling and the Cactus integration tests
```
```

Update Cactus and exclude broken networkx

---

src/toil/lib/aws/utils.py
src/toil/server/utils.py
src/toil/server/wes/tasks.py
src/toil/test/server/serverTest.py

* Toil no longer stores state in S3 at keys with an extra leading `/`. (#4109)
* Added more tests for Toil's server mode and its integration with AGC components.
* Reduced the time to time out CANCELING WES workflows to CANCELED.
* Actually handle the case where the Toil workflow takes longer than our timeout to clean up after the Celery task is canceled. (#4111).
```
```

AGC integration fixes

---

requirements-google.txt

This should be new enough to share google-auth with the kubernetes module
without pip complaining about version conflicts.
This should fix #3889.
* Toil now accepts the newest 1.x `google-cloud-storage` module (#3889)
```
```

Allow newer google-cloud-storage

---

requirements-aws.txt
src/toil/lib/aws/utils.py

This will fix #4118 and pin the boto3 stubs so it won't happen again.
* Boto3 type stubs are exactly pinned to prevent unexpected changes in type-checking results
```
```

Remove MyPy overrides and exactly pin stubs

---

src/toil/common.py
src/toil/cwl/cwltoil.py
src/toil/jobStores/abstractJobStore.py
src/toil/test/cwl/cwlTest.py
src/toil/test/cwl/directory/directory/file.txt
src/toil/test/cwl/download_http.json
src/toil/test/cwl/download_https.json
src/toil/test/cwl/download_s3.json
src/toil/test/cwl/load_contents.cwl

* CWL tools using `loadContents` on input files can now be run directly against inputs in S3, without an enclosing workflow (#4125)
```
```

Implement and test CWL loadContents from URLs to fix #4125

---

docs/contributing/contributing.rst

* `contrib/hooks` scripts now have contributor documentation
```
```

Add documentation for the type-checking hooks

---

src/toil/jobStores/fileJobStore.py
src/toil/leader.py

* Toil now handles job deletes coming in late with FileJobStore, and warns instead of crashing (#4092).
```
```

Catch and warn about jobs going away too slowly on FileJobStore

---

contrib/admin/cleanup_aws_resources.py
contrib/pod-murder-bot/podKiller.sh
docs/appendices/environment_vars.rst
docs/running/cliOptions.rst
src/toil/batchSystems/kubernetes.py

* Toil will no longer wait indefinitely on pods that are stuck in `ContainerCreating` (#4145)
* Toil will tell Kubernetes to create `TOIL_KUBERNETES_HOST_PATH` for its pods if it does not exist already (#4145) 
```
```

Stop waiting on hostpath volumes to exist

---

src/toil/batchSystems/gridengine.py

I'm not entirely sure which qsubs will now start accepting our commands and which might stop, but this implements the suggested fix from #2511.
* Toil's `qsub` commands will now pre-split the commands we want `qsub` to run (#2511)
```
```

Pre-lex commands for qsub

---

src/toil/cwl/__init__.py

Closes: #4138 
* the installed version of `cwltool` is now cached; lack of `cwltool` is now only sent to the `DEBUG` stream, not on `WARNING`
```
```

cache results of cwltool version lookup

---

src/toil/server/wes/abstract_backend.py
src/toil/server/wes/tasks.py
src/toil/test/server/serverTest.py

This should fix #4037 by allowing WES requests to omit `workflow_params` from the POST data. If that happens, we will now treat it the same as if they had passed an empty JSON-serialized object.
* Toil WES server now accepts requests that leave out `workflow_params`.
```
```

Make `workflow_params` optional for WES workflow submissions

---

requirements-cwl.txt

This should hackily fix #4168 by restricting us to versions of schema-salad that seem to work. 
* `schema-salad` is restricted to version 8.2 or below which can validate CWL version strings properly and not as files (#4168)
```
```

Prohibit schema-salad 8.3 which thinks CWL versions need to be filenames

---

contrib/admin/cleanup_aws_resources.py
requirements-cwl.txt

* CWL: use newer schems-salad (8.3)
* 
```
```

re-support newer schema-salad 8.3

---

src/toil/lib/aws/ami.py

When we search the AWS marketplace, we only look for x86_64 AMI images.  This allows us to search for ARM as well.
Note:  I apparently had to separately subscribe to this service manually (we already subscribe to x86_64 flatcar AMI images; apparently ARM64 is a separate subscription): https://aws.amazon.com/marketplace/pp/prodview-zmao5idgwafbi
* Find ARM AMIs in AWS marketplace in addition to x86_64.
```
```

Fix ARM AMI fetch.

---

src/toil/lib/aws/iam.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/lib/aws/test_iam.py

Update aws permission check to handle "NotActions" included in policy documents.
```
```

Handle not actions, update tests to ensure this

---

.gitlab-ci.yml
contrib/toil-ci-prebake/Dockerfile

This should save us some time, and also avoid any network dust storms interfering with our vital PPAs.
* Use a CI prebake image for gitlab testing.
```
```

Prebake a Toil CI image.

---

requirements-cwl.txt

Fixes #4212 
* CWL: bump schema-salad dep to avoid cachecontrol issues
```
```

bump schema-salad dep to avoid cachecontrol issues

---

src/toil/job.py
src/toil/utils/toilStats.py

Fixes #4173. I am not sure if it is useful to include the `min`, `max`, `average`, and `median` of the requested cores, but I could include them as well. Or, it is also possible to display this information for individual jobs, but that may clutter the output.
* Include total requested cores for each job type in `toil stats`
```
```

Include total requested cores for each job type in `toil stats`

---

src/toil/provisioners/aws/awsProvisioner.py

This should fix #4278 (which we should put under CI at some point).
* `toil launch-cluster` should again work for cluster leaders that only get private IP addresses
```
```

Allow private-only IPs with a warning

---

docker/Dockerfile.py

Cactus uses `/usr/bin/time -v` to log peak memory usage, so allowing it within the toil appliances will help improve Cactus's logs when running on aws.  
Resolves  #4283
* `/usr/bin/time -v` now available from within Toil Docker Appliances
```
```

Add time to appliance

---

src/toil/batchSystems/kubernetes.py

Fix #3403. This ensures that the remaining kubernetes jobs will be deleted during shutdown if batch delete fails.
Tested with a running Toil workflow that is killed in the middle, and the kubernetes jobs are properly cleaned up even without batch delete permissions:
- Kubernetes batch system: Delete jobs individually when batch delete fails
```
```

Kubernetes batch system: Delete jobs individually when batch delete fails

---

src/toil/batchSystems/slurm.py

This PR attempts to solve 2 issues of the original PR https://github.com/DataBiosphere/toil/pull/4237 that attempts to solve https://github.com/DataBiosphere/toil/issues/3916 
1. The append of `['--export=ALL']` results in the incorrect `sbatch` call:
```bash
[2023-01-16T15:57:23+0000] [Thread-2  ] [D] [toil.batchSystems.abstractGridEngineBatchSystem] Running ['sbatch', '-J', 'toil_job_0_None', '--export=TOIL_RT_LOGGING_ADDRESS=10.36.16.24:54657,TOIL_RT_LOGGING_LEVEL=Debug,OMP_NUM_THREADS=1', '--mem=2048', '--cpus-per-task=1', '-o', '/tmp/toil_7db5fd48-eb51-4900-815b-488e5c4050b4.0.%j.out.log', '-e', '/tmp/toil_7db5fd48-eb51-4900-815b-488e5c4050b4.0.%j.err.log', '--time', '60', …
```

fix --export slurm configuration

---

src/toil/batchSystems/htcondor.py

Have HTCondor use prepareSubmission as opposed to prepareHTSubmission
```
```

Replace prepareHTSubmission with prepareSubmission in HTCondor

---

src/toil/cwl/cwltoil.py

When using `InplaceUpdateRequirement` in the `hints` section, `toil-cwl-runner` now warns that the Toil file store does not support this, and that the option `--bypass-file-store` should be provided on the command line.
```
```

Warn about missing --bypass-file-store with in-place update

---

src/toil/lib/aws/iam.py

Remove json.loads from policy check
```
```

Ignore incorrect type hint from boto3, remove json.loads

---

src/toil/common.py

This should fix #4326 by not forgetting to create the `nodeExporterProc` attribute.
* `--provisioner` and `--metrics` should now work together again without a crash at shutdown (#4326)
```
```

Fix --provisioner and --metrics together

---

requirements-cwl.txt
src/toil/job.py

This should fix #4340 and hopefully get CI working again.
* Pin schema_salad to a version that doesn't crash the unpickling process when a `RecordSchema` is encountered.
```
```

Pin schema salad

---

src/toil/provisioners/aws/awsProvisioner.py

This should fix #4280.
* `toil destroy-cluster` should no longer fail if an AWS AutoScaling Group vanishes before it can be deleted
```
```

Tolerate ASGs already being deleted and use more error accessors

---

requirements-cwl.txt

* Resume using latest Schema Salad releases
```
```

a fixed version of schema salad was released (8.4.20230128170514)

---

.gitlab-ci.yml
Makefile
requirements-dev.txt
src/toil/test/docs/scripts/tutorial_cwlexample.py
src/toil/test/docs/scripts/tutorial_docker.py
src/toil/test/docs/scripts/tutorial_dynamic.py
src/toil/test/docs/scripts/tutorial_encapsulation.py
src/toil/test/docs/scripts/tutorial_encapsulation2.py
src/toil/test/docs/scripts/tutorial_invokeworkflow.py
src/toil/test/docs/scripts/tutorial_invokeworkflow2.py
src/toil/test/docs/scripts/tutorial_jobfunctions.py
src/toil/test/docs/scripts/tutorial_managing.py
src/toil/test/docs/scripts/tutorial_managing2.py
src/toil/test/docs/scripts/tutorial_promises.py
src/toil/test/docs/scripts/tutorial_promises2.py
src/toil/test/docs/scripts/tutorial_quickstart.py
src/toil/test/docs/scripts/tutorial_requirements.py
src/toil/test/docs/scripts/tutorial_services.py
src/toil/test/docs/scripts/tutorial_staging.py
src/toil/test/docs/scripts/tutorial_wdlexample.py
src/toil/test/docs/scriptsTest.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/src/jobTest.py
src/toil/test/utils/ABCWorkflowDebug/debugWorkflow.py
src/toil/test/utils/toilDebugTest.py
src/toil/test/utils/utilsTest.py
src/toil/test/wdl/toilwdlTest.py
src/toil/wdl/wdl_synthesis.py

* The offline tests can now be run in parallel
```
```

Parallel testing

---

src/toil/lib/aws/__init__.py

* AWS: better handle errors getting EC2 identity.
```
```

AWS: better handle errors getting EC2 identity.

---

src/toil/lib/threading.py

For example, FileNotFoundError
May help #4373 
* cope with missing lock file, due to inconsistent filesystem
```
```

cope with missing lock file, due to inconsistent filesystem

---

docs/developingWorkflows/developing.rst
src/toil/cwl/cwltoil.py
src/toil/exceptions.py
src/toil/job.py
src/toil/leader.py
src/toil/test/cwl/cwlTest.py
src/toil/test/lib/dockerTest.py
src/toil/test/sort/sortTest.py
src/toil/test/src/autoDeploymentTest.py
src/toil/test/src/checkpointTest.py
src/toil/test/src/deferredFunctionTest.py
src/toil/test/src/fileStoreTest.py
src/toil/test/src/importExportFileTest.py
src/toil/test/src/jobServiceTest.py
src/toil/test/src/jobTest.py
src/toil/test/src/restartDAGTest.py
src/toil/test/src/resumabilityTest.py
src/toil/test/src/retainTempDirTest.py

* Pull out FailedJobsException to break the import loop. This also fixes a false error in cwltoil in some circumstances
```
```

Pull out FailedJobsException to break the import loop

---

src/toil/batchSystems/abstractBatchSystem.py
src/toil/batchSystems/kubernetes.py
src/toil/batchSystems/singleMachine.py

Fixes #2864 by introducing a jobs queue system to restrict the maximum resources given to kubernetes at once. Proposed changes to the Kubernetes batch system:
- Maintain a queue of jobs in Toil to prevent swamping the cluster when resources are over a set limit (`--maxCores`, `--maxMemory`, and `--maxDisk`)
- All jobs would go through the queue to be submitted to the kubernetes cluster
- Use a separate scheduler thread to process the jobs queue
- This thread wakes up when a new job is put into the queue or when any resource is freed
- When it wakes up, it loops over the entire queue and tries to launch as many jobs as possible
- When any resource is not available for the job, it is put back into the queue …

Kubernetes batch system: support `--maxCores`, `--maxDisk`, and `--maxMemory`

---

index.html

Before: ![image](https://user-images.githubusercontent.com/1330696/220390981-2ddd7993-3f7b-4572-bd2e-188c5dec79bd.png) After: ![image](https://user-images.githubusercontent.com/1330696/220391023-a62d1c48-1850-45dc-baa4-ca74735d8160.png)

website: Update statement about CWL support.

---

requirements-wdl.txt
setup.cfg
setup.py
src/toil/batchSystems/singleMachine.py
src/toil/common.py
src/toil/job.py
src/toil/lib/accelerators.py
src/toil/test/__init__.py
src/toil/test/utils/utilsTest.py
src/toil/test/wdl/md5sum/md5sum.1.0.wdl
src/toil/test/wdl/toilwdlTest.py
src/toil/test/wdl/wdltoil_test.py
src/toil/wdl/wdltoil.py

This improves the MiniWDL-based WDL implementation so that you can successfully run:
```
python -m toil.wdl.wdltoil --logDebug --clean=always --cleanWorkDir=always --scale=0.1 --retryCount=0 https://raw.githubusercontent.com/vgteam/vg_wdl/44a03d9664db3f6d041a2f4a69bbc4f65c79533f/workflows/giraffe.wdl https://raw.githubusercontent.com/vgteam/vg_wdl/44a03d9664db3f6d041a2f4a69bbc4f65c79533f/params/giraffe.json
```
We still ignore the retry count, and we still don't keep sibling files next to each other as in the spec, but we implement requirements.
There's an implementation of GPU requirements for WDL in here right now, but it hasn't been tested yet.
Eventually this will fix  #4353 but I want to make sure the GPU-based workflows actually work on a GPU machine. …

Enable running Giraffe WDL

---

src/toil/lib/accelerators.py

Cactus cannot be run on a system where `nvidia-smi` exists, but the user does not have permission to run it.  Even if they do not want to use the GPUs at all.  This situation is not hypothetical: https://github.com/ComparativeGenomicsToolkit/cactus/issues/937
The reason is that `count_nvidia_gpus()`, which seems to get run whether or not the user wants GPUs, doesn't handle permission exceptions.  This PR changes that. 
* `count_nvidia_gpus()` will return 0 instead of raising an exception if client can't call `nvidia-smi` for permissions reason. This will allow Cactus users to run (without GPUs) on such environments.  
```
contrib/admin/test-pr otheruser theirbranchname …
```

Handle user not having permission to run nvidia-smi

---

src/toil/__init__.py
src/toil/cwl/cwltoil.py

Add --custom-net cwltool option to cwltoil.py to enable user to add ability to connect container to an input docker network via cwltool. See https://manpages.ubuntu.com/manpages/bionic/man1/cwltool.1.html.
- Support for docker container communication via connecting containers to a docker network
```
```

Allow connecting docker containers to docker networks

---

src/toil/__init__.py

It seems that sometime since #588,`import subprocess` was accidentally removed. This PR restores `import subprocess` at the call site (rather than at the top-level) so this becomes less likely in the future.
* Added `import subprocess` to restore the behavior of #588.
```
```

added import subprocess

---

src/toil/jobStores/aws/jobStore.py
src/toil/lib/aws/utils.py

This will fix #4442 by making Toil's buckets capable of having public objects in them again.
* Fix Toil bucket setup to re-enable public objects in Toil's buckets to compensate for Amazon's change to the default settings (#4442)
```
```

Re-enable public objects

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml

* Move to a supported version of the CodeQL GitHub Action
* 
```
```

GitHub Actions: update codeql version

---

src/toil/common.py
src/toil/lib/aws/session.py
src/toil/test/src/busTest.py
src/toil/utils/toilStatus.py

This will fix #4438 and thus https://github.com/ComparativeGenomicsToolkit/cactus/issues/987 by just making a new message bus path every time Toil starts, if the user didn't specify one manually.
* Toil will no longer use the stored message bus path from an old execution of a workflow when deciding where to save the message bus log when restarting a workflow (#4438)
```
```

Avoid re-using old message bus path when restarting a workflow

---

docs/running/cliOptions.rst
src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/htcondor.py
src/toil/batchSystems/kubernetes.py
src/toil/batchSystems/local_support.py
src/toil/batchSystems/options.py
src/toil/batchSystems/singleMachine.py
src/toil/common.py

* Users should no longer need to set `--maxLocalJobs` to increase jobs submitted to gird engine schedulers beyond host core count
* New `--maxJobs` option allows limiting max non-local jobs on batch systems that use a Toil-side queue.
```
```

Make --maxJobs control max jobs instead of --maxLocalJobs

---

src/toil/leader.py
src/toil/utils/toilClean.py
src/toil/wdl/wdltoil.py

With this I managed to clean up my lingering `toil-cwl-6a8536e5-1cfb-433d-abef-9f03cb51d8bb--files` bucket and several similar ones.
This is still on top of #4460 because that includes CI fixes. 
* `toil clean` can now delete a job store even if it can't properly resume it.
```
```

Clean unresumable job stores

---

docs/running/cliOptions.rst
src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/options.py
src/toil/batchSystems/slurm.py
src/toil/fileStores/nonCachingFileStore.py
src/toil/lib/misc.py

This is an attempt to fix #4431. It is still sending the list of all active jobs to Slurm (so it might e.g. hit a command line limit), but I don't think it will call N commands to poll N jobs anymore.
I will need a test workflow to see if this is good enough.
* `--coalesceStatusCalls` is now permanently on where implemented
* Default Slurm `--statePollingWait` reduced to 0. **On a busy Slurm cluster you may need to increase this to avoid degrading service for others!**
* NonCachingFileStore no longer retries a lot looking for deleted job state files
```
```

Speed up Slurm job turnaround when there are many jobs

---

src/toil/batchSystems/kubernetes.py
src/toil/jobStores/fileJobStore.py

This fixes #4484 because we forgot to pass the job ID that was missing to the exception we use to signal that it isn't there.
* Toil should no longer crash when a delete wins a race against a load in `FileJobStore`
```
```

Pass job ID to NoSuchJobException as required

---

src/toil/jobStores/abstractJobStore.py
src/toil/wdl/wdltoil.py

This will fix #4479.
* Toil will now stop if it encounters an error polling a possible import URL for a WDL workflow input file.
* Attempts to import files from URLs when the implementing job store is missing an extra are now better reported.
```
```

Improve reporting for why WDL file imports fail

---

src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/job.py

* Slurm and other grid batch system jobs will now have more informative names
```
```

Make sure to name Slurm jobs with something even if unitName isn't set

---

src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/test/wdl/md5sum/empty_file.json
src/toil/test/wdl/wdltoil_test.py
src/toil/wdl/wdltoil.py

This should fix #4477.
* WDL workflows can no longer import `""` as a File.
* WDL workflows will be protected against imported files with no basenames.
```
```

Prevent empty path `File` imports in WDL

---

src/toil/common.py
src/toil/cwl/cwltoil.py
src/toil/fileStores/abstractFileStore.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/jobStores/googleJobStore.py
src/toil/test/jobStores/jobStoreTest.py

Also added unit test for testing --linkImports
```
```

Fix cwl runner not grabbing --linkImports from config

---

src/toil/server/wsgi_app.py

This fixes #4275. The order of applying settings was reversed where Gunicorn's defaults were being applied last.
* CLI server options no longer get overwritten by Gunicorn's default arguments
```
```

Stop CLI options from being overriden by Gunicorn's defaults

---

requirements-aws.txt
src/toil/lib/aws/iam.py
src/toil/lib/aws/session.py

This fixes #4532 
* Fix CI lint test
```
```

Fix CI lint test

---

src/toil/fileStores/abstractFileStore.py
src/toil/test/wdl/wdltoil_test.py

* Giraffe WDL CI test can now run in the memory we actually have
```
```

Use less memory in the Giraffe WDL test

---

src/toil/lib/accelerators.py

* Fix test failures in environments without docker installed.
```
```

Fix test failures without docker installed

---

docs/running/cloud/amazon.rst
src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py
src/toil/test/cwl/preemptible.cwl
src/toil/test/cwl/preemptible_expression.cwl
src/toil/test/cwl/preemptible_expression.json
src/toil/test/lib/test_ec2.py

This will fix #4258 by allowing you to specify preemptibility per-task in CWL, like you can in WDL.
Unfortunately [the Arvados schema we are trying to support](https://github.com/arvados/arvados/blob/48a0d575e6de34bcda91c489e4aa98df291a8cca/sdk/cwl/arvados_cwl/arv-cwl-schema-v1.1.yml#L345) only allows literal `boolean` values, and not parameter references/expressions, and I couldn't figure out how to get `cwltool` to evaluate the expressions in hints, so I'm not supporting expressions for preemptibility (yet?).
I've added some tests for parsing/validation, but I couldn't figure out how to add a good unit test for the preemptibility flag *actually* making it to the Toil backend and having an effect, since it doesn't matter single-machine and I don't want to spin up a cluster on CI to test …

Support per-task preemptibility in CWL

---

docs/gettingStarted/quickStart.rst
docs/running/hpcEnvironments.rst
docs/running/wdl.rst

This will fix #4496.
I'm adding the Slurm documentation asked for by the issue, as well as more pointers to WDL tutorials like my WDL/Slurm one on the GI wiki.
* Toil documentation now includes more material about WDL and Slurm (#4496)
```
```

More WDL and Slurm documentation

---

src/toil/fileStores/cachingFileStore.py
src/toil/job.py
src/toil/jobStores/fileJobStore.py
src/toil/toilState.py

This will fix #4562. I've switched to a completely different way of doing deep copies, and added some error checks to make sure that job versions ratchet forward and we never let an old job version replace a new one.
* Toil should no longer see old versions of jobs return from the dead
```
```

Banish ghost jobs

---

.gitlab-ci.yml
Makefile
contrib/admin/mypy-with-ignore.py
src/toil/fileStores/cachingFileStore.py
src/toil/lib/aws/ami.py
src/toil/test/batchSystems/batchSystemTest.py
src/toil/test/cwl/cwlTest.py
src/toil/test/src/fileStoreTest.py

This has fixes for CI on non-Kubernetes Gitlab runners. It should fix #4522 (except that it doesn't remove CI tests that need to run *Toil workflows* on the Kubernetes cluster).
* CI now runs on local Gitlab runners, instead of runners in Kubernetes in AWS
```
```

Fix CI on local Gitlab runners

---

src/toil/lib/aws/iam.py

#4576 
* Fix mypy from new boto types
```
```

Fix mypy from being broken by new boto types

---

src/toil/cwl/__init__.py
src/toil/cwl/cwltoil.py
src/toil/worker.py

This will fix #4526.
* Single machine Toil runs will no longer spam the console with logging redirect or CWL version mismatch messages (#4526)
```
```

Lower redirect log level to fix #4526

---

requirements.txt

I have version 4.6.2 in my virtualenv and it works, so we should be fine with at least that version.
This fixes #4585.
* Toil now knows it cannot work on old versions of `typing-extensions`
```
```

Add version bound for typing-extensions

---

docker/Dockerfile.py
docs/running/wdl.rst
src/toil/jobStores/fileJobStore.py
src/toil/wdl/wdltoil.py

This fixes #4546.
* `toil-wdl-runner` can now output to supported Toil export locations, such as S3 URIs (#4546)
```
```

Run WDL output through Toil export system to support URIs

---

.gitlab-ci.yml
src/toil/wdl/wdltoil.py

This will resolve #4583 
* Enable WDL decls in the output section to reference itself
```
```

Allow the WDL output section to reference itself

---

src/toil/fileStores/nonCachingFileStore.py
src/toil/lib/threading.py

To summarize without the additions to catch errors when files are inaccessible or missing on a network file system, toil will throw this stack trace below.
```
File "/home/walkerbd/toil/src/toil/worker.py", line 390, in workerScript
with fileStore.open(job):
File "/home/walkerbd/mambaforge-pypy3/envs/dali/lib/python3.9/contextlib.py", line 119, in __enter__
return next(self.gen)
File "/home/walkerbd/toil/src/toil/fileStores/nonCachingFileStore.py", line 105, in open
self._removeDeadJobs(self.coordination_dir)
File "/home/walkerbd/toil/src/toil/fileStores/nonCachingFileStore.py", line 243, in _removeDeadJobs
for jobState in cls._getAllJobStates(coordination_dir):
File "/home/walkerbd/toil/src/toil/fileStores/nonCachingFileStore.py", line 300, in …
```

Fix pickling error on network file system

---

src/toil/__init__.py
src/toil/bus.py
src/toil/common.py
src/toil/cwl/cwltoil.py
src/toil/cwl/utils.py
src/toil/job.py
src/toil/leader.py
src/toil/lib/conversions.py
src/toil/lib/docker.py
src/toil/lib/ec2.py
src/toil/lib/ec2nodes.py
src/toil/lib/encryption/_nacl.py
src/toil/lib/threading.py
src/toil/realtimeLogger.py
src/toil/resource.py
src/toil/serviceManager.py
src/toil/test/wdl/builtinTest.py
src/toil/toilState.py
src/toil/wdl/wdl_functions.py
src/toil/wdl/wdltoil.py
src/toil/worker.py

This will resolve #3716.
* Reduce the amount of assert statements
```
```

Reduce the number of assert statements

---

src/toil/test/docs/scripts/tutorial_arguments.py
src/toil/test/docs/scripts/tutorial_invokeworkflow.py
src/toil/test/docs/scripts/tutorial_invokeworkflow2.py
src/toil/test/docs/scripts/tutorial_multiplejobs.py
src/toil/test/docs/scripts/tutorial_multiplejobs2.py
src/toil/test/docs/scripts/tutorial_multiplejobs3.py
src/toil/test/docs/scripts/tutorial_quickstart.py
src/toil/test/docs/scripts/tutorial_requirements.py
src/toil/test/docs/scripts/tutorial_staging.py
src/toil/test/src/helloWorldTest.py
src/toil/test/src/realtimeLoggerTest.py
src/toil/test/src/toilContextManagerTest.py
src/toil/test/src/userDefinedJobArgTypeTest.py

* Tests: only request a single core
```
```

Tests: only request a single core

---

.gitlab-ci.yml
contrib/admin/cleanup_aws_resources.py

This will solve the old buckets issue from #4584
* Update AWS cleanup script to catch old naming schemes
```
```

Remove old buckets from AWS

---

src/toil/test/provisioners/clusterScalerTest.py

This will fix #4599 by making the mock leader thread safe.
* Scaler test mock leader is more thread safe
```
```

Avoid concurrent modification in cluster scaler tests

---

.gitlab-ci.yml
src/toil/wdl/wdltoil.py

This will resolve #4554.
This uses monkey patching as MiniWDL just stores the filepath for these types of conversions. If there is a new extension point in MiniWDL, this should probably be replaced with a newer implementation. It also looks like workflow nodes by default already [run on the leader node](https://github.com/DataBiosphere/toil/blob/10a25897064b2637701ce43060b5ce6928f02c14/src/toil/wdl/wdltoil.py#L957-L959), so I didn't explicitly add those arguments for workflow nodes.
* Support string to file conversion in toil-wdl-runner
```
```

Add String to File functionality into toil-wdl-runner

---

src/toil/lib/accelerators.py

Toil runs `nvidia-smi` to count the available GPUs, and if the command fails, it catches it and returns 0.  This is fine, but only when it fails with an exception that Toil expects.  This came up once before in https://github.com/ComparativeGenomicsToolkit/cactus/issues/937 where an unhandled permission error wasn't caught, which completely blocked the user from running Cactus. This got fixed in #4391 by adding a check for `PermissionError`.  
But now somebody's run into what looks like the exact same issue again: https://github.com/ComparativeGenomicsToolkit/cactus/issues/1185.  This time it looks like they're getting a `NotADirectoryError` when running `nvidia-smi`.  They don't want to use GPUs but the failing exception completely breaks Cactus...
Anyway, this PR just makes the check …

take any nvidia-smi exception as not having gpu

---

contrib/slurm-test/slurm_test.sh
src/toil/batchSystems/abstractBatchSystem.py

This ought to fix #4633
* Nonexistent `--batchLogsDir` will be created and should no longer break Slurm
```
```

Make sure the `--batchLogsDir` exists if it is set

---

requirements-cwl.txt

Fixes: https://github.com/DataBiosphere/toil/issues/4638
* Upgrade `cwltool` to 3.1.20231020113452 . This forces a downgrade of `galaxy-tool-util` to fix #4638 
```
```

Upgrade cwltool to avoid broken galaxy-tool-util release.

---

src/toil/test/cwl/cwlTest.py

* CWL conformance testing: use the latest commit from the proposed CWL v1.2.1 branch
Related to https://github.com/DataBiosphere/toil/issues/4564
```
```

cwl: use the latest commit from the proposed CWL v1.2.1 branch

---

.gitlab-ci.yml
requirements-aws.txt
requirements-dev.txt
requirements-mesos.txt
requirements.txt
setup.py

This should also fix #4648 and allow #4649 to pass
This resolves #4651 
* Fix CI appliances to build properly
* Also only install htcondor on CI in appliance builds
* Installing with extras=[all] on Python 3.12+ will not install mesos
* Moved AWS stub and mock packages to requirements-dev.txt
```
```

Fix CI Appliance Builds

---

requirements-aws.txt
requirements-dev.txt
requirements.txt

This resolves #4663 
Moving the AWS libraries back into requirements-aws.txt instead of requirements-dev.txt seems to make it work again locally.
* Fix slow 3.8/3.9 builds
* Loosened docker constraints and moved AWS libraries
```
```

Fix slow 3.8/3.9 appliance builds

---

.gitlab-ci.yml

This should fix #4648 by turning on the batch system tests again. The Mesos-specific ones are already moved elsewhere.
* Batch system tests now run again
```
```

Turn batch system tests back on

---

src/toil/test/jobStores/jobStoreTest.py

* Test logic for AWS jobStoreTest: re-use `delete_s3_bucket` from `toil.lib.aws` which has better error handling code.
```
```

AWS jobStoreTest: re-use delete_s3_bucket from toil.lib.aws

---

src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py
src/toil/test/cwl/glob_dir.cwl

This fixes #4698, and adds a test for it.
* `toil-cwl-runner` should no longer fail to output files with `--bypass-file-store` and without `--outdir`
```
```

Make sure cwltool always knows we have an outdir to fix #4698

---

setup.py
src/toil/cwl/__init__.py
src/toil/utils/toilMain.py
version_template.py

* Migrate from the deprecated pkg_resource to Python 3.8's [`importlib.metadata.version()`](https://docs.python.org/3/library/importlib.metadata.html#distribution-versions)
```
```

remove useage of the deprecated pkg_resources

---

src/toil/wdl/wdltoil.py

This will fix #4695 by calling MiniWDL's whitespace-removal function.
* WDL shell commands now have leading whitespace removed as in MiniWDL, fixing `<<` heredocs.
```
```

Strip leading whitespace from WDL commands

---

src/toil/options/cwl.py

This fixes #4724 by making mutually exclusive groups not exist when they are supposed to be suppressed in options/cwl.py
* Fix --help output in toil-wdl-runner by avoiding an argparse bug with mutually exclusive groups
```
```

Make cwl mutually exclusive groups exist only when cwl is not suppressed

---

Makefile
common.mk
setup.cfg
src/toil/lib/aws/ami.py
src/toil/test/__init__.py
src/toil/test/cwl/cwlTest.py
src/toil/test/lib/test_ec2.py

This will fix #4726.
* CI tests should no longer fail if we cannot authenticate to AWS when trying to pick a Flatcar AMI
```
```

Tolerate a failed AMI polling attempt

---

Makefile
requirements-dev.txt

'mock' has been integrated in the standard library as 'unittest.mock'
```
```

remove extraneous dependency on old 'mock'

---

.gitlab-ci.yml

This should fix #4756 and hopefully the intermittent test failures where buildkit tries to speak HTTPS to our Docker cache.
* CI should no longer speak HTTPS to HTTP Docker cache
```
```

Stop marking HTTP registry as insecure

---

Makefile
requirements-cwl.txt
requirements-server.txt
src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py
src/toil/test/provisioners/clusterTest.py

Fixes https://stackoverflow.com/questions/77684785/toil-cwl-runner-not-using-default-container-option-with-singularity-option
Needs a test to prevent future regressions
* CWL: don't clear out user-provided values for the --default-container option
```
```

CWL: don't clear out user-provided values for the --default-container

---

requirements.txt
src/toil/common.py

This way, conda/debian etc.. don't need to package the `ruamel.yaml.string` module; and this solution is simpler and possibly a bit faster.
* Deps: removed the ruaml.yaml.string plugin dependency for a simpler solution
```
```

remove ruamel.yaml.string dependency for a simpler solution

---

.github/workflows/autoupdate.yaml

This uses https://github.com/marketplace/actions/auto-update so I don't have to go around poking all the PRs all the time to keep them up to date. Instead I should more or less always find a PR I can hit merge on, if any are working properly.
This might make a lot of CI runs happen automatically if a PR merges and a lot of other ones are outstanding. But right now I end up making all those runs happen manually, *and* I have to wait around for them.
* PRs to Toil now stay up to date wit the target branch automatically if possible.
```
```

Add workflow to automatically update PRs when other PRs merge

---

docs/appendices/deploy.rst
docs/contributing/contributing.rst
docs/gettingStarted/install.rst
docs/gettingStarted/quickStart.rst
docs/running/cliOptions.rst
docs/running/cloud/amazon.rst
docs/running/cloud/clusterUtils.rst
docs/running/cloud/gce.rst
docs/running/hpcEnvironments.rst

Patch is from Debian, where we update the docs to remove the virtualenv for most examples.
* Docs: Always show Python execution using `python3`, in case a virtualenv is not used
```
```

Docs: Always show Python execution using `python3`

---

Makefile

This replaces #4348 with just the change to the formatter.
We still need to run `make format && make sort_imports` and commit the result without upsetting all the outstanding PRs and making them basically unmergeable. Maybe we need to black and isort the main branch *and* black and isort all the PRs and then Git will be able to make sense of the diffs?
* `make format` now formats the whole Toil codebase
```
```

Make formatting do all the code

---

src/toil/jobStores/aws/utils.py
src/toil/test/jobStores/jobStoreTest.py
src/toil/test/lib/test_ec2.py

This is from the Debian package of Toil
* Improved ability to easily discover & run tests without boto or boto3 installed.
```
```

avoid unnecessary boto{,3} imports

---

src/toil/lib/conversions.py
src/toil/options/common.py
src/toil/utils/toilDebugFile.py

In Python 3.10 and 3.11, distutils has been formally marked as deprecated.
Code that imports distutils will no longer work from Python 3.12.
Copied code is MIT licensed
https://github.com/pypa/distutils/blob/fb5c5704962cd3f40c69955437da9a88f4b28567/distutils/util.py#L340 https://github.com/pypa/distutils/blob/fb5c5704962cd3f40c69955437da9a88f4b28567/LICENSE
* Add more Python3.12 compatibility by replacing the one function from distutils that we use, `strtobool()`.
```
```

remove use of distutils by copying in strtobool()

---

src/toil/options/common.py
src/toil/test/utils/toilDebugTest.py

This replaces #4758.
* `--disableProgress` is once again a flag that doesn't take an argument
```
```

Revert --disableProgress to old flag-style behavior

---

docs/running/cliOptions.rst
src/toil/options/common.py

This will fix #4785 and should let you log quite a few files you couldn't mount.
* Use a default log limit of 100MiB
```
```

Use a default log limit of 100MiB

---

requirements.txt

* Toil now requires the `docker` module 6.1 or later.
```
```

Require new Docker

---

src/toil/cwl/cwltoil.py

This should fix #4791. We weren't logging the CWL command output to stats and logging before we threw an error due to the CWL task failing. Now it should always make it to stats and logging, and should also appear inline again for failing commands, like for WDL.
* CWL jobs again report standard output and standard error when they fail
```
```

Log CWL command output inline on failure, and to logging system whether it succeeds or not

---

src/toil/wdl/wdltoil.py

This fixes a silent data loss/corruption bug in WDL workflows where, if multiple outputs had the same base filename, only one would actually be saved, and all of the output JSON fields would just point to that one.
@juklucas is supposed to open the actual issue, but when he does this should fix it.
* WDL workflows can now safely output multiple files with the same name without collisions.
```
```

Unify devirtualization to fix output name collisions

---

docs/wdl/running.rst
src/toil/options/wdl.py
src/toil/wdl/wdltoil.py

* WDL workflows can be run on `docker` or `singularity` specifically with `--container`.
```
```

Allow setting WDL container engine with --container

---

src/toil/batchSystems/slurm.py
src/toil/worker.py

This should fix #4801. I've tested this manually and it does indeed result in MiniWDL getting a chance to kill its containers, so it should help with #4800. It also is an independent fix for #4706, as long as the worker actually does manage to shut down gracefully between the signal and the actual timeout. 
* Toil now stops jobs gracefully 30 seconds before Slurm timeout with a `SIGINT`/`KeyboardInterrupt`.
* Toil now attempts to commit the job log back even if the job is exiting with a `BaseException`.
```
```

Request and handle Slurm timeout signal

---

src/toil/test/docs/scriptsTest.py
src/toil/test/src/workerTest.py
src/toil/worker.py

This fixes #4782 by checking the local flag on jobs when determining how to chain them.
* Jobs not marked with `local=True` can no longer accidentally run on the leader via chaining
```
```

Respect job local-ness when chaining

---

.gitlab-ci.yml
docker/Dockerfile.py
src/toil/utils/toilStats.py

This should fix support for Python 3.8, and also bring all the Python versions under test for the main branch, tags, and scheduled tests. It also stops the Docker build from succeeding if Toil fundamentally can't run at the command line.
When this is in we probably need to make a 6.1.1 patch release that actually supports all the Python versions it claims to, and we should change our release process to make sure that the new tests pass before publishing.
* Toil now runs on Python 3.8 again
```
```

Fix Python 3.8 support

---

Makefile
setup.py

- setuptools: Include README in the package metadata.
Currently https://pypi.org/project/toil/#description is
> The author of this package has not provided a project description
- Makefile: use isolated builds, add dist target (sdist+wheel) and deprecate the sdist target.
* Metadata: include the README.rst as part of the published package
```
```

Fix missing description on PyPI

---

.gitlab-ci.yml

#4825 
* Fix missing module in CI
```
```

Install build module for CI

---

src/toil/cwl/cwltoil.py

This fixes #4812 by changing how we internally represent that a file was missing when we went to look for it.
* Toil should now be able to properly find and materialize secondary files for input files referenced by URL when `--reference-inputs` is set.
```
```

Use a sentinel location instead of an unmodified location to mark missing files

---

src/toil/batchSystems/singleMachine.py

This resolves #2739 
This now properly carries through the status code of the debugged job. This will mean that a failing job in debug mode will retry according to `--retryCount`. Maybe it is better if it does not retry at all?
* Fix `--debugWorker` from causing an infinite loop when running a failing job
```
```

Pass through debugged job status code to prevent infinite loop

---

requirements-dev.txt
src/toil/test/src/environmentTest.py

This adds testing that I think should close #4835. The worker-based environment system is now tested, running on a single machine but in a way that should apply to all batch systems that actually run the worker.
* Toil CI now tests that `environment.pickle` and not magic batch system osmosis carries leader environment to worker
```
```

Add tests for environment pickling

---

.gitlab-ci.yml

Resolves #4841
The existing batchsystems tests only installs Toil, so this PR removes it as it isn't doing much, other than spending around 5 minutes.
There are AWS, Kubernetes, and Single machine tests in `batchSystemTest.py` that may be useful. Maybe there should be a new test in `.gitlab-ci.yml` to run them with `$CI_PIPELINE_SOURCE == "schedule"`?
```
```

Remove unused CI test

---

.gitlab-ci.yml
Makefile
requirements-dev.txt
src/toil/test/utils/utilsTest.py

Adds Python 3.12 to CI
* Add support for Python 3.12
```
```

Update to Python 3.12

---

src/toil/common.py

Closes #4877.
This will try the /tmp directory before the work directory in case the work directory is actually shared, as /tmp should be local to the node. I'm not sure of a proper way to test if a directory/filesystem is shared or not, the closest that I could find is using a nonconsistent linux command: https://unix.stackexchange.com/questions/72223/check-if-folder-is-a-mounted-remote-filesystem
* Try the /tmp/toil_coordination before the Toil workdir
```
```

Try /tmp before the workdir for the Toil coordination directory

---

src/toil/test/cwl/cwlTest.py
src/toil/test/cwl/seqtk_seq.cwl

* CWL biocontainer tests: use version corresponding to v2 Docker Image Format
```
```

CWL biocontainer tests: use version corresponding to v2 Docker Image Format

---

docs/gettingStarted/install.rst

* Add documentation for installing batchsystem plugins
```
```

Add documentation for installing batch system plugins

---

requirements-server.txt

It looks like if you give away your debugger PIN, people can use your Werkzeug debugger. This is somehow a security issue and was apparently never fixed on Werkzeug 2.
* Toil server mode now needs/allows newer Werkzeug
```
```

Update Werkzeug to appease the Github security police

---

requirements-server.txt

Reverts DataBiosphere/toil#4925

Revert "Update Werkzeug to appease the Github security police"

---

.gitlab-ci.yml
src/toil/test/batchSystems/batch_system_plugin_test.py

Closes #4879 
* Add a test to ensure batchsystem plugins are installable
```
```

Add batchsystem plugin test

---

.gitlab-ci.yml

Addresses #4935 .
* Fix bad test paths that had been moved and broken.
```
```

Fix bad test paths.

---

src/toil/utils/toilLaunchCluster.py

Resolves #4952 
* Fix Toil utils to work without the AWS extra
```
```

Allow Toil utils to work without the AWS extra

---

src/toil/utils/toilMain.py

It got annoying trying to figure out whether my installed Toil on the cluster was up to date with my commits, so this makes development builds print the hash.
* `--version` with development builds will now also output the commit hash
* Ex, before: `7.1.0a1`, After: `7.1.0a1-ccf57e6071e32675daabdcbacb91988e871745a9`
```
```

Print hash with --version when installed as development

---

.gitlab-ci.yml

#4961 
I'm not sure how they disappeared, but I chose the closest currently available version relative to the previous pinned versions.
We also don't really have htcondor tests set up, so it may be better to remove them entirely and move the code into it's own batchsystem plugin, similar to TES. That way, we could be able to run CI.
* Changed pinned versions of htcondor on CI
```
```

Change pinned htcondor versions to fix CI

---

docs/running/utils.rst
src/toil/bus.py
src/toil/common.py
src/toil/leader.py
src/toil/utils/toilStatus.py

Closes #4415
* Fixed a bug where the message bus path gets lost
* Added `toil status --printStatus` to the documentation
* Changed output format for `--printStatus` to be more readable
```
```

Add `--printStatus` to documentation + Fix message bus path getting lost

---

docs/Makefile
docs/conf.py
requirements-dev.txt

This will fix #4940 and revert part of 6a1bbbde9266402c496780657eb854671f33b852
I'm not seeing it actually hit any docs build warnings on my machine, so I want to see what CI thinks of it.
* Docs build warnings (like missing link targets) treated as errors again
```
```

Re-enable failing on warnings in the docs build

---

requirements-dev.txt
requirements.txt

This will fix #4969 by moving the dependency.
We also might want to cut the toil.lib.bioio to toil.test internal dependency.
* Toil now has correct dependencies for importing from `toil.lib.bioio` on Python 3.8.
```
```

Make backports.zoneinfo a normal dependency

---

src/toil/lib/aws/__init__.py
src/toil/lib/aws/utils.py
src/toil/server/wes/tasks.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/server/serverTest.py

These should resolve #4974 and lead `master` back to The Path.
Fixes a broken URL and adds an omitted variable (`enable_fuse`) into a couple of tests.
* Fixes a broken URL and an omitted variable.
```
```

Integration test fixes.

---

src/toil/lib/threading.py

This might help with #4972 by only being willing to see an EIO from Ceph so many times before giving up. We don't know much about these errors and it's plausible they are at least sometimes permanent.
* Toil file locking now has a limited patience for IO errors.
```
```

Handle permanent EIOs in file locking by eventually stopping

---

src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/aws/utils.py
src/toil/lib/aws/__init__.py
src/toil/lib/aws/iam.py
src/toil/lib/aws/session.py
src/toil/lib/aws/utils.py
src/toil/lib/ec2.py
src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/lib/aws/test_s3.py
src/toil/test/provisioners/aws/awsProvisionerTest.py
src/toil/test/server/serverTest.py

* Allow for not installing the `mypy_boto3_*` packages, they aren't packaged for Debian yet.
```
```

Allow for not installing the mypy_boto3_* packages

---

src/toil/leader.py
src/toil/wdl/utils.py
src/toil/wdl/wdltoil.py
src/toil/worker.py

#4978
#4977 
#4981
* Support passing inputs into toil-wdl-runner for task only WDLs
* toil-wdl-runner will now carry through task exit codes
* toil-wdl-runner will respect explicit null values for optional inputs
```
```

Support inputs for task only WDLs, pass through task exit codes, and respect explicit null inputs

---

src/toil/wdl/wdltoil.py

* Debug message for overriding a workflow default is now correct
```
```

Revise debug message for new code

---

src/toil/cwl/cwltoil.py

Closes #4990
This solution gets around [needing to change cwltool's internals](https://github.com/DataBiosphere/toil/issues/4990#issuecomment-2218271659) by prepulling containers before the job fully runs. This does mean the `get_image` step is called twice, but the second call will see a cached image instead. Ideally, only one call is needed, but that will require internal changes to cwltool.
This also sets a default `SINGULARITY_CACHEDIR`, but maybe it shouldn't be the same as Singularity's default?
* Prevent simultaneous Singularity container pulls in toil-cwl-runner
```
```

Add locking to Singularity pulls in toil-cwl-runner

---

src/toil/common.py
src/toil/test/utils/utilsTest.py

* Generate default config correctly, fix #5014
```
```

Fix regression in default config generation (#5014)

---

src/toil/test/cactus/test_cactus_integration.py

See #5017 , `master` is failing: https://ucsc-ci.com/databiosphere/toil/-/pipelines/7593
Either we upgrade cactus so that its dependencies make sense in python3.12 or we run cactus on python3.11.  This fix is the former.
* Use the latest setuptools when running cactus.
```
```

Update Cactus Integration Test setuptools.

---

requirements-cwl.txt

cwltool will handle version management so this should be robust enough
See: https://github.com/DataBiosphere/toil/pull/5016#discussion_r1684270791
* Relax cwl-utils version requirement
```
```

Relax required cwl-utils version to match cwltool

---

src/toil/test/utils/toilDebugTest.py

This adds logging to make it possible to debug #5041.
* Logic to create a failed workflow job store will now pass through logs from the workflow
```
```

Add debug logging around missing root jobs in failed workflow fixtures

---

src/toil/wdl/wdltoil.py

This fixes #5041 by using syntax that older Pythons can actually understand when talking about union types in executable code. It turns out there wasn't a race; the #5030 PR that introduced the problem changed more than just the dependency version, and we didn't test it on older Python versions as part of the PR CI pipeline.
* `toil-wdl-runner` works again on Python 3.8 and 3.9 after MiniWDL version upgrade
```
```

Use pre-3.10 union syntax in WDL runner

---

.gitlab-ci.yml

We're using a pretty old version of cactus on CI, so this updates it to cactus 2.9.0
* Update cactus on CI to 2.9.0
```
```

Update cactus on CI

---

src/toil/batchSystems/lsf.py

Closes #4605 
* Fix `bjobs` stdout getting lost in LSF
```
```

Don't drop stdout in subprocess call for LSF

---

docs/running/cliOptions.rst
src/toil/batchSystems/abstractGridEngineBatchSystem.py
src/toil/batchSystems/options.py
src/toil/common.py

#5063 
* Added `--memoryIsProduct` to support batch systems that multiply requested memory with requested cores
```
```

Add `--memoryIsProduct` for clusters that multiply requested memory and cores

---

contrib/admin/mypy-with-ignore.py
src/toil/lib/aws/s3.py

This should fix things.
* Fix linting for lib.s3.py
```
```

Fix linting.

---

src/toil/test/wdl/testfiles/wait.wdl
src/toil/test/wdl/wdltoil_test.py
src/toil/wdl/wdltoil.py

This will fix #5090 by hiding the resource monitor process from Bash's job system.
* `toil-wdl-runner` will no longer hang when running workflows using Bash `wait` on Docker
```
```

Add subshell to hide resource monitor

---

src/toil/wdl/wdltoil.py

This should hopefully fix CI and also any possible loss of workflow outputs.
* `--allCallOutputs` no longer discards WDL workflow outputs section outputs.
```
```

Stop redefining output_bindings to fix CI

---

src/toil/provisioners/node.py

Resolves #5119 
* Remove deprecated pipes module
```
```

Replace deprecated pipes module

---

.gitlab-ci.yml
contrib/toil-ci-prebake/Dockerfile
docker/Dockerfile.py
setup.py
src/toil/lib/threading.py

Closes #5130 
* Added support for Python 3.13
```
```

Update to Python 3.13

---

requirements-dev.txt

* type-checking: set minimum version of types-psutil to match types update
```
```

set minimum version of types-psutil to match types update

---

.github/dependabot.yml
.gitlab-ci.yml
requirements-dev.txt

* Dependabot configuration should now pass schema validation and is itself under CI
```
```

Move rebase-strategy into each updates element

---

.gitlab-ci.yml
src/toil/test/wdl/wdltoil_test_kubernetes.py

This updates Cactus to a version that doesn't want the `pipes` module that Python 3.13 removed.
This also gives more time to the WDL conformance tests on Kubernetes, since they were observed to time out and we were only giving them about 10 minutes.
* Toil now tests a version of Cactus that ought to run on Python 3.13.
* WDL conformance tests on Kubernetes may now run for 30 minutes.
```
```

Fix Integration Tests

---

docker/Dockerfile.py

* Remove distutils install for Python 3.12 appliance
```
```

Python 3.12 has no distutils

---

src/toil/jobStores/aws/jobStore.py
src/toil/lib/aws/session.py
src/toil/lib/aws/utils.py
src/toil/wdl/wdltoil.py

This can replace most of #5205 and fix #5203. Instead of having a setting this just always tries anonymous read for AWS URLs, and falls back to logging in.
* Try anonymous AWS access for URLs before logging in
```
```

Simple anonymous aws

---

src/toil/batchSystems/slurm.py
src/toil/test/batchSystems/test_slurm.py

Should now no longer ever accept a GPU partition when a normal one will do, or a high-priority partition when a low-priority one will do.
This will fix #5223.
* Toil will no longer select GPU or high-priority Slurm partitions when it does not need to.
```
```

Add tests for and fix Slurm partition selection

---

src/toil/cwl/cwltoil.py
src/toil/test/cwl/cwlTest.py
src/toil/test/cwl/optional-file-exists.json
src/toil/test/cwl/optional-file-missing.json
src/toil/test/cwl/optional-file.cwl
src/toil/test/cwl/revsort-job-missing.json

Resolves #5174 
This also adds tests to ensure optional secondary file workflows work.
* Improve error message when a file is not found in CWL
```
```

Improve missing file error message

---

src/toil/worker.py

This should fix #5214 by adding a hack that just `lsof`s the Toil worker process every once in a while, while tolerating various hangs.
We still have no real insight into what `lsof` does to un-stick a stuck worker, or why the worker gets stuck in the first place. But this should hopefully help @glennhickey and the other users who have been reporting this stuck-job problem on our Slurm cluster.
* Add hack to automatically un-stick jobs that can be un-stuck by `lsof`.
```
```

Add worker unstick-ing thread

---

docs/appendices/environment_vars.rst
docs/python/developing.rst
docs/running/cliOptions.rst
docs/running/hpcEnvironments.rst
src/toil/batchSystems/slurm.py
src/toil/common.py
src/toil/job.py
src/toil/test/batchSystems/test_slurm.py

This fixes #5230 and fixes #5231 by adding the requested options and adding back `--time` as an allowed argument in `TOIL_SLURM_ARGS`.
I'm adding some actual parsing of `TOIL_SLURM_ARGS` and some tests for the new functionality (though not all the way through to Toil option parsing) and for the other Slurm option things we are supposed to do (like `--export-file` handling).
* Re-added support for `--time` in `TOIL_SLURM_ARGS`
* Added `--slurmPartition` and `--slurmGPUPartition` options for manual Slurm partition selection.
```
```

Add `--slurmPartition` and `--slurmGPUPartition` and support `--time` in `TOIL_SLURM_ARGS`

---

.gitlab-ci.yml
src/toil/test/cwl/conftest.py

- cwl conformance testing: fix doc string
- cwl conformance tests: run with --bypass-file-store

Attempt to fix the CWL conformance test badge

---

docs/cwl/conformance.rst
docs/index.rst
docs/running/debugging.rst
docs/wdl/conformance.rst
docs/wdl/developing.rst
docs/wdl/running.rst
docs/wdl/tutorial.rst

@benedictpaten wanted us to move some of the tutorial stuff I'd written for the GI wiki over into the actual Toil documentation. This does that.
I'm also trying to harmonize some of the document titles between CWL and WDL.
* Toil WDL documentation now includes tutorial and debugging content from the UCSC GI wiki
```
```

Revise WDL Docs

---

src/toil/job.py

This should fix #5240.
We probably want a test for this to make sure the batches really are set up like we expect them to be.
* `--runImportsOnWorkers` should no longer import files repeatedly
```
```

Clear batch of files to import when it is full

---

src/toil/__init__.py

This should fix #3635 
* Removed unused values and functions from root `toil` namespace
```
```

Remove unused cache file and try/except

---

docs/appendices/environment_vars.rst
src/toil/lib/dockstore.py
src/toil/lib/history_submission.py

This connects Toil to production Dockstore so metrics will actually be accepted when published.
* Toil metrics published to Dockstore now are marked as coming from `TOIL` and not `OTHER`.
* Toil metrics published to Dockstore are now "authenticated" with a public, non-secret token.
* Dockstore publication tkinter dialog now opens over other windows on Mac.
* Publishing metrics for the current workflow will no longer send an empty list of tasks also.
```
```

Hook up credentials for live Dockstore

---

src/toil/wdl/wdltoil.py

This fixes part of #5247, but doesn't (yet?) add the test to keep it working.
* `toil-wdl-runner` can again successfully finish a workflow and emit outputs when using `--restart`
```
```

Make sure wdl_options is available for exports on restart

---

src/toil/test/__init__.py

This PR is adapted from a patch we are carrying in Debian: https://salsa.debian.org/med-team/toil/-/blob/master/debian/patches/needs_aws-proxyfix?ref_type=heads
* aws_s3: also skip tests if there is a proxy error
```
```

needs_aws_s3: also skip if there is a proxy error

---

.gitlab-ci.yml
requirements-dev.txt

* Speed up CWL badge generation on CI
```
```

Use multiple threads for CWL badge generation on CI

---

docs/running/cliOptions.rst
docs/running/debugging.rst
src/toil/common.py
src/toil/leader.py
src/toil/options/common.py

This will fix #5243.
* Toil now supports `--stopOnFirstFailure=True` to stop a workflow when the first completely failed job is detected.
```
```

Add feature to stop on first failure

---

requirements-server.txt
src/toil/server/cli/wes_cwl_runner.py

Flask is also pinned to prevent pip from searching too much for a compatible flask package. I believe this can be unpinned once https://github.com/common-workflow-language/workflow-service/pull/136 is merged into wes-service
* Fix a bug in Toil server mode
```
```

Update YAML parsing in Toil server mode

---

setup.py

This fixes #5270 by making the setup.py codegen code that is already trying to run actually run correctly in the environment we get when we're a pyproject.toml project. We don't get the whole package on the Python path for free so we have to add it to find the version template file.
* Toil can now build correctly for pip installs from Git again.
```
```

Fix codegen in setup.py to work during pip install from Git alongside pyproject.toml

---

src/toil/common.py
src/toil/options/wdl.py
src/toil/test/wdl/lint_error.wdl
src/toil/test/wdl/wdltoil_test.py
src/toil/wdl/wdltoil.py

Closes #4630 
* Added lint checking to toil-wdl-runner
* Use `--strict=True` to error on lint warnings
```
```

Add MiniWDL's lint checking to toil-wdl-runner

---

src/toil/lib/dockstore.py
src/toil/test/wdl/wdltoil_test.py

This will fix #5264 by checking with an integration test to make sure we can really publish metrics to Dockstore.
This is using the staging Dockstore and not QA Dockstore because the Dockstore team thought that made more sense.
* Publication of workflow metrics to Dockstore is now under CI test.
```
```

Add message and test for making sure Dockstore accepts our metrics

---

.gitlab-ci.yml
src/toil/lib/misc.py
src/toil/test/__init__.py
src/toil/test/src/jobTest.py
src/toil/test/src/miscTests.py
src/toil/test/wdl/wdltoil_test.py

This should fix the regression in #5235 where we stopped type-checking on Python 3.9, which wasn't in the main every-PR CI path.
* Toil now tests linting on the oldest supported Python for every PR
```
```

Restore 3.9 support

---

.gitlab-ci.yml

I was wondering why CWL badge generation wasn't working, turns out #5234 removed `allow_failure: true`, so the current badges are pointing to nonexistent runs.
* Fix a regression in CWL badge generation
```
```

Fix CWL badges

---

src/toil/test/wdl/testfiles/read_file.wdl
src/toil/test/wdl/wdltoil_test.py
src/toil/wdl/wdltoil.py

This should fix #5251 by adding the desired test. To get a workflow that always fails the first time and always succeeds the second time, I'm using the WDL ability to read a file from a string at workflow scope, and assuming we don't creatively split up a single WDL `Decl` input multiple jobs.
* `--restart` for `toil-wdl-runner` is now under CI testing
```
```

Test WDL Restart

---

src/toil/lib/accelerators.py
src/toil/test/wdl/md5sum/md5sum-gs.json

* Suppress spurious nvidia warnings
```
```

Suppress spurious nvidia warnings.

---

src/toil/common.py
src/toil/cwl/cwltoil.py
src/toil/cwl/utils.py
src/toil/jobStores/abstractJobStore.py
src/toil/jobStores/aws/jobStore.py
src/toil/jobStores/fileJobStore.py
src/toil/jobStores/googleJobStore.py
src/toil/lib/url.py
src/toil/test/lib/test_url.py
src/toil/wdl/wdltoil.py

* Refactor URL access function
```
```

Refactor URL access function

---

.gitlab-ci.yml

I noticed that in #5323 I think we added this test run, but we don't really need it since we don't actually have any integrative plugin tests yet. The ones it wants to run are bench tests that `quick_test_offline` already runs.
* Remove separate plugin test job since quick_test_offline runs them
```
```

Remove separate plugin test job since quick_test_offline runs them

---

.gitlab-ci.yml
Makefile
src/toil/test/server/serverTest.py

This fixes #5332. I noticed one of the server mode tests in `make test_1min` was failing, and it turns out we needed to make a bunch of changes to them for the Connexion 3 upgrade. This makes those changes, and adds the server mode tests to CI in more places so this shouldn't happen again.
It turns out the non-integrative server mode tests only take about 20 seconds to run, so I added them to the normal main test runs.
* Toil server mode CI tests now run on PRs
* Toil server mode integration tests now run on PRs that touch the server code
* Toil server mode CI tests are now updated for Connexion 3
```
```

Fix the CI tests for server mode

---

requirements-dev.txt
src/toil/test/lib/test_url.py
src/toil/test/wdl/testfiles/url_to_optional_file.wdl
src/toil/test/wdl/wdltoil_test.py

* Toil web URL tests now run against local servers instead of httpstat.us
```
```

Set up a local server for tests instead of httpstat.us

---

requirements-aws.txt
requirements-dev.txt
src/toil/provisioners/aws/awsProvisioner.py
src/toil/test/lib/test_url.py
src/toil/test/wdl/testfiles/url_to_optional_file.wdl
src/toil/test/wdl/wdltoil_test.py

This should fix #5342. It will use https://github.com/adamchainz/ec2-metadata/pull/562 if available and if not it will use a copy of the SSH key name it hides in the instance tags.
I still need to test actually running an in-workflow autoscaler workflow with this change, since CI doesn't cover that apparently.
* Prepare for https://github.com/adamchainz/ec2-metadata/pull/562 and in the meantime hide SSH key name in instance tags.
```
```

Fix finding the leader's AWS SSH key

---

Makefile
docker/Dockerfile.py
src/toil/provisioners/aws/awsProvisioner.py

This should fix #5344. It includes adamnovak/http-parser and pymesos==0.3.15 in the Docker image for Python versions where Toil can't transitively depend on the `http-parser` in PyPI.
* Toil Docker image now supports Mesos on Pythons newer than 3.10
```
```

Inject patched http-parser for modern Python Mesos support

---

src/toil/test/cwl/cwlTest.py

This should fix the issue I was chasing in https://github.com/DataBiosphere/toil/pull/5351/commits/b974cc391e92b4bb240625f5e108675ee0ed8411 in #5351. We can put a whole pre-formatted string that contains `%` in as a log message, and manually using that with an empty args tuple isn't quite what the logging module itself does, and crashes. When sniffing the log messages with a handler, we need to ask `logging` to produce the final string for us.
This is a port over from the `releases/9.0.x` branch.
* CI tests that sniff logs will no longer crash when a Toil job log containing `%` is logged
```
```

Use logging method instead of manual formatting to support non-format-string messages
