setup.py, src/toil/common.py, src/toil/job.py
Byte-based resource requirements can be specified as various byte-based units in addition to just bytes. Adds this functionality to Job's resource requirements as well as the max_log_size and default/max memory/disk toil options. Adds bd2k-python-lib 1.7 as a dependency, and uses the human2byte method provided within that library.
=> Specify memory reqs as string (resolves #172)

src/toil/job.py, src/toil/leader.py, src/toil/test/dependencies/dependenciesTest.py, src/toil/test/mesos/stress.py, src/toil/test/sort/sortTest.py, src/toil/test/src/jobEncapsulationTest.py, src/toil/test/src/jobServiceTest.py, src/toil/test/src/jobTest.py, src/toil/utils/toilRestart.py
Change behavior of Job.Runner.startToil to raise an exception if there are failed jobs at the end of a run.
Resolves #277
=> Change behavior of Job.Runner.startToil (resolves #277)

src/toil/common.py, src/toil/job.py, src/toil/test/sort/sort.py, src/toil/test/src/jobServiceTest.py, src/toil/test/utils/utilsTest.py, src/toil/worker.py
Cherry picked 0023582d28cdfea82940734a8d1f50005a46bbe8 (+3 squashed commits)
Squashed commits:
[c89fac4] Fixes to hot deployment of service- and function-wrapping jobs
Only localize user function modules if they don't belong to toil. Ensure that the module containing a service whose job is at the root of a workflow will be hot-deployed.
[98a833c] Added missing globalization of service module descriptor
[e9e990a] Utils test was broken but the error was masked because sortTest success
was set to equal 1. This is fixed, as is the serviceTestIssue. Hannes,
please test this now works for you on pyCharm.
=> Fixed pickling of service jobs by importing and hot-deploying corresponding user module (resolves #272)

setup.py, src/toil/common.py, src/toil/jobStores/azureJobStore.py, src/toil/jobStores/conftest.py, src/toil/test/__init__.py, src/toil/test/jobStores/jobStoreTest.py
Azure functionality seems to work OK (if slowly, from outside the azure datacenter anyway), and passes the existing tests.
Some caveats:
- Azure is very picky about table and container names, so the namePrefix probably has to be alphanumeric.
- For credential storage, right now it uses a supplemental file (~/.toilAzureCredentials) with a format that looks like this:
```
[AzureStorageCredentials]
accountName1=ACCOUNTKEY1==
accountName2=ACCOUNTKEY2==
```
because multiple Azure "storage accounts" can exist under a single Microsoft account. Right now the tests use the hardcoded "toiltestaccount" storage account.
=> Azure job store (resolves #87)

src/toil/job.py
sys.maxint is also used as the default for the max resources flags in common, but those usages seem appropriate and were kept.
=> Remove sysmaxint as a placeholder in Job.py (resolves #227)

src/toil/batchSystems/gridengine.py, src/toil/batchSystems/singleMachine.py, src/toil/common.py
Added maxDisk to the gridEngineBatchSystem constructor
replaced undefined values in __str__ with self.values
Fixed typo (curline -> currline)
Added disk to issueBatchJob and self.checkResourceRequest
maxWait not defined in killBatchJobs method, replaced with standard killedJobsQueue.get()
Added shutdown method to gridEngine
Replaced getFromQueueSafely with standard .get() call
Changed "p=str(cpu)" to specify cores to:  ["-pe", "smp", str(cpu)]
CPU only accepts integers. Since TOIL handles floats, the values supplied to cpu will be rounded up.
Added debug messages for logging.
Added explanatory docstring for overridden shutdown() (+19 squashed commits)
=> Fix gridEngine (resolves #213)

src/toil/worker.py
Catch ValueError when toil is installed into virtualenv from pip.
Resolves #290
=> Error removing toil/src directory from python path (resolves #290)

src/toil/batchSystems/parasol.py, src/toil/batchSystems/parasolTestSupport.py, src/toil/test/__init__.py, src/toil/test/batchSystems/batchSystemTest.py
All the unit tests pass, but I had to increase the memory limits to 1 GB because parasol apparently needs at least 100 MB for each job. The problems from before were all due to the memory limits being set too low for parasol. paraHub/paraNode don't need to be run as root.
=> Setup Parasol unit tests for continuous integration (resolves #258, resolves #282)

src/toil/common.py, src/toil/job.py, src/toil/lib/bioio.py, src/toil/test/dependencies/dependenciesTest.py, src/toil/test/mesos/helloWorld.py, src/toil/test/mesos/mesosTest.py, src/toil/test/mesos/stress.py, src/toil/test/sort/sort.py, src/toil/test/sort/sortTest.py, src/toil/test/src/jobEncapsulationTest.py, src/toil/test/src/jobServiceTest.py, src/toil/test/src/jobTest.py, src/toil/test/src/jobWrapperTest.py, src/toil/test/utils/utilsTest.py, src/toil/utils/toilClean.py, src/toil/utils/toilKill.py, src/toil/utils/toilRestart.py, src/toil/utils/toilStats.py, src/toil/utils/toilStatus.py
Includes the toil utils, removes the deprecated optparse since it offers very limited positional support.
=> Make jobStore argument positional (resolves #329)

setup.py, src/toil/common.py, src/toil/jobStores/azureJobStore.py, src/toil/lib/encryption.py, src/toil/test/jobStores/jobStoreTest.py
Currently it uses only one key. Having a separate key for each file is certainly possible, but it involves some key distribution which would be slightly trickier.
Only the path to the key file is ever stored in the jobStore, because I was a bit paranoid about stuff getting pickled and passed around so often. If the job store never, ever gets pickled, maybe we could save a bit of I/O and read it in at job store creation.
This client side encryption should work fine for the file job store too.
=> Client-side encryption for Azure job store (resolves #308)

src/toil/batchSystems/gridengine.py
Modified __init__ in MemoryString class in gridengine.py to support for terabyte (T) MEMTOT output from host, and specified shm processors via -pe shm in prepareQsub function.
Resolves #409
=> Ported GridEngine terabyte fix and shm processors from JobTree (resolves #409)

src/toil/job.py, src/toil/test/src/jobFileStoreTest.py
Fixed Job.FileStore.readGlobalFile to allow a user specified location with the job's temporary directory structure. Fixed Job.FileStore.writeGlobalFile to not put files in the cache and subsequently delete files which are not within the job's temporary directory structure.
=> Issues/467 fix file store methods (resolves #467, resolves #468)

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/gridengine.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/parasol.py, src/toil/batchSystems/singleMachine.py, src/toil/test/batchSystems/batchSystemTest.py
- In all batch systems, getUpdatedBatchJob now returns (jobID, exitValue) tuples only for jobs on which killBatchJobs was not called. This prevents killed jobs from being processed twice in the leader.
- batchSystemTest.testKillJobs updated to enforce this behavior.
=> Prevent batch systems from returning killed jobs in getUpdatedBatchJobs (resolves #460)

src/toil/job.py, src/toil/test/src/jobCacheEjectionTest.py
As mentioned, First In First Out (FIFO) was implemented as the cache ejection strategy if cache will be overfull at the end of a writeGlobalFile.  Wrote a unittest that tests the event.
Resolves #490
=> Implemented FIFO as cache ejection strategy + tests (resolves #490)

src/toil/lib/bioio.py, src/toil/test/src/jobTest.py, src/toil/worker.py
bioio.getTempDirectory was redundant so instead tempfile.mkdtemp() is
used. 0755 is enforced for localWorkerTempDir in worker.py 
Resolves #480 and #446.
=> Removed bioio.getTempDirectory() and enforce 755 for localWorkerTempDir (resolves #480, resolves #446) 

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/gridengine.py, src/toil/batchSystems/lsf.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/parasol.py, src/toil/batchSystems/parasolTestSupport.py, src/toil/common.py, src/toil/test/batchSystems/batchSystemTest.py
- Create a new results file each time a job is issued with a new unique combination of ram and CPU requirements. 
- Switch the updated jobs worker to a thread instead of a daemon process.
- When shutting down, make the batch system clean up all the jobs it issued, and clear sick jobs.
- Use "parasol -results=<resultsForBatch> pstat2" on each batch to list issued jobs, instead of "parasol list jobs." This avoids listing all jobs on the cluster, which is slow when other users have created many jobs.
- Eliminate getFromQueueSafely in abstractBatchSystem because it was only necessary for multiprocessing.Queue, not Queue.Queue.
=> Make Parasol batch system create a separate batch for each set of ram and cpu requirements (resolves #396, resolves #429, resolves #456)

src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/azureJobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/lib/encryption/_dummy.py, src/toil/lib/encryption/_nacl.py, src/toil/test/__init__.py, src/toil/test/jobStores/jobStoreTest.py
- convert encryption mandate in job store to tri-state (yes, no, maybe)
- store encryption status of an Azure blob as metadata alongside that blob
- avoid memoizing the encryption key in AWS job store, consistent with Azure store
- log the missing extra when skipping a test
- renamed encryptionOverhead to just overhead
=> Make sure that an encryption mandate is never ignored (resolves #407)

src/toil/__init__.py
=> Don't use absolute paths for entry points outside of virtualenvs (resolves #536)

src/toil/jobStores/aws/jobStore.py
=> AWS job store: Properly distinguish between version of None and empty string (resolves #532)

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/mesos/__init__.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/mesos/executor.py, src/toil/batchSystems/singleMachine.py, src/toil/common.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/azureJobStore.py, src/toil/test/batchSystems/batchSystemTest.py
This will allow setting LD_LIBRARY_PATH which wouldn't work with the environment.pickle mechanism. Use that ability to distribute Azure credentials
Partially addresses #473, but see #547.
=> Ability to communicate environment variables from leader to worker (resolves #441, resolves #421)

.gitignore, setup.py, src/toil/job.py, src/toil/resource.py, src/toil/test/src/resourceTest.py, src/toil/test/src/userDefinedJobArgTypeTest.py
- Extend tests a bit
- Eliminate unnecessary warnings in localize() and globalize()
Resolves #565
=> Include sibling modules of user scripts when deploying them to workers (resolves #565)

src/toil/__init__.py, src/toil/batchSystems/parasolTestSupport.py, src/toil/batchSystems/singleMachine.py
=> Fallback to sysctl when os.sysconf('SC_PHYS_PAGES') fails on OS X (resolves #587)

src/toil/cwl/cwltoil.py
If no args are passed to cwltoil tool main method, use system args (the default None will cause exception on the [workdir] + args)
=> Fix NPE in cwltoil entry point

setup.py, src/toil/cwl/cwltoil.py
Fix for issue #621 
This was due to the cwltool module having an open-ended dependency on the schema-salad module.  I made a incompatible change to schema-salad which broke cwltool which was pulling in the latest version.
cwltool now pins a specific version of schema salad, but this means toil needs to pin a new version of cwltool.
Also includes a small fix to the cwltoil main method.
=> Issue 621 cwl schema (resolves #621)

src/toil/job.py
This commit checks file ownership before trying to change the
permissions on a file that a job wants to put in the file store. If you
want to, say, store the local node's syslog file, or a file owned by
another user on a shared disk, we have to do this.
=> Allow uploading unowned files to file store

docs/conf.py, docs/essentials.rst, docs/tutorial.rst, src/toil/job.py, src/toil/jobStores/abstractJobStore.py
Fixes several rst formatting errors and an incorrectly listed html source in conf.py. 
Most errors involved the use of special rst characters in docstrings ( * and | ) and required backslashes to escape them. This makes the docstrings much uglier but I don't see a way around it.
=> Fix Sphinx build warnings (resolves #594)

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/gridengine.py, src/toil/batchSystems/lsf.py, src/toil/batchSystems/mesos/__init__.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/mesos/executor.py, src/toil/batchSystems/parasol.py, src/toil/batchSystems/singleMachine.py
Resolves #651 
1. Implemented abstract methods in AbstractBatchSystem for this.
2. SingleMachine and Mesos call the worker cleanup function on shutdown
3. All batch systems now have a static method for indicating whether they
support worker cleanup.
=> Add support for worker clean-up to single-machine and Mesos batch systems (resolves #651)

src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/mesos/executor.py
This just makes handling of exceptions that occcur while running tasks in the executor more robust. Also logs the exception on the executor and includes the Popen setup in the try block.
=> Fix: ValueError for failed Mesos tasks kills framework (resolves #671)

src/toil/batchSystems/mesos/batchSystem.py
=> Fix: Catch KeyError in Mesos scheduler when job finishes (resolves #674)

jenkins.sh
resolves #704
The test framework uses the system TMPDIR to create temp working directories for running toil tests. If we
set it to a directory on /mnt/ephemeral while running tests on jenkins, then the tests can run in a larger volume
allowing for tests to use more space if need be.
=> Use ephemeral for running Toil tests on Jenkins (resolves #704)

docs/tutorial.rst
The [promises documentation example](http://toil.readthedocs.org/en/releases-3.1.x/tutorial.html#promises) raises the following error when tested:
```
2016-03-11 17:44:37,186 WARNING:toil.leader: o/u/job3P9XQk:       File "promises_test.py", line 6, in fn
2016-03-11 17:44:37,186 WARNING:toil.leader: o/u/job3P9XQk:         job.fileStore.logToMaster("i is: %s" % i, logLevel=100)
2016-03-11 17:44:37,186 WARNING:toil.leader: o/u/job3P9XQk:     TypeError: logToMaster() got an unexpected keyword argument 'logLevel'
```
=> logLevel in logToMaster is not a valid parameter anymore

jenkins.sh
resolves #719
`/mnt/ephemeral/tmp` is now deleted before and after the jenkins tests. This prevents the testing temp directory from having other files in it when the test starts.
=> Reset TMPDIR with every call of jenkins.sh (resolves #719)

src/toil/batchSystems/abstractBatchSystem.py, src/toil/common.py, src/toil/leader.py, src/toil/test/src/retainTempDirTest.py, src/toil/worker.py
Cherry picked already merged commits from 3.1.x branch. Resolves a logToMaster issue, EOF error upon root job failure, and adds support for optionally retaining the workDir on workers.
=> Port commits from 3.1.x onto master (resolves #683, resolves #686, resolves #690)

docs/toilAPI.rst, docs/tutorial.rst, src/toil/batchSystems/abstractBatchSystem.py, src/toil/common.py, src/toil/job.py, src/toil/jobStores/abstractJobStore.py, src/toil/leader.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/sort/sortTest.py, src/toil/test/src/jobServiceTest.py, src/toil/test/src/jobWrapperTest.py, src/toil/test/src/toilContextManagerTest.py, src/toil/test/utils/utilsTest.py, src/toil/utils/toilClean.py, src/toil/utils/toilKill.py, src/toil/utils/toilRestart.py, src/toil/utils/toilStats.py, src/toil/utils/toilStatus.py, src/toil/worker.py
The Toil class is meant to be used as a context manager and has all of the functionality of setupToil. Many of the  top level methods in common that
setupToil previously used have been refactored as regular or static methods of common.Toil.
Here is a list of methods that were refactored and their common.Toil counter parts:
- (loadBatchSystem, loadBatchSystemClass, createBatchSystem) >> Toil.createBatchSystem
- loadJobStore >> Toil.loadOrCreateJobStore
- serialiseEnvironment >> Toil._serialiseEnvironment
- getToilWorkflowDir >> Toil.getWorkflowDir
A word on the loadBatchSystem, loadBatchSystemClass, createBatchSystem:
These methods were extremely redundant. createBatchSystem did almost nothing; loadBatchSystem simply calls createBatchSystem and there was
no useful use case for the …
=> Refactored setupToil and other methods into common.Toil class (resolves #619, resolves #749)

docs/tutorial.rst, setup.py, src/toil/common.py, src/toil/job.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/azureJobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/test/__init__.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/src/importExportFileTest.py
Every concrete jobStore now supports importing and exporting files to other jobStores. These methods are exposed to the toil user in job.py. There is also now a standalone multipart copy function for S3, and a dynamic test method generator function in toil test.
=> Add import/export file methods to AbstractJobStore (resolves #645, resolves #618, resolves #660)

src/toil/job.py
=> Moving try to stop service.stop from being called if service.start (Resolves #756)

src/toil/batchSystems/slurm.py, src/toil/common.py, src/toil/test/__init__.py, src/toil/test/batchSystems/batchSystemTest.py
Continued from #718 
Implements support for slurm scheduler
SlurmBatchSystem class is modeled after GridengineBatchSystem
Maps AbstractBatchSystem methods to sbatch, squeue, scancel, sacct, sinfo subprocess calls
Includes SlurmBatchSystemTest for testing system
Wrap submitted sbatch command in --wrap
=> Support for Slurm batchSystem (resolves #682)

src/toil/job.py, src/toil/test/src/jobServiceTest.py
Replaces functionality by adding an argument Job.addService.
Job.Service.addChild is dangerous, because the user might call addChild
after the Service has already been serialised, e.g. in
Job.Service.start.
=> Removes Job.Service.addChild as a public method  (resolves #794)

src/toil/jobStores/aws/jobStore.py, src/toil/test/jobStores/jobStoreTest.py
boto.new_key was used instead of boto.get_key
=> Fix imports of files > 5GiB from S3 (resolves #816, resolves #829)

src/toil/test/__init__.py
Resolves #825 
Previously the first letter of the value name was uppercase and every subsequent letter was lowercase. e.g. ```test_generalMethodName__param1_Valuename()```. This is a bit arbitrary since value names are fairly discernible given that a single underscore separates parameter names and their respective value names. Now the same method would look like: ```test_generalMethodName__param1_valuename()```.
=> All values in generated function names are lowercase (resolves #825)

Makefile, docs/installation.rst, jenkins.sh
Resolves #935.
Also includes a variety of minor Makefile and documentation fixes.
=> Add `make prepare` for installing build reqs (resolves #935)

docs/toilAPI.rst, setup.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/job.py, src/toil/leader.py, src/toil/test/batchSystems/batchSystemTest.py, src/toil/test/src/promisedRequirementTest.py
Resolves #729, continued from #791
=> Implement promised requirements (resolves #729)

src/toil/job.py, src/toil/test/src/jobCacheTest.py
Resolves #953 
Resolves #949 
Harbinger timeout bug was fixed by adding logic for jobs to ensure that the process downloading the
requested file from the job store  is still alive, and to handle the case where it isn't.
Docstring in AbstractCacheTest._multipleFileReader was updated to reflect the changes made to it since
the function was written.
=> Fix harbinger timeout bug and _multipleFileReader docstring (resolves #953, resolves #949)

setup.py
Moves cwltool version pin to match that used in arvados-cwl-runner so
both can exist in the same python environment. This has been tested with
full bcbio generated CWL runs on arvados-cwl-runner and cwltoil.
Discussed with @tetron who recommended synchronizing until we move to
semantic versioning on cwltool. Follows up on #910.
=> Synchronize cwltool version with arvados-cwl-runner

src/toil/leader.py
The previous behavior sometimes caused a parent job to schedule its already-finished children, because  its stack hadn't been correctly updated.
The basic pattern was: a failed child job reruns successfully, notices that its parent job's successors have all finished, then puts the parent in updatedJobs so it can be deleted. However, the parent job still had the failed child job in its stack, so the child got scheduled again. Since the child had already finished, that raised a NoSuchJobException.
Stylistic note: the `stackNeedsUpdating` variable is just for convenience, so that the if statement on line 778 doesn't get too complicated.
=> Fix scheduling a restarted successor twice (resolves #808)

src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/aws/utils.py
Resolves #967
… and its bastard cousin 104.
Also renames another retry predicate.
=> Retry SDB requests on ECONNRESET (resolves #967)

src/toil/job.py, src/toil/worker.py
resolves #973
refactored Job._execute into Job._executor and Job._runner and modified worker.py to use the new
context manager syntax of Job._executor.
=> Refactor Job._execute (resolves #973)

jenkins.sh, src/toil/job.py, src/toil/test/src/jobCacheEjectionTest.py, src/toil/test/src/jobCacheTest.py
resolves #966 
asyncWrite is now a class method and CachedFileStore overloads it with a cache-friendly version
=> Fix async writing of files to jobstore in caching (resolves #966)

docs/spark.rst
Also removed `src/toil/spark/__init__.py`, which had snuck in.
=> Fixed Spark module path in documentation (resolves #1001)

src/toil/lib/spark.py
Moves the hostname capture to the start method of the Spark service job. This resolves the issue where the hostname of the node starting the service was being captured, thus causing the wrong IP address to be returned for the Spark cluster leader.
=> Capture hostname in Spark start method (resolves #1007)

src/toil/common.py, src/toil/job.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/azureJobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/jobStores/googleJobStore.py, src/toil/leader.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/sort/sortTest.py, src/toil/utils/toilClean.py, src/toil/utils/toilKill.py, src/toil/utils/toilStats.py, src/toil/utils/toilStatus.py, src/toil/worker.py
Job store string has now been refactored completely. The syntax for each job store locator has been documented in the job store option help message. Minor corrections to outdated documentation have also been made.
=> Refactored job store string to locator (resolves #864, resolves #991, resolves #992)

src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/utils.py, src/toil/test/jobStores/jobStoreTest.py
HTTP import now uses ```shutil.copyfilobj``` and uses the general retry functionality in job store utils.
=> Retry on certain errors during HTTP imports (resolves #1010)

src/toil/jobStores/azureJobStore.py, src/toil/test/jobStores/jobStoreTest.py
A new jobStoreExists method is used to test for existence. A unit test has been added for the new method.
=> Removed registry from Azure job store (resolves #975)

src/toil/common.py, src/toil/job.py, src/toil/test/src/jobCacheTest.py, src/toil/worker.py
resolves #1029
Removed legacy Job.FileStore.
Removed all mentions of the legacy cache requirement.
Removed --useSharedCache flag.
Modified worker.py to remove all legacy FileStore operations.
Renamed Job.CachedFileStore to Job.FileStore
=> Remove legacy FileStore (resolves #1029)

src/toil/common.py
Resolves #921
Secondary exceptions raised in  the ```__exit__``` method of the Toil context manger can mask a primary exception. This has been fixed with a simple try except block.
=> Prevents exception masking in Toil context manager (resolves #921)

docs/index.rst, docs/running.rst, setup.py, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py, src/toil/test/cwl/revsort.cwl, src/toil/test/cwl/revtool.cwl, src/toil/test/cwl/sorttool.cwl
Update of #1050 which I messed up trying to rebase.
In progress work towards v1.0 support. Current status, failing 19 out of
72 unit tests.
- Apply path/location fixes globally, required for v1.0 support
(which uses location) and back compatibility with CWL (which uses path).
- Adjusts imports to match cwltool reorganization changes
- Some functions use kwargs instead of default arguments
(single_job_executor, _init_job).
- Changes from output to outputSource in job outputs.
- Start of work to improve scatter support for valueFrom by applying
after scatter process. Still in progress.
- Update internal CWL revsort test to v1.0 syntax
- Update conformance test to v1.0
=> CWL: test update and fixes for v1.0 support

src/toil/batchSystems/singleMachine.py
The output logging messages when running cwltoil pipelines were generic
references to jobstore directories, making it hard for users to
determine which stage of the pipeline was running. This fixes in two
ways:
- Moves references to internal file deletion to debug, instead of info.
- Handles the case where we're running CWL-based runs with filesystem
storage, reading the underlying CWL and providing a useful logging
message from the baseCommand.
This is an attempt to improve the logging output during cwltoil runs to make it easier for users to identify what stage of the pipeline they were at. In the previous iteration, users could tell jobs were running but had little insight into the current step since all the outputs are references to `_toil_worker` commands, internal jobstore IDs and …
=> Improve logging message for filestore CWL runs

src/toil/job.py, src/toil/test/batchSystems/batchSystemTest.py
resolves #1063
memory and disk can now only accept ints and humanized strings.
cores can accept only ints and floats.
=> Standardize types of values accepted as resources in Job (resolves #1063)

jenkins.sh, src/toil/__init__.py, src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/singleMachine.py, src/toil/test/batchSystems/batchSystemTest.py
resolves #770 
Adding this to 3.3.1 as a patch to 3.3.0 will help @fnothaft overcome the "unable to free up enough space for caching" error in his pipeline.
=> Add singleMachine disk tracking (resolves #770)

src/toil/common.py
@cket @arkal @hannes-ucsc -- thank you for all the work on implementing disableCaching for the batch schedulers. I tested on SLURM and all works great with the exception of this small problem with the initial sanity checks. Thank you again for tackling this.
During testing of #1072 #1079, batch schedulers would error out with a
warning to add `--disableCaching` even when set. This corrects the check
to include the status of that flag.
=> disableCaching: avoid batch error message when set

Makefile, docs/Makefile, docs/conf.py, docs/index.rst, docs/toilAPI.rst, src/toil/fileStore.py, src/toil/job.py, src/toil/test/__init__.py, src/toil/test/batchSystems/batchSystemTest.py
```make docs``` no longer auto generates rst files and documentation for each module to improve the overall clarity and quality of the documentation. The auto generated documentation was [formatted poorly](http://toil.readthedocs.io/en/latest/generated_rst/modules.html) and included every single module in toil, even those without [visible documentation](http://toil.readthedocs.io/en/latest/generated_rst/toil.lib.encryption.html). 
This will remove everything under "src" at the bottom of our [index page] (http://toil.readthedocs.io/en/latest/) and will also remove the modules index from [here](http://toil.readthedocs.io/en/latest/#indices-and-tables).
=> Fix documentation build bugs (resolves #1076) 

docs/cli.rst, src/toil/batchSystems/slurm.py
This supports SLURM native flags in a similar way [SGE does](https://github.com/BD2KGenomics/toil/blob/master/src/toil/batchSystems/gridengine.py#L177).
This is hopefully a continuation and closer to closing issue #918 and siblings.
@chapmanb
=> Add native flags support for SLURM, via TOIL_SLURM_ARGS, (resolves issue #918)

docs/batchSystem.rst, src/toil/batchSystems/gridengine.py, src/toil/test/batchSystems/batchSystemTest.py
- Provides support for specifying TOIL_GRIDENGINE_ARGS to pass
queue and other information to qsub. Environmental variable
approach synchronized with #1101
- Documentation on environmental variables
- Fix and allows debugging on qsub command line. Previous version
was missing -V so would not pass through environmental variables, and
also swallowed all qsub error output making it hard to debug problems.
SGE with cwltoil works cleanly with these improvements.
=> GridEngine: adjust qsub with TOIL_GRIDENGINE_ARGS

src/toil/batchSystems/abstractBatchSystem.py, src/toil/fileStore.py, src/toil/job.py, src/toil/test/batchSystems/batchSystemTest.py, src/toil/test/src/jobCacheTest.py
resolves #987
related to #922
Jobs can now register deferred functions -- functions that are run when the
job finishes, when the job crashes and is restarted or upon batch system
shutdown.
Every job now tests the state of other jobs on the node and can handle
cleanup of other jobs that have failed.
Added 4 tests for the deferred functions (it works, it works on restart,
jobs can handle other dead jobs, worker cleanup handles dead jobs)
=> Implement support for deferred functions (resolves #987)

Makefile
=> Fix `make docker` to not pass -f to `docker tag` (resolves #1155)

src/toil/batchSystems/mesos/executor.py
resolves #1143
The hierarchy of workdir is now:
`User-specified workdir` > `(sandox if mesos)` > `ENV TOIL_WORKDIR` > `ENV TMPDIR`
=> Set workdir to default to the executor sandbox in mesos (resolves #1143)

src/toil/job.py, src/toil/test/src/jobServiceTest.py
Changes the `Job.Service` `start` and `stop` methods to pass `job` instead of `fileStore`, which allows `Job.Service` instances to register defer methods, etc. To do this, we also modify `ServiceJob.run` to set `self.fileStore` within the service job, which was previously not exposed.
=> Allow Job.Service to access the underlying Toil Job (resolves #1191)

src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/test/jobStores/jobStoreTest.py
resolves #1202
We see a lot of leaked `jobstore-test-UUID` and `cache-test-UUID` domains in SDB
and those are due to the domains being bound before creating the s3 bucket for the
jobstore. If the bucket creation fails, Toil exited without removing the domains. This
PR adds a flag to ensure the jobstore is properly initialized, and adds logic to handle
the deletion of a failed fresh jobstore.
Added a test for this feature.
=> Delete SDB domains on failed jobstore bucket creation (resolves #1202)

docs/installation.rst
fix stale link in installation doc
=> DOC: fix link to setuptools’ extras mechanism

src/toil/common.py, src/toil/fileStore.py, src/toil/test/src/miscTests.py
resolves #1188
Added a simple check at the end of each job of how much disk space is used by the
job at the end of its lifespan. Log the results to INFO and then add a message to
WARNING if the job used more space than it requested.
Added a function to recursively get the size of a directory (including subdirectories).
Added a test for the function under a new test file `src/miscTests.py`
=> Add disk-usage logging to filestores (resolves #1188)

Makefile, src/toil/test/jobStores/jobStoreTest.py
@hannes-ucsc I ended up going with [stubserver](https://github.com/tarttelin/Python-Stub-Server) for the FTP test. I think it is better because it does not rely on any particular file system and would not require writing a test file to said file system.
With that same reasoning I subclassed the built-in http mock server into a stub server. Please let me know what you think!
=> Use stub servers for import tests (resolves #1226)

jenkins.sh, src/toil/leader.py, src/toil/test/src/resourceTest.py
Backports 8e5fd0feca3c75fd44ccd71339340656198a4d1b to 3.3.x
=> Avoid importing AWSJobStore without AWS extra installed (resolves #1115)

Makefile
Add target 'test' to Makefile and rename existing target to 'test-parallel' per #1284.
Some tests are failing on my machine (`make test`). I think it has to do with mesos - the tests that fail all seem to be mesos-related and die with a segmentation fault - but I can't pin down a root cause so I'm not 100% sure. `make test-parallel` appears to work as expected, though.
=> Run tests serially by default (connected to #1284)

docs/conf.py, docs/vendor/sphinxcontrib/__init__.py, docs/vendor/sphinxcontrib/fulltoc.py
Using http://sphinxcontrib-fulltoc.readthedocs.io/en/latest/ to display a neat, dynamic TOC that shows additional details for the section selected. It uses the Apache license so it should be fine for use to use (right?).
The addition to the makefile installs fulltoc when the user runs `make prepare`
=> Implement full, dynamic TOC sidebar (resolves #1296)

Makefile
Rename target 'test-serially' to 'test' and 'test' to 'test-parallel'
=> Test serially by default (fixes #1284)

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/gridengine.py, src/toil/test/batchSystems/batchSystemTest.py
First commit adds test to check file name. Second commit will fix results filename and shall past tests.
=> Fix miss-formatted filename for CWL Slurm (resolves #1261)

src/toil/provisioners/aws/__init__.py, src/toil/provisioners/aws/awsProvisioner.py
i.e. 'leader' --> 'toil_leader', 'worker' --> 'toil_worker'
=> Rename appliance container to toil_{role} for AWS provisioner (fixes #1364)

docs/running.rst, setup.py, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
Work in progress to update CWL support to use the latest version of
cwltool, as work to fix any ongoing CWL support issues in Toil.
This passes many standard runs including bcbio CWL, but currently fails
5 CWL conformance tests I'm stuck at how to fix; starting this branch/PR
to solicit help from @mr-c @tetron and any other CWL folks.
The PR includes these updates:
- Dump Jobs to pickles with pickle avoiding the HIGHEST_PROTOCOL.
The cPickle/HIGHEST_PROTOCOL will not serialize CWLWorkflow objects
which contain sub-workflow steps and avro/schema-salad classes
(they fail with `Can't pickle <type 'instancemethod'>: attribute
lookup __builtin__.instancemethod failed find problem attribute`)
- Ensure generalized resolver used for loading tools
- logging debugging with new pickling and Job …
=> CWL: migrate to latest cwltool

src/toil/cwl/cwltoil.py
`resolve_indirect` translates tuples (keyword, dictionary) into context
specific dictionaries for CWL jobs. When a set of values had both values
that needed evaluation and indirect tuples, the evaluation logic would
get non-eval objects from the original dictionary (`d`) instead of the
resolved one (`res`). This fixes the typo to pass along resolved references
when not running `do_eval`.
=> CWL: fix typo in resolve_indirect

src/toil/fileStore.py, src/toil/leader.py
During CWL runs, there are extra messages in the INFO log
relating to internal processes, which obscure useful messages. This
moves these to DEBUG:
- Internal jobs releated to CWL
- Cache access and read messages
- Deletion of cached files
- Adding files to be deleted from cache
Fixes #1061
=> Move internal log messages to DEBUG

docs/installation.rst
Needed since I had to dig into the source and test to figure out what `TYPE` meant in CGCLOUD context:
```
vagrant@vagrant-ubuntu-trusty-64:~$ cgcloud terminate-cluster ec2
INFO: Using zone 'ap-southeast-2a' and namespace '/vccc/'
ERROR: Unknown cluster type 'ec2'
vagrant@vagrant-ubuntu-trusty-64:~$ cgcloud terminate-cluster mesos
INFO: Using zone 'ap-southeast-2a' and namespace '/vccc/'
ERROR: Unknown cluster type 'mesos'
vagrant@vagrant-ubuntu-trusty-64:~$ cgcloud terminate-cluster toil
INFO: Using zone 'ap-southeast-2a' and namespace '/vccc/'
INFO: Binding to instance ...
INFO: ... bound to i-063c2580243a0f5d7.
INFO: === Performing terminate() on workers ===
Thread-1 INFO: Terminating instance ...
Thread-2 INFO: Terminating instance ...
Thread-1 INFO: ... instance terminated.
Thread-2 …
```
=> Explain how to terminate (remove) a cgcloud cluster

docs/developing.rst, src/toil/lib/docker.py, src/toil/test/lib/dockerTest.py
Adds support for Docker to core Toil.
I forgot to force push after squashing commits on the [previous PR](https://github.com/BD2KGenomics/toil/pull/1403) and royally bjorked the git history so that it incorporated 44 commits from master.  
I'll link from the old PR to this one so review history is preserved. This PR can be merged, I'll close the old one, and we can all pretend that never happened :see_no_evil:.
=> Add docker call (resolves #1387)

src/toil/utils/__init__.py
=> Avoid import error if ‘AWS’ extra not installed 

src/toil/provisioners/aws/__init__.py
Resolves #1464.
The very first restart after a container failure / docker daemon failure will still fail with a message like:
```
Jan 31 02:54:00 ip-172-31-25-156.us-west-2.compute.internal docker[21686]: I0131 02:54:00.597786     1 main.cpp:243] Build: 2016-07-27 20:23:20 by ubuntu
Jan 31 02:54:00 ip-172-31-25-156.us-west-2.compute.internal docker[21686]: I0131 02:54:00.597882     1 main.cpp:244] Version: 1.0.0
Jan 31 02:54:00 ip-172-31-25-156.us-west-2.compute.internal docker[21686]: I0131 02:54:00.597893     1 main.cpp:247] Git tag: 1.0.0
Jan 31 02:54:00 ip-172-31-25-156.us-west-2.compute.internal docker[21686]: I0131 02:54:00.597899     1 main.cpp:251] Git SHA: c9b70582e9fccab8f6863b0bd3a812b5969a8c24
Jan 31 02:54:00 ip-172-31-25-156.us-west-2.compute.internal docker[21686]: I0131 …
```
=> Remove toil containers before start in systemd service files (resolves #1464)

src/toil/provisioners/aws/awsProvisioner.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/test/utils/utilsTest.py, src/toil/utils/toilLaunchCluster.py
User can specify tags in the command line when running `toil launch-cluster` which will automatically be added to all node as the cluster auto scales. The form for tags is:
`toil launch-cluster -T key1=value1 --tag key2=value2 ...`
Multiple tags can be specified.
=> Optionally tag auto-scaled EC2 instances with user-specified tags (resolves #1341)

docs/contributing/source.rst, docs/deploying.rst, docs/developing.rst, src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/mesos/__init__.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/mesos/executor.py, src/toil/leader.py, src/toil/provisioners/abstractProvisioner.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/test/provisioners/clusterScalerTest.py
Resolves #1416 
The cluster statistics currently report the cluster's actual resource usage. This is helpful to users but for Toil development, especially in relation to the autoscaler, we only care about how efficiently Toil is managing the resources that a user requests regardless of whether the user is using them. This lets us distinguish between efficiency losses due to Toil scheduling/autoscaling and losses due to a user requesting more resources than needed.
=> Report 'theoretical' cluster usage in addition to actual usage

index.html
Fixes the static url for the genomics institute link.
=> Fix image url (resolves #1488)

src/toil/job.py, src/toil/test/src/jobTest.py
Fix verification that new checkpoint jobs are leaf vertices (resolves #1465, resolves #1466)
Changed to 1) correctly identify a leaf vertex and 2) to include checking of the workflow root job.
Note: This pull request is also listing a merge-related commit from updating my fork.
However, this merge-related commit did not contribute any of the changes displayed for this pull request. I reviewed the changes shown for this pull request, and they are a correct and complete set for the two fix-related commits that are intended for this pull request.
I think I know why that happened and I will avoid including extraneous commits in future pull requests.
=> Issues/1465 1466 Fix verification that new checkpoint jobs are leaf vertices

src/toil/provisioners/aws/awsProvisioner.py
Changes role name in AWS Provisioner to 'toil' instead of '-toil'.
=> Remove disallowed character from role name (resolves #1458)

Makefile, src/toil/common.py, src/toil/job.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/azureJobStore.py, src/toil/jobStores/googleJobStore.py
Resolves #1503
Skipping the automatically triggered CI test since this PR will add a new CI target. The first build with this target should fail after detecting the current usages of cPickle without HIGHEST_PROTOCOL, and the second commit I add will fix those usages.
=> Prevent hanging due to cPickle serialization 

src/toil/provisioners/aws/__init__.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/utils/toilLaunchCluster.py
CJ -- this follows up on our discussion in #1470 around using accounts with non-default VPCs. It's back compatible with the previous approach but provides a new option so a user can specify a VPC to launch in, then all other steps happen within that VPC. With this in place I can spin up and start running autoscaling CWL jobs, then get blocked by a bug in cwltool which is also fixed here. Thanks much for the help getting this in.
- Allow specifying a VPC subnet when launching a cluster. The previous
code assumed use of a default VPC which is not true for all AWS
accounts.
- VPC subnet passed to all node creation scripts so everything occurs
in same configured VPC.
- Using specific VPCs in boto requires sending security groups by ID
instead of name (https://github.com/boto/boto/issues/350). …
=> AWS autoscaling: arbitrary VPCs

setup.py, src/toil/cwl/cwltoil.py
Updates cwltool and schema-salad to help with debugging fixes for CWL
runs on AWS.
- Handles new status return tuple from single_job_executor
- Updates `adjust*Objs` import path from builder to pathmapper
=> CWL: update to latest cwltool

src/toil/cwl/cwltoil.py
Files retrieved from a filestore reference the staged file in the CWL
object `path` but not in `location` resulting in differing references
to original and staged files depending on how cwltool references the
object. This synchronizes the `location` and `path` to avoid the
confusion.
=> cwltoil: sync path/location on filestore retrieval

setup.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/test/cwl/cwlTest.py
CJ and all;
While testing bcbio CWL runs on AWS I'm running into the issue that bcbio Docker image is too big for the root volume size on CoreOS instances (8Gb). The failure log for this is below. This PR bumps it to 50Gb to allow for the Docker image + associated running data for a wider variety of pipelines.
Longer term it would be good if the launched nodes set this based on requested disk usage in the set of Job, which does get passed from CWL's ResourceRequirements. However I don't have enough expertise to implement that so this unblocks current attempts to test bcbio CWL runs on AWS.
```
---TOIL WORKER OUTPUT LOG---
c4382872-faad-41f4-b1ef-6045391331e0    INFO:toil:Running Toil version 3.7.0a1.dev353-00c18d033666227f86d798c6ce2f30d95f173a1e.
c4382872-faad-41f4-b1ef-6045391331e0 …
```
=> AWS: increase default size of root volume

src/toil/worker.py
Previously, a non-preemptable job could be run on a preemptable node if it was run in a chain from a preemptable predecessor.
=> Terminate the job chain if preemptability status changes (resolves #1537)

src/toil/leader.py, src/toil/serviceManager.py
The current service deadlock detection doesn't actually detect most (any?) deadlocks, because it works on the basis of issued jobs. Instead it just occasionally crashes the workflow when there aren't any deadlocks, because it doesn't reset when "potential deadlock" situations are gone. It also calls deadlocks when services are still starting up.
This patch:
- Works on the basis of *running*, not issued or starting, jobs
- Resets when deadlock situations are no longer detected
Stylistically, I'm not totally happy with the deep level of if conditions, and the duplicated code on the elses, but it does speed things up since it skips some expensive checks the majority of the time.
Unfortunately it's difficult to create a proper test for this. As a stopgap, here is a script that shows the wrong …
=> Fix service deadlock detection (resolves #1509)

src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/azureJobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/jobStores/googleJobStore.py, src/toil/test/src/importExportFileTest.py
Currently jobStore.importFile returns a string which is inconsistent with other methods for uploading a file to the jobStore. This PR instead makes importFile return a FileID object.
This involved adding a getSize attribute to abstractJobStore which returns the file size (in bytes) from the specified URL. This is necessary because FileID has a size attribute.
=> ImportFile should return a FileID object

src/toil/lib/bioio.py, src/toil/utils/toilStats.py
The reported "wait" time (wall-clock time - CPU time) was also almost always negative, because it was calculating CPU time - wall-clock time instead.
NB: the memory usage is still not perfect, because the only data available for the children is the maximum size of the single largest child, not (as previously implied by the docstring) the entire process tree:
>    ru_maxrss (since Linux 2.6.32)
>          This is the maximum resident set size used (in kilobytes).  For RUSAGE_CHILDREN, this is the resident set size of the largest child, not the maximum resident set size of the process tree.
Unfortunately, it's significantly more difficult to portably get the maximum RSS for the entire process tree. We would probably need to spawn a monitoring thread if we wanted to be fully accurate. But …
=> Fix incorrect memory usage and "wait" stats reporting (resolves #1541)

Makefile
The old target wasn't recursing properly.
=> Fix check_cpickle Makefile target

src/toil/provisioners/clusterScaler.py
Sorry for the delay in submitting this patch, I wanted to test this on a large run. It doesn't seem to cause any problems.
This also resolves the issue that was causing the faulty code path depending on "historical average runtime" to almost never trigger: the "average runtime" was actually just a sum of the runtime of all previous jobs, unnormalized by the number of previous jobs. So only when your current jobs have been running a truly exceptional amount of time would that path trigger.
The beta parameter is 1.2 by default. I've assumed that that's intended to mean "ignore wobbles in cluster sizes of less than 20% of the current cluster size", rather than 120%. So I subtract 1.0 from the beta parameter every time.
=> Fix a few cluster scaler bugs (resolves #1583, #1584)

src/toil/batchSystems/mesos/batchSystem.py, src/toil/provisioners/clusterScaler.py
Following run status on AWS can be difficult due to the presence of a
regularly generated identical status messages:
```
ip-10-0-0-66.ec2.internal 2017-02-14 17:55:35,221 preemptable-scaler INFO toil.provisioners.clusterScaler: Limiting the estimated number of necessary preemptable nodes (3) to the configured maximum (2).
ip-10-0-0-66.ec2.internal 2017-02-14 17:55:37,504 scaler INFO toil.provisioners.clusterScaler: Adding 0 preemptable nodes to compensate for a deficit of 0 non-preemptable ones.
ip-10-0-0-66.ec2.internal 2017-02-14 17:55:37,505 scaler INFO toil.provisioners.clusterScaler: Estimating that cluster needs 0 non-preemptable nodes of shape _Shape(wallTime=3600, memory=8589934592, cores=2, disk=0), from current size of 0, given a queue size of 0, the number of jobs per node …
```
=> AWS autoscaling: limit distracting log messages

src/toil/lib/__init__.py, src/toil/lib/docker.py, src/toil/test/lib/dockerTest.py
Resolves #1578 
Some of these retries, like docker kill, may be unnecessary. Also includes a short-circuit for _fixPermissions so it isn't fully executed if running as root.
=> Retry Docker errors when possible

src/toil/job.py
This globalizes the module descriptor during Job creation, rather than only during serializing successors. This doesn't crash anything, and seems to fix the problem as far as I can tell.
I've left the globalize() call in while serializing successors: https://github.com/BD2KGenomics/toil/blob/bfb63c9c85ae311945d61be2e1fa6e7717f05522/src/toil/job.py#L1069 because I'm a bit worried that taking it out might break restarting a workflow created previous to this commit. globalize() is idempotent so it won't matter that it's run twice (it's already run twice for function-jobs and services).
=> Globalize user module in Job.__init__ (fixes #1593)

src/toil/provisioners/clusterScaler.py
Avoids repetitive messages about increasing number of nodes when an
autoscaling cluster hits maximum node usage:
```
ip-10-0-0-38.ec2.internal 2017-04-08 20:18:48,925 preemptable-scaler INFO toil.provisioners.clusterScaler: Estimating that cluster needs 2 preemptable nodes of shape _Shape(wallTime=3600, memory=68719476736, cores=16, disk=0), from curren
t size of 2, given a queue size of 2, the number of jobs per node estimated to be 1.0, an alpha parameter of 0.8 and a run-time length correction of 1.0.
ip-10-0-0-80.ec2.internal 2017-04-09 19:55:12,620 scaler WARNING toil.provisioners.clusterScaler: Historical avg. runtime (3600) is less than current avg. runtime (4518.77800202) and cluster is being well utilised (2 running jobs), increasing cluster requirement by: 1.25521611167
```
=> Logging: avoid repetitive messages at maxNodes

src/toil/jobStores/abstractJobStore.py
Didn't create an issue for this. Hopefully that's OK for such a trivial change. Somewhat related to #1453.
=> Return an integer rather than string size for HTTP imports

docker/Dockerfile.py
1.0.1 fixes a [pretty critical bug in Mesos](https://issues.apache.org/jira/browse/MESOS-5943) which causes the scheduler to occasionally crash when it receives enough task status updates at once that a read chunk ends in the middle of a request.
This is somewhat relevant to #1629, where I ran into this crash, and #1553, where the "partitions" (really just disconnections) *may* have the same root cause, though I'm not totally sure. It does have a very similar pattern (an random RST from the server after a bunch of large packets get POSTed at once). It doesn't really fix either of those issues in principle, but it might in practice.
This PR doesn't upgrade past the 1.0 series, because beyond that the meaning of the task updates changes slightly. I'm working on proper reconciliation, …
=> Upgrade to Mesos 1.0.1

src/toil/cwl/cwltoil.py
This fixes those issues in `singleMachine` mode, but not when running in LSF (or other batch systems, I imagine).
=> Reuse the previously made Builder (resolves #1540, resolves #1621)

docker/Dockerfile.py
Allows complex javascript manipulations on AWS runs using the appliance.
The nodejs default version in Ubuntu 14.04 is not new enough so uses
the stable nodejs distribution from NodeSource
(https://github.com/nodesource/distributions)
=> CWL: add recent nodejs to Appliance Dockerfile

src/toil/jobStores/abstractJobStore.py, src/toil/leader.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/statsAndLogging.py
This seems to work OK: the workflow that previously deadlocked has restarted fine with these changes.
There is one visible change in the logs: the `---TOIL WORKER OUTPUT LOG---` line is prefixed by the job name now. Not sure if that was intentionally left unprefixed or not.
=> Fix issues with large stats files (fixes #1594, #1595)

src/toil/batchSystems/lsf.py
I'm getting an error `NameError: global name 'os' is not defined` when using cwltoil. This PR should fix this error.
=> Add `import os`

docs/running/running.rst, src/toil/cwl/cwltoil.py
The current toil integration with cwltool allows specification of
inputs into the initial working directory, so this enables this feature.
This is not generalized directory support (#1656 #1459), but does
allow writing inputs to the work directory making cross platform
CWL support for records easier.
=> CWL: Add support for InitalWorkDirRequirement

run_tests.py, src/toil/provisioners/__init__.py, src/toil/provisioners/abstractProvisioner.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/provisioners/clusterScaler.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/utils/toilLaunchCluster.py
This allows worker nodes to be launched along side leader by adding `-w` option to `toil launch-cluster`. To spin up a cluster with 4 workers (not including the leader) run:
`toil launch-cluster CLUSTER_NAME --nodeType=t2.micro --keyPairName foo@example.com  -w 4`
=> Launch workers alongside leader with toil launch-cluster (resolves #1383)

src/toil/lib/docker.py, src/toil/test/lib/dockerTest.py
When passing chains of commands to the docker caller, they are effectively run through something like checked_call(bash -c 'cmd1 | cmd2 | ... | cmdN').  This will only raise an exception if cmdN fails.  Not being able to detect errors in the previous commands in the chain is, from experience, quite dangerous.  We fix that here by telling bash to detect and abort on a failure at any step in the piped chain.
=> Better error checking in piped docker commands

docs/running/running.rst, src/toil/cwl/cwltoil.py
getFile would copy all input files from the jobStore previous due to a
refactoring bug: the `copy` function argument was removed but still
referenced; it picked up the `copy` module and was always true.
This moves to using symlinks to avoid the extra file copy. In doing so
it exposed some new issues, also fixed in this PR:
- Needed to correctly set basename and location in the File objects to
avoid resolving the original Toil name instead of the actual file name.
- We don't support writable InitialWorkDirRequirement in CWL, but still
support the more common readable case.
Fixes #1627
=> CWL: symlink jobStore files instead of copying

src/toil/cwl/cwltoil.py
Use spaces not commas to pass multiple environment variable to preserve
=> Match doc to reality for --preserve-environment

src/toil/batchSystems/mesos/executor.py, src/toil/fileStore.py, src/toil/lib/docker.py, src/toil/resource.py
Long-running tasks e.g. docker pipelines, can be abondoned on the slave nodes
when tasks are killed. Instead kill all processes belonging to the task's process
group. This requires us to make sure a new progress group is created on launching
a pipeline.
Also fixes an issue where docker containers aren't named as expected on launch.
=> When killing tasks, make sure to reap child processes in the process groups

src/toil/provisioners/__init__.py, src/toil/provisioners/abstractProvisioner.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/test/utils/utilsTest.py, src/toil/utils/toilRsyncCluster.py, src/toil/utils/toilSSHCluster.py
* Automated functions (i.e. spinning up a cluster) will skip host key checking
* `ssh-cluster` and `rsync-cluster` will not skip host key checking by default and will prompt the user when encountering a new host. This can by temporarily overridden by the user by passing the `--insecure` flag. (See also: #1505)
=> Strict hostkey checking by default in cluster utils (fixes #1373)

setup.py
Adds relevant `classifier` and `license` fields to `setup.py`.
=> Display license information in `pip show` (fixes #1670)

src/toil/provisioners/aws/awsProvisioner.py, src/toil/utils/toilDestroyCluster.py, src/toil/utils/toilLaunchCluster.py, src/toil/utils/toilRsyncCluster.py, src/toil/utils/toilSSHCluster.py
* In `launch-cluster`, `destroy-cluster`, `ssh-cluster`, and `rsync-cluster`, logging would be erroneously initialized twice, causing some messages to be logged multiple times. 
* In `awsProvisioner.py`, `_terminateNodes` and `_terminateInstances` both logged the instances to be terminated before calling `_terminateIDs`, which logged the same information again.
=> Fixed logging being initialized twice (fixes #1591)

src/toil/common.py
This sets the default address for the Mesos master to the private IP of the node where the workflow is launched. 
Because workflows are always launched from the leader node, the private IP is precisely what we need in 99% of circumstances and thus makes a sensible default.
First commit is the actual change. A second commit will follow that will adjust the tests to make use of the new feature.
=> Set mesosMasterAddress default to private IP (resolves #1664)

src/toil/resource.py, src/toil/test/src/resourceTest.py
As a side-effect now *every* file in the hot-deployed directory or virtualenv is deployed, not just Python files. I'm open to changing that so that the new code still has the old behavior, but I don't know if there's really a good reason to keep the old behavior. Non-python files can be included in virtualenvs, and it's conceivable that those might need to be hot-deployed as well.
=> Fix hot-deployment with python-3-supporting libraries (fixes #1678)

src/toil/common.py, src/toil/jobStores/aws/jobStore.py
Just throwing this out there, not really 100% sure that this is the best solution.
The refresh thread isn't really guaranteed to be scheduled within its 2 minute window, especially given the number of other threads that are running in the leader process. This would remove the refresh thread entirely, and set the ACL of the user script object to `public-read` instead. Unfortunately I can't seem to get a straight answer on the consistency of the PUT object?acl operation. It seems to take effect right away, but I'm not totally sure.
=> Remove "refresh" thread and just set S3 user script ACL to public-read (resolves #1600, #1516)

docs/batchSystem.rst, docs/running/running.rst, src/toil/batchSystems/torque.py, src/toil/common.py, src/toil/test/src/nodeIDTest.py
Proposing two sets of changes. These were caused by not being able to execute `toil-sort-example.py` from the Toil manual on our cluster.
Our cluster:
- runs Torque. The `qsub` job scripts need to use `/bin/sh` instead of `/bin/bash`, otherwise `-V` variables get zapped by BASH profiles sourced when a job starts. This is the same as [this](https://github.com/roryk/ipython-cluster-helper/commit/33c9eb1fdeb5816c87a5c0b685291673ac685cad)
- has a tiny `/tmp` file system on each node (2GB each), and no other local disks that we can use. This is a very common setup on the clusters. Because of that, we need to use a shared FS for all scratch work, including as a `--workDir` when running Toil. This results in workers on different nodes erasing each other's live job directories in a call to …
=> Torque and workDir fixes (resolves #1462, #1628)

src/toil/provisioners/clusterScaler.py
At some point nodesToTerminate changed from being a list of Nodes to a list of (Node, NodeInfo). This line didn't get updated when that changed, which caused a crash of the workflow on any downscaling attempt.
=> Fix autoscaler crash (resolves #1728, #1729)

src/toil/jobStores/fileJobStore.py
CJ;
Thank you for the work on hard links and avoiding file copying. I was testing this and ran into a problem when the input files were symlinks themselves. This resolves those to get it working with these cases as well. Thanks again.
Input files for hard linking into the filestore fail if they contain
relative symlinks in the input, since the hard links contain only
the original symlinks which are no longer valid:
```
$ ln -s base.txt input.txt
$ ls -lh
total 0
-rw-rw-r-- 1 chapmanb chapmanb 0 May 29 05:32 base.txt
lrwxrwxrwx 1 chapmanb chapmanb 8 May 29 05:32 input.txt -> base.txt
$ mkdir store
$ ln input.txt store/output.txt
$ ls -lh store/
total 0
lrwxrwxrwx 2 chapmanb chapmanb 8 May 29 05:32 output.txt -> base.txt
```
Supplement to #1681
=> hard links: resolve inputs with symlinks

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/torque.py
This is a followup on PR #1617.
The child jobs' exit codes were not properly monitored by the leader. Flag differences between pbspro and the oss version are indeed confusing:
`qstat -x` means: XML on OSS version BUT provide exit codes on PBS pro... ¬_¬'''
Also the `qstat` polling 1 second polling is considered excessive by traditional HPC cluster operators, raised it to 10 seconds. 
Thanks to @cket and @hcraT for their invaluable insights on this issue over gitter: https://gitter.im/bd2k-genomics-toil/Lobby?at=5912e6b9ac693c532adb46d1
=> PBSPro (Torque's proprietary version) in addition to OSS's PBS

Makefile, run_tests.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/test/utils/utilsTest.py
This amends the call to `pytest` in run_test.py by adding the option `--timeout=600` which gives any particular test 10 minutes to run. I imagine this may be enough time for all of the tests. If it is not, we can increase the overall timeout by adjusting the option above, or any particularly lengthy tests can be given their own timeout by adding the decorator `@pytest.mark.timeout(XXX)` where `XXX` is some number of seconds.
This passes tests locally, but pytest-timeout may need to be installed on Jenkins for this to work.
=> Add timeout for running pytest (resolves #1735)

docs/contributing/contributing.rst, jenkins.sh, run_tests.py, src/toil/test/__init__.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/test/utils/utilsTest.py
The AWS keyname was hard coded to Jenkins. This PR sets the keyname by an environment variable.
=> Added TOIL_AWS_KEYNAME

src/toil/test/provisioners/aws/awsProvisionerTest.py
This forces the worker to wait before we check for the volume. Since the failure is sporadic, this will be sort of difficult to test. 
The wait function used (from CGCloud) may or may not be sufficient. Another approach is to retry accessing the volume until success. If this first approach doesn't work that will be next.
=> Try waiting for worker before checking volume (resolves #1742)

src/toil/test/__init__.py, src/toil/test/utils/utilsTest.py
Previously if you had an outdated version of rsync installed (<3.0.0, like the one that comes by default with OSX) running the provisioner utils tests would fail.
This PR adds a decorator that checks if the user has rsync installed and makes sure that the version is sufficient, skipping the tests otherwise.
=> Skip provisioner utils test if rsync version is outdated or unavailable (resolves #1725)

src/toil/test/provisioners/aws/awsProvisionerTest.py
credit to fix from @joelarmstrong [here](https://github.com/BD2KGenomics/toil/pull/1743#issuecomment-314181619).
Hopefully this should fix #1742 for good.
=> Update worker instance before checking block_device_mapping (resolves #1742)

src/toil/cwl/cwltoil.py
fix failure in resolve_indirect_inner in cwltoil.py for Workflow if substep is a workflow and some inputs are optional and empty. see #1761
=> fix failure in resolve_indirect_inner in cwltoil.py (resolves #1761)

src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/azureJobStore.py, src/toil/test/jobStores/jobStoreTest.py
The old version didn't create an empty file. This also adds a test to
ensure it works with other job stores.
=> Fix getEmptyFileStoreID on AWS and Azure JobStores (resolves #1705)

src/toil/batchSystems/options.py, src/toil/common.py, src/toil/jobStores/fileJobStore.py, src/toil/test/sort/sortTest.py, src/toil/test/src/jobFileStoreTest.py
Previously when using importFile function hard-links were made if possible in the fileJobStore. Caching code changes permissions of the imported file to read-only which can have unexpected results. 
This PR changes importFile to copy by default instead. It also add a command line option `--linkImports` which will cause linking if desired. The help message explains the permissions side affect.
Also I did a few minor style changes in nearby areas.
=> Add option to link files when importing into fileJobStore (resolves #1755)

src/toil/test/__init__.py
Docker on mac requires whitelisting directories before mounting them into docker images. Temp files are created in `/var/folders/...`. `/var` is a symlink to `/var/private`. `/private` is in the whitelist, but since the canonical name is not being used docker doesn't recognize it.
The workaround of adding `/var/folders` fails because the GUI will only select the canonical name (`/private/var/folders`) and because `/private` is already on the list the change is rejected.
resolves #1778
=> Fix docker tests failing on mac. resolves #1778

src/toil/resource.py
Hello! Thanks for the great software. I'm working on a workflow interface to @jupyter, and toil is seeming like the best option for a workflow engine so far, especially once Python 3 is supported. Obviously, interactivity will be very useful.
Please excuse my ignorance of the code base, and feel free to suggest any improvements. I'd be happy to be helpful however is best.
Anyways, here's my quick solution:
Presently, trying to copy and paste [HelloWorld.py](https://toil.readthedocs.io/en/latest/running/running.html) into an IPython interpreter results in `'module' object has no attribute '__file__'` as described in #673.
From my quick investigation, this seems to be because when running jobs on workers, toil collects information about any packages which have been imported, and distributes …
=> Quick fix for running toil from IPython

src/toil/batchSystems/lsfHelper.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/options.py, src/toil/batchSystems/parasol.py, src/toil/common.py, src/toil/jobStores/abstractJobStore.py, src/toil/leader.py, src/toil/lib/encryption/__init__.py, src/toil/provisioners/clusterScaler.py, src/toil/test/__init__.py, src/toil/test/cwl/cwlTest.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/provisioners/clusterScalerTest.py, src/toil/test/src/jobServiceTest.py, src/toil/test/src/multipartTransferTest.py, src/toil/test/src/regularLogTest.py
In the plan to get to python2/3 compat, this is the first step.
I ran `futurize -1 -w src` and fixed a few things up.
The only thing that might be controversial is that I deleted some doctests in `src/toil/test/__init__.py`. Python's api changed here in a problematic way and I don't fully understand what the code is supposed to do. So I suggest removing and if there's a compelling reason to add it back.
=> futurize stage 1 resolves #1784

src/toil/cwl/cwltoil.py
Check for presence of an existing file before deciding on upload into
the fileStore. This prevents double uploading an identical file shared
across multiple sample, which would trigger a later export issue when
we try to write two identical files with different fileStoreIDs to a
work directory. This fixes a bug introduced in the symlink changes
(a1d574ade864342f82045cd53217b09a3eccc219).
=> CWL: avoid importing existing files into fileStore

Makefile, docs/contributing/contributing.rst, run_tests.py, src/toil/test/__init__.py
This PR adds two new targets to the makefile for testing locally:
- `test_offline` and
- `integration_test_local`.
The `test_offline` target gives a cleaner interface to run unit tests without running the docker/appliance tests. Previously, one had to set the environment variable `TOIL_DOCKER_REGISTRY` to the empty string and _then_ run `make test`. Now, one can simply run `make test_offline` and get the results that they expect. Help messages were changed to clarify the new process. Name taken from 
The `integration_test_local` target now runs in series and output is not captured. This can still use some improvement however because running all of the tests in series takes a looong time and produces a _lot_ of output.
Other changes:
- target that are _only_ designed to be run on Jenkins …
=> Add local testing targets (resolves #1741)

src/toil/provisioners/aws/__init__.py, src/toil/provisioners/aws/awsProvisioner.py
This is a fix for #1814, where nodes with > 4 ephemeral drives, such as i2.8xlarge, are not supported.  
There is probably a more elegant/future-proof fix to be made here, but this at least works for the node type in question for the time being.
=> Extend bdtKeys to support more ephemeral drives

Makefile
This retries the push 5 times, to avoid timeouts killing our integration tests.
=> Retry `docker push` 5 times (resolves #1821)

src/toil/jobGraph.py, src/toil/jobStores/abstractJobStore.py, src/toil/leader.py, src/toil/test/src/checkpointTest.py, src/toil/worker.py
Hopefully this gives us some relief from the flaky tests.
This arose because of the recent checkpoint fixes. Unfortunately updating the state of the jobGraphs from the leader caused issues in some cases: for a job that launches services, the leader sets `jobGraph.services` to an empty list as a leader-specific signal that its services have been launched. This is out-of-sync with how it should appear in the jobStore. Crucially, this means that the job state can't ever be updated from the leader. If the jobGraph's services list gets cleared in the jobStore while the services are running, then those services will be orphaned and can't be cleared on checkpoint restart. If the orphaned services then become totally failed, and then the workflow ultimately completes (because a checkpointed …
=> Fix flaky JobService tests (resolves #1819)

src/toil/batchSystems/gridengine.py
Split was causing white character to return such that casting to int was returning an error.
=> Removed split

src/toil/batchSystems/registry.py
There was a typo in the import statement that I corrected. Should be GridEngine not Gridengine.
=> GridEngine not Gridengine

src/toil/lib/bioio.py
The default default of None for some of the options with a dest of
"logLevel" was overriding the explicitly set default. Adding
an explicit default to all of them solves the problem.
Also restores functionality of the --logOff option which didn't
work.
Fixes #1316 by having a non-None logLevel for --realTimeLogging to
use.
=> Stop log level option defaults from clobbering each other (resolves #1316)

Makefile, docs/contributing/contributing.rst, src/toil/test/__init__.py
This adds a section describing what steps are necessary to run tests using pytest (this includes setting TEST_INTEGRATIVE for integration tests).
This also fixes the outdated reference to test_local (should be test_offline).
There are also miscellaneous fixes (minor reorganization, better error message, etc.)
=> Update testing docs (resolves #1841, #1848)

src/toil/job.py, src/toil/test/src/jobEncapsulationTest.py
Resolves #1643. Calling `job.addChild().encapsulate` would create two parents. This PR uses the code suggested in #1643 and adds a test to confirm that only one parent exists.
=> Fixed `job.addChild().encapsulate`

src/toil/jobStores/aws/utils.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/src/fileStoreTest.py
This should address these two rare test failures:
- http://jenkins.cgcloud.info/job/toil-pull-requests/3214/testReport/junit/src.toil.test.jobStores.jobStoreTest/AWSJobStoreTest/testSDBDomainsDeletedOnFailedJobstoreBucketCreation/
- http://jenkins.cgcloud.info/job/toil-pull-requests/3213/testReport/junit/src.toil.test.src.fileStoreTest/CachingFileStoreTestWithAzureJobStore/testAsyncWriteWithCaching/
=> Fix flaky AWS and cache tests

src/toil/cwl/cwltoil.py
Places the output directories into work directory with other
temporary work files to avoid clutter and improve ability
to easily clean up.
https://github.com/BD2KGenomics/toil/issues/1865#issuecomment-328303879
=> CWL: move tmp_outdir_prefix to work directory

src/toil/job.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/azureJobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/jobStores/googleJobStore.py, src/toil/test/jobStores/jobStoreTest.py
Create SDB items representing the job graph with a batch insertion, to avoid large numbers of transactions when there are many child jobs.
=> Allow batch creation of jobs

src/toil/jobStores/utils.py, src/toil/test/jobStores/jobStoreTest.py
This should also fix the problem for jobStores other than AWS, but I haven't tested it on anything else yet. I added a unit test to catch this error in all jobStores, so if the tests pass everything should be OK.
The basic idea is to always close the file on exit in the reader thread, which wakes the writer up and causes an exception in its thread. Thanks to @diekhans for the suggestion.
=> Fix AWS readFileStream deadlock on partial reads (resolves #1748)

src/toil/batchSystems/options.py, src/toil/realtimeLogger.py, src/toil/test/jobStores/jobStoreTest.py
The old method (relying on the FQDN resolving correctly) crashed Toil
on some OSes (depending on your DNS server).
Fixes #1877, #1858.
=> Use a socket to get the public-facing IP (resolves #1877, #1858)

src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/cwl/cwltoil.py, src/toil/leader.py
The cwltoil integration includes non-processing based internal
jobs that handle dispatching and managing workflows. When running on a
cluster these jobs were being submitted to the scheduler. The larger
number of short submissions make busy schedulers unhappy and slow down
the runs.
This introduces a local batch queue along with the cluster submission
queue. Internal CWL jobs go to this, getting run locally instead of on
the cluster. It's a general fix that should apply across all of the
supported batch systems (SGE, Slurm, Torque, PBSPro).
Closes #1783
=> CWL: run internal jobs locally, not on cluster

src/toil/leader.py
I've tried my best to test this with both the CWL extra installed and not installed, and it seems to work OK.
=> Fix leader crash when `cwl` extra isn't installed (resolves #1880)

docs/appendices/environment_vars.rst, docs/contributing/contributing.rst, jenkins.sh, src/toil/jobStores/googleJobStore.py, src/toil/test/__init__.py, src/toil/test/batchSystems/batchSystemTest.py, src/toil/test/cwl/cwlTest.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/lib/dockerTest.py, src/toil/test/mesos/MesosDataStructuresTest.py, src/toil/test/mesos/mesosTest.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/test/provisioners/clusterScalerTest.py, src/toil/test/sort/sortTest.py, src/toil/test/src/checkpointTest.py, src/toil/test/src/fileStoreTest.py, src/toil/test/src/hotDeploymentTest.py, src/toil/test/src/importExportFileTest.py, src/toil/test/src/jobFileStoreTest.py, src/toil/test/src/jobServiceTest.py, src/toil/test/src/jobTest.py, src/toil/test/src/miscTests.py, src/toil/test/src/multipartTransferTest.py, src/toil/test/src/promisedRequirementTest.py, src/toil/test/src/regularLogTest.py, src/toil/test/src/restartDAGTest.py, src/toil/test/src/resumabilityTest.py, src/toil/test/src/toilContextManagerTest.py, src/toil/test/src/userDefinedJobArgTypeTest.py, src/toil/test/utils/utilsTest.py
If TOIL_TEST_QUICK=True, all tests with the 'slow' decorator will be skipped. Quick, in this case, is 15 minutes on my laptop.
Any critical tests that are not too long could be added back in.
=> Skip slow tests (resolves #1826).

src/toil/leader.py, src/toil/worker.py
This should make it easier to see what's happening on a node when using `ps` and similar tools. A typical `ps aux` line now looks like this:
```
joel     32119 60.5  0.4 566948 67128 pts/2    Sl+  19:20   0:43 /home/joel/toil-fresh/venv/bin/python /home/joel/toil-fresh/venv/bin/_toil_worker _forceModifyCacheLockFile file:/tmp/toil-test-toil.test.src.fileStoreTest.CachingFileStoreTestWithFileJobStore-testAsyncWriteWithCaching-jobstore-5zRacP H/L/jobLfK9ai
```
which is a little noisy, but the `_forceModifyCacheLockFile` is the name of the job being run.
This also tweaks leader.py to import JobNode from where it's defined, in job.py, rather than from jobGraph.py where it happens to be imported.
=> Put jobName into the _toil_worker arguments (resolves #1884)

src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/torque.py, src/toil/common.py
Improves support for configuring interval to query schedulers. This
builds off #1769 which blocked to avoid extra queries. Unfortunately
this also blocks submissions of jobs, making it hard to scale up
analyses. This change uses caching instead of blocking, so Toil can
continue to submit and monitor jobs and will refresh queries to the
scheduler only within the `statePollingWait` period. The behavior when
`statePollingWait` is unset does not change.
=> Batch: cache instead of block for statePollingWait

src/toil/batchSystems/parasol.py, src/toil/batchSystems/parasolTestSupport.py
This should hopefully make Parasol usable on the master branch, so that we don't have to keep up our toil fork on juggernaut/kolossus. I've tested it out, and the memory requirements seem to be enforced correctly, which I know was a worry before.
- Didn't parse jobStore path correctly: it now does, and fails early
if using anything but the FileJobStore
- The previous version attempted to remove jobs that it didn't launch.
=> Fix bugs in the Parasol batch system

src/toil/common.py
This fixes a defect in the dynamic batch system feature whereby the new batch system options were not added to the Config object. This would lead to errors like:
```
cwltoil --jobNamePrefix myjob [etc]
...
AttributeError: 'Config' object has no attribute 'jobNamePrefix'
```
=> Dynamic batch systems are not actually created

docker/Dockerfile.py
The newest schema-salad version contains python_version requirements
that the older setuptools versions don't know how to parse. These new requirements would cause the Toil appliance build to break from today onwards otherwise.
Fixes #1907.
=> Update setuptools and pip versions within appliance build

docker/Dockerfile.py, src/toil/common.py, src/toil/jobStores/abstractJobStore.py, src/toil/leader.py, src/toil/test/sort/sortTest.py, src/toil/test/src/toilContextManagerTest.py, src/toil/test/utils/utilsTest.py
Previously, if your workflow completed successfully but a single `toil.exportFile` call failed, the entire effort would be wasted, because there was no way of running the export steps again (the workflow would crash if restarted).
This PR allows a "restart" if the workflow is nominally completed and the jobStore hasn't been deleted. No Job work will be done on this type of "restart", just export steps and other main-method work.
=> Fix workflow effort being wasted if a single export fails (fixes #1319)

src/toil/common.py, src/toil/provisioners/clusterScaler.py, src/toil/test/provisioners/clusterScalerTest.py
I set the default value to 10. If this list is shorter than the nodeTypes list, the first value is used as default for missing values.
=> Added default value for maxNodes (resolves #1913)

Makefile, docker/Dockerfile.py, docs/developingWorkflows/developing.rst, setup.py, src/toil/lib/docker.py, src/toil/test/lib/dockerTest.py
Addresses #1851
Hopefully this addresses the backwards compatibility issues with previous dockerCall usage.  I reworked a few things, and wanted to ask about the old bash command structure.  The name too, docker.py, was changed because it conflicts with "import docker" from the python docker API.  I also changed the "defer" variable because it interfered with the defer() function within toil.
This PR makes use of docker's powerful python API (including an exception that detects if a docker image exists) and the documentation they've cheerfully provided here: http://docker-py.readthedocs.io/en/stable/containers.html
This PR is also a necessary step towards increasing our docker functionality in preparation for running WDL workflows using docker.
=> dockerCall function changed to use docker API. (resolves #1851)

src/toil/lib/docker.py, src/toil/test/lib/dockerTest.py
dockerCall() and dockerCheckOutput() now default to using subprocess.check_output() under the old functionality.  This should enable full backwards compatibility.  To use the new docker API wrapper, use apiDockerCall().
=> Fixed dockerCall backwards compatibility issues.

src/toil/lib/ec2.py
Instances added:
-  t2.nano
-  t2.xlarge
-  t2.2xlarge
-  m4.16xlarge
-  r4.large
-  r4.xlarge
-  r4.2xlarge
-  r4.4xlarge
-  r4.8xlarge
-  r4.16xlarge
-  p2.xlarge
-  p2.8xlarge
-  p2.16xlarge
-  g3.4xlarge
-  g3.8xlarge
-  g3.16xlarge
-  g2.8xlarge
-  x1.16xlarge
-  x1.32xlarge
-  x1e.32xlarge
-  i3.large
-  i3.xlarge
-  i3.2xlarge
-  i3.4xlarge
-  i3.8xlarge
-  i3.16xlarge
Not added:
- f1.2xlarge
- f1.16xlarge
because these are FPGA instances and didn't seem applicable. If I'm wrong, let me know.
=> Update ec2 instance list (resolves #1893)

src/toil/batchSystems/options.py, src/toil/common.py, src/toil/fileStore.py, src/toil/jobStores/fileJobStore.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/provisioners/clusterScalerTest.py
RULE: If Toil did not create the file, Toil will not change permissions.
=> Define fileStore semantics (resolves #1887, #1903)

src/toil/lib/docker.py, src/toil/test/lib/dockerTest.py
Just allow "job" to be accepted as an *arg.  Addresses an issue with the subprocessDockerCall() that toil-vg uses.
=> Modify subprocessDockerCall to address 1959.

src/toil/provisioners/aws/awsProvisioner.py
The Toil provisioner uses `ssh -t` to issue commands, which forces the allocation of a
TTY. When checking that dockerd is running, it issues a `ps aux` and
searches for dockerd in the output. But when run inside a TTY, ps
truncates the output to the width of the terminal. If you used the
default terminal width, 80, and were particularly unlucky with what
date/PID/RSS you had, you could get an output line for the dockerd process
that looks like this:
```
root      1002  8.3  1.8 816052 73688 ?        Ssl  18:37   0:30 /run/torcx/bin
```
which actually doesn't contain the string "dockerd" at all.
This patch just forces ps to never truncate.
=> Fix launch-cluster breaking if your terminal window isn't extra-wide

setup.py, src/toil/cwl/cwltoil.py
* Run "#main" resolved object by default
* sort globs according to POSIX
* reduce loading time for packed documents
=> get latest fixes from cwltool

src/toil/test/src/jobFileStoreTest.py
iNode check done by this test doesn't apply to the symbolic tests used now
=> Remove testImportLinking (closes #1998)

src/toil/job.py
When using `Job.Runner.getDefaultArgumentParser` method, default values aren't displayed with `--help`.
This pull request adds  [ArgumentDefaultsHelpFormatter](https://docs.python.org/3/library/argparse.html#formatter-class) as `formatter_class` in `Job.Runner.getDefaultArgumentParser`.
See https://stackoverflow.com/questions/12151306.
=> show default values in --help

docs/index.rst
This just adds an explicit reference to the toil citation to the beginning of the toil docs in addition to the paper link.  Hopefully this induces more people to cite toil:
Vivian, J., Rao, A. A., Nothaft, F. A., Ketchum, C., Armstrong, J., Novak, A., … Paten, B. (2017). Toil enables reproducible, open source, big biomedical data analyses. Nature Biotechnology, 35(4), 314–316. http://doi.org/10.1038/nbt.3772
=> Add citation.  (#2010)

src/toil/cwl/cwltoil.py
https://github.com/common-workflow-language/cwltool/#use-with-boot2docker
=> --tmp-outdir-prefix for toil-cwl-runner with OS X & docker

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/lsf.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/parasol.py, src/toil/batchSystems/singleMachine.py, src/toil/test/batchSystems/batchSystemTest.py
enhances CWL execution on Mesos, AbstractGrinEngine, and other BatchSystemSupport
based backends
Fixes non-thread safe job ID increment on Mesos
Removes unused getRescueBatchJobFrequency() methods
=> move local job queue up into BatchSystemLocalSupport

src/toil/batchSystems/lsf.py, src/toil/batchSystems/lsfHelper.py
In the default LSF configuration `mem` in `-R` and `-M` are in different units, so we can't reuse the same value for both.
=> LSF: Separately determine memory reservation and memory limit values.

docs/gettingStarted/install.rst, setup.py
Allows toil to be built from source using just: `make develop extras=[all]` so that I don't have to copy-paste all of the time when building from source.  Also relocates a global variable.
=> Add [all] extra.

src/toil/common.py, src/toil/test/src/miscTests.py
Addresses #2017.
Should be faster (sometimes much faster) and won't skip 'root' protected directories, erroneously telling you it's 0 size.  Also, doesn't break on broken symlinks.  Should work on Apple things too.
=> Changed getDirSizeRecursively to use du.

jenkins.sh, setup.py, src/toil/batchSystems/htcondor.py, src/toil/batchSystems/registry.py, src/toil/test/__init__.py, src/toil/test/batchSystems/batchSystemTest.py
Current version works with HTCondor pools that use a shared file system (this includes, for example, a personal HTCondor pool on a single machine). Future versions will work with distributed HTCondor pools.
Requires the HTCondor Python bindings, which are either installed by the system package manager as part of a HTCondor install or can be installed separately via `pip install htcondor`.
Passes tests in `src/toil/test/batchSystems/batchSystemTest.py` when tested on a machine with a personal HTCondor pool.
To do to make this plugin more complete (will open issue): 
1. Transfer local file stores to the execute nodes.
2. Check pool resources.
3. Support running in the Open Science Grid.
=> Add HTCondor batch system

src/toil/jobStores/fileJobStore.py
I set a rather large buffer size (1Gb) after doing some speed tests.  I also made it so that it uses the original method (loads the entire file into memory) if the file is smaller than 1Gb.
=> Add buffering for large files in fileJobStore.  Addresses #1983.

src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/gridengine.py, src/toil/batchSystems/slurm.py, src/toil/batchSystems/torque.py
NB: I haven't actually tested this yet, this is just from going through visually so I may have added stupid syntax errors. I should have some time to test this tomorrow.
This fixes #2030 as well as a related race in Torque, and a similar race when jobs are killed (which pretty much never happens, so is less serious).
NB: I only looked at data that could simultaneously be written to and read from the leader and batch system worker thread as written (simultaneous read/read should be fine, e.g. https://github.com/BD2KGenomics/toil/blob/b9b6ca1c519dfc18e355cae2a4eea9753480745a/src/toil/batchSystems/abstractGridEngineBatchSystem.py#L190 which could be read in the worker while the leader also reads). So if later modifications to the leader or worker (or others) start calling new methods, they …
=> Fix GridEngine/Torque race(s)

docs/gettingStarted/quickStart.rst
To clarify the documentation about running the Cactus Workflow on AWS with autoscaling.
=> Improve cactus quickstart instructions

docs/gettingStarted/install.rst, docs/gettingStarted/quickStart.rst, docs/running/amazon.rst, docs/running/wdl.rst, setup.py
We sat down with Brian to "kick the tires" on WDL and he had some suggestions for the docs.  This PR addresses some of those issues:
- Add wdl to extras with comments (no dependencies as of now).
- Add a wdl helloworld example to the quickstart.
- Warn the user to use destroy-cluster at the start of the autoscaling scripts in the quickstart rather than relying on them to see it in the final step.
- Change the CWL AWS example to use a t2.medium instead of a t2.micro.
- Change the AWS sort.py example to use a t2.medium instead of a t2.micro.
=> Doc changes.

src/toil/provisioners/aws/__init__.py, src/toil/provisioners/aws/awsProvisioner.py
NB: this requires a Container Linux version upgrade as well. The (very) old version currently used by toil has a kernel that fails to recognize more than one NVMe drive.
I haven't tested this Container Linux version extensively with this version of toil. On my fork (which may use a different docker client version), the stable branch works great, though, so this shouldn't introduce major problems.
=> Support NVMe ephemeral drives (e.g. the i3 series) (resolves #2057)

src/toil/batchSystems/options.py, src/toil/common.py, src/toil/cwl/cwltoil.py
https://github.com/BD2KGenomics/toil/pull/2050 was wrong, so here's a better PR
It adds the ability to have `toil-cwl-runner` specific help text and options. Here I've skipped the service workers related options and added a `--noLinkImports`; both only for `toil-cwl-runner`
=> make CWL specific options

src/toil/provisioners/aws/awsProvisioner.py
This is a continuation of #2061. 
It should fix a few different kinds of AWS errors.
- Adding tags would fail with `EC2ResponseError: EC2ResponseError: 400 Bad Request` [example](http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/1950/testReport/junit/src.toil.test.provisioners.aws.awsProvisionerTest/AWSAutoscaleTestMultipleNodeTypes/testAutoScale/)
This is fixed in 6682bac then refactored in 7659c0b
- Counting workers would fail with assertion error. [example](http://jenkins.cgcloud.info/job/toil-pull-request-integration-tests/1955/testReport/junit/src.toil.test.provisioners.aws.awsProvisionerTest/AWSStaticAutoscaleTest/testSpotAutoScale/)
This is fixed in e01298a
This PR also contains a refactor of the AWS retry mechanism 7659c0b. Now there is a decorator `@awsRetry` …
=> Fix some flaky AWS tests (resolves #1840)

src/toil/jobStores/azureJobStore.py
Addresses #2079.
Should avoid a vulnerability pointed out thanks to James Davis over at Virginia Tech.
=> Replace regex pattern in AzureJobStore to avoid backtracking.  Addresses #2079.

src/toil/utils/toilMain.py, src/toil/utils/toilStatus.py
Addresses #2081.
Currently if one pip installs toil and runs the command `toil --help`, toil breaks.  This PR fixes this.
=> Fixes broken help menu.  Addresses #2081.

version_template.py
Skips git commit hash versioning if not in a git environment.
=> Enable pip install from tarball (closes #2060).

src/toil/batchSystems/slurm.py
Reverts BD2KGenomics/toil#1950.
A bug occurred and this will be reverted.
=> Revert "issue1929/correction_slurm.py"

attic/toil-sort-example.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/test/provisioners/gceProvisionerTest.py, src/toil/test/sort/sort.py
Changes the amount of memory that the sort example requires. I want to see if this fixes our flaky tests in the short term (though resource allocation in the long term should be reworked because this seems like a symptom of a different problem).
=> Fix flaky tests by lowering sort.py memory requirements.

docs/developingWorkflows/developing.rst, src/toil/job.py
Partially address #1764.
Change tutorial examples in the docs that use deprecated code (`startToil()`) to reflect currently supported methods (`toil.start()`).
=> Updates deprecated startToil() use in doc tutorials. Partially addresses #1764.

src/toil/batchSystems/lsf.py
Discovered with @joelarmstrong when running cactus, which wanted Toil to allocate 0.1 cores
=> bugfix: LSF only supports integers for the number of cores

src/toil/common.py, src/toil/test/src/workerTest.py, src/toil/worker.py
Also refactors worker logic slightly.
This *shouldn't* break the resumability of jobstores that were started before these changes, but I haven't tested that. I have tested that resuming a workflow with/without --disableChaining seems to work as expected (it flips on/off properly, unlike options like --writeLogs).
=> Add --disableChaining option (resolves #1698)

src/toil/provisioners/gceProvisioner.py, src/toil/test/provisioners/gceProvisionerTest.py
* Some tests were timing out too early.
* Some nodes were in a stopped state. Changed getProvisionedWorkers to only return running nodes.
* Implemented the preemptable option for getProvsionedWorkers
=> GCE fixes - closes #2096

src/toil/provisioners/aws/awsProvisioner.py
Addresses #2140.
`logging.getLogger("boto").setLevel(logging.WARNING)` was added and now it's spamming confusing error messages to the terminal.  This should suppress it enough that it doesn't flood the terminal with errors (which seem to be benign) each time a user launches a cluster.
=> Suppress boto logs.  Addresses #2140.

Makefile, docs/appendices/deploy.rst, docs/developingWorkflows/developing.rst, docs/running/cliOptions.rst, docs/running/cloud/amazon.rst, src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/options.py, src/toil/batchSystems/parasol.py, src/toil/batchSystems/singleMachine.py, src/toil/common.py, src/toil/resource.py, src/toil/test/src/autoDeploymentTest.py, src/toil/test/src/hotDeploymentTest.py, src/toil/test/src/resourceTest.py
Addresses #2089.
There was confusion over hot, remote, and now the chosen one, "auto-deployment".  Hopefully this resolves these mentions throughout the code.
=> Change to "auto-deployment".  Addresses #2089.

docker/Dockerfile.py
Previous message upon a successful toil ssh-cluster <cluster-name> stated that the user entered a toil appliance, which 'could only run scripts in single-machine mode.'
Addresses: #2147.
=> modify message upon successful ssh-cluster <cluster-name>

setup.py
Addresses #1935.
Affects python 2/3 compatibility.  PyCrypto is also no longer maintained.  Saw this when looking into our SSE keys.
=> Update pycrypto to pycryptodome.  Addresses #1935.

setup.py, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
This PR addresses two failing CWL conformance tests:
"Test that no MultipleInputFeatureRequirement is necessary when..."
and
"Test valueFrom with constant value overriding provided array inputs"
The test in issue #2161 is not failing when run locally.
=> Fix new CWL conformance test problems (closes #2161).

setup.py
This makes Toil consistent with the documentation, which specifies that Toil currently only supports Python 2.7.
=> Fail installation if not running Python2.7 (#2145)

src/toil/lib/docker.py
Otherwise there's no way to check the exit code or wait on the container.
This should fix https://github.com/vgteam/toil-vg/issues/475
=> Make sure apiDockerCall returns the container when detatching

src/toil/jobStores/fileJobStore.py, src/toil/test/cwl/cwlTest.py
Addresses #2181 .
CWL conformance tests have been timing out towards the end, and seem to work locally.  This is likely due to recently updating these tests, and so I've increased the timeout by another 5 minutes.
Cloud tests have been randomly failing among all three clouds it seems, also (most commonly) with timeouts, and this is likely due to #2157.  I've reverted back to the standard method for removing directories before trying the potentially time consuming custom deletion function written to address mostly nfs specific issues.
=> Fix failing flaky tests.  Addresses #2181.

src/toil/common.py, src/toil/job.py, src/toil/jobStores/abstractJobStore.py, src/toil/worker.py
This is relevant to earlier issues like #1503. The root cause is that cPickle sometimes doesn't release the GIL when reading. When reading using the `read_file` function, cPickle correctly releases the GIL before performing a potentially-blocking operation:
https://github.com/python/cpython/blob/a61f5da54772b0ea6a7eccf21df08e61585ef712/Modules/cPickle.c#L552
But in the `readline_file` function, it doesn't:
https://github.com/python/cpython/blob/a61f5da54772b0ea6a7eccf21df08e61585ef712/Modules/cPickle.c#L591
This means that anytime the "file-like-object" that cPickle is reading from is a pipe filled from a different Python thread (i.e. in remote jobStores), we have to avoid using `readline_file` at all costs. Otherwise, the unpickling thread will stall waiting for data, but the thread that …
=> Fix cPickle deadlock when unpickling Job objects

src/toil/common.py, src/toil/fileStore.py, src/toil/job.py, src/toil/leader.py, src/toil/lib/humanize.py, src/toil/provisioners/abstractProvisioner.py, src/toil/provisioners/clusterScaler.py, src/toil/test/batchSystems/batchSystemTest.py, src/toil/test/provisioners/clusterScalerTest.py
This is a slight refactoring and retouching of the autoscaler. This fixes several bugs, some of which are blockers for certain niche use-cases. Notably:
- Services weren't being treated specially by the autoscaler. Services are one case where the degree of parallelization really, really matters. If you have multiple services, they may all need to be running simultaneously before any real work can be done. Previously, if your services had a fairly short runtime, the autoscaler would believe that it could pack them serially, one after the other. This would lead to service deadlocks in some situations.
- New node reservations (reservations are sort of like "time-slices" of resource usage at a node, so you can find the projected resource usage at each point in time) weren't split, meaning …
=> Autoscaler revamp

src/toil/test/batchSystems/batchSystemTest.py
Addresses #2219.
Should fix some flakiness in two tests.
=> Extend sleep on measureConcurrency.  Addresses #2219.

src/toil/provisioners/abstractProvisioner.py, src/toil/provisioners/clusterScaler.py, src/toil/test/provisioners/clusterScalerTest.py
Also some miscellaneous crap to add a `__repr__` to Shape and ensure throttling still works if an exception is raised inside the scaler loop body.
=> Fix a crash if job is larger than all available node types (resolves #2237)

src/toil/__init__.py
Right now, if you give a non-working Docker container specifier as TOIL_APPLIANCE_SELF, you get no feedback. This adds code to show you the manifest URL that didn't work and the HTTP status code that describes the problem (for example, 401 if you forgot to make your Quay repo public).
=> Report why a Docker manifest might be unavailable

src/toil/provisioners/node.py
I could've sworn I fixed this before, but here is a fix for a thorny issue: whether `toil launch-cluster` succeeds depends on the width of your terminal. Worse yet, it fails if your terminal is the standard size of 80x24. (Your mileage may vary, because the length of ps output may depend on the size of the PIDs, etc.)
The core problem is that toil is using `ps aux` to try to find the dockerd entry, which looks something like this:
```
root       953 37.7  3.3 729624 68156 ?        Ssl  02:06   0:12 /run/torcx/bin/dockerd blah blah blah
```
But `ps` truncates its output to the size of the terminal by default. If your window is 80 characters, for example, you get:
```
root       953 37.7  3.3 729624 68156 ?        Ssl  02:06   0:12 /run/torcx/bin/
```
The terminal size is forwarded through …
=> Fix docker daemon detection depending on terminal size

src/toil/provisioners/abstractProvisioner.py
c5, i3.metal, c5d, m5, and m5d instances all have their EBS volumes
show up as NVMe devices. Previously toil assumed that all NVMe devices
were ephemeral, so it formed a RAID device from them. On these
instance types, though, the root volume would be reformatted,
corrupted, and then remounted as readonly, causing failures.
=> Avoid overwriting NVMe root volumes on current-gen AWS instances (addresses #2252)

src/toil/test/cwl/cwlTest.py
Addresses #2181.
Extends the cwl conformance tests we run from the default 900 seconds to 1800 seconds.  It also reverts the cwl confromance test to the code it contained previously, except for this small addition.
Also, I hope I'm not abusing the `TEST_N` variable here @mr-c .
=> Extend cwltest (conformance run) timeout to 1800 seconds.  Addresses #2181.

src/toil/provisioners/clusterScaler.py, src/toil/test/provisioners/clusterScalerTest.py
Fixes #2256. Adds a unit test which covers this, but more importantly that unignoring actually happens as it should.
=> Don't call addNodes if the delta was met by unignoring nodes

docs/running/cwl.rst, docs/running/wdl.rst
Addresses #2260. Provides examples of executing CWL and WDL workflows from a Toil script.
=> Add examples of running prexisting workflows with Toil scripts.

src/toil/provisioners/aws/awsProvisioner.py
At end of function that creates the cluster security group, there is
some logic that loops through the EC2 security groups to find the
one that is named for the cluster, and also is in the specified VPC,
if a VPC was specified. The security group is then returned and
applied to the EC2 instance in the calling function. The logic
however, was not correct, and results in getting all the security
groups. Usually this is not an issue, but if there are a lot of
security groups, this can be a problem with AWS limits on the
number of security groups per EC2 instance or network interface.
(resolves #1714)
=> Simple change to logic to correctly filter AWS security groups

src/toil/worker.py
This has been driving me freaking batty.
The previous behavior caused messages like this:
```
DEBUG:toil.jobStores.fileJobStore:Path to job store directory is '/Users/joel/cactus/jobStore'.
```
to be printed once per job run, regardless of log level setting. This was especially frustrating in single-machine mode, where these end up being output hundreds of times, crowding out any useful output.
The issue turned out to be that `toil/test/__init__.py` tries to run `logging.basicConfig()` hardcoded with level `DEBUG`, and something in `worker.py` was transitively importing `runningOnEC2` from a module under `toil.test`. Ensuring that `logging.basicConfig()` is run much earlier in the imports in worker.py fixes the problem. (Or we could remove the hardcoded `DEBUG` config from `toil.test`, …
=> Stop FileJobStore DEBUG messages from sneaking out once for every job

src/toil/cwl/cwltoil.py
Addresses #2311.
This PR exposes the `--force-docker-pull` option within Toil.
=> Expose force_docker_pull option in cwltoil.  Addresses #2311.

docs/running/introduction.rst
Also, haven't tested this, but is
```
gce:us-west2-2a:my-google-jobstore-name
```
still the correct format for specifying Google Cloud Storage buckets?
=> Fix mixing up S3 with Google Cloud Storage in docs

docs/developingWorkflows/developing.rst, docs/developingWorkflows/toilAPIFilestore.rst, src/toil/fileStore.py, src/toil/jobStores/abstractJobStore.py
It was pointed out that there was no documentation around accessing the size of a file stored in a jobstore. There was a little blurb about FileID's in general in the "Developing Workflows" section but I can see how it could be improved. This PR adds the FileID class to the "Filestore API" section as well as a link between this and the previously mentioned blurb. @adamnovak @joelarmstrong did you miss the blurb or not feel it was a sufficient description? Let me know if you have any feedback that I can use to improve this documentation.
=> Improve documentation around fileID (resolves #2278)

src/toil/worker.py
Worker.py will try to read redirected stdout/err logs which are not always created. This PR will prevent this read from happening unless these outputs were redirected.
=> Prevent worker from checking for nonexistant file (resolves #2300)

src/toil/utils/toilStatus.py
This allows the status to be queried as a rough API without raising an exception if the jobstore folder has not been created yet.
=> Toil Status no longer raises if no jobstore present.

setup.py, src/toil/fileStore.py, src/toil/jobStores/fileJobStore.py
I've backed out the code that I wrote to diagnose what is holding a file open and try to kill it or close the file descriptor, but this at least solves the immediate problem I was having in that issue and somehow stops the file descriptor from leaking in the first place.
It's not a general solution to misbehaving user code, which can still do bad things like start a subprocess attached to a file stream in the job store and leave it running when the Toil job exits.
=> Fix 2162 (at least partially) by refactoring stream writes in the fileJobStore

src/toil/wdl/toilwdl.py, src/toil/wdl/wdl_synthesis.py
Exports wdl output files to a cloud bucket with an option analogous to the current cwl option to do so.  This retains the original names of the files.
=> WDL bucket outputs with orig names.

setup.py, src/toil/cwl/cwltoil.py, src/toil/leader.py, src/toil/realtimeLogger.py, src/toil/test/cwl/cwlTest.py
=> CWL:fix support for user space overrides

src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/htcondor.py
This Pr will change how the abstract grid engine batch system will decide whether or not to continue making jobs. Currently it the --maxLocalJobs option is not being respected. This fixes the issue by checking if the number of running jobs is less than the value set by the user. When it exceeds that number it stops.
=> Grid engine job creation fix

src/toil/provisioners/node.py, src/toil/utils/toilSshCluster.py
To debug workflows, it is helpflu to have access to the Mesos dashboard.
This adds a port forward for port 5050 for the Mesos dashboard, along with the other dashboards that get forwarded with `toil ssh-cluster`.
I'm also adding another option to `toil ssh-cluster` so you can pass options through to SSH. This allows you to do something like `--sshOption=-D8080` to get a SOCKS proxy, so you can talk to the actual nodes in the cluster by IP address. (You have to use the = syntax because of https://bugs.python.org/issue9334) This is important if you want to use the full capabilities of the Mesos dahsboard, which include peeking at the stdout and stderr of the running executors, and will hopefully be useful for debugging. But to use it, you have to point your browser at the resulting proxy, …
=> Add Mesos port forwarding and the ability to use a SOCKS proxy with toil ssh-cluster

docs/gettingStarted/quickStart.rst, src/toil/cwl/cwltoil.py
This PR would add two if statements in cwlToil's main function that check to see if the user specified these options appropriately. Additionally, it shows the proper usage of these options in update documentation.
=> Require a jobstore to be specified when a provisioner is. (Resolves #2262)

setup.py
`pip install toil[all]` doesn't work on apple right now.
Toil's wheels are built on a linux machine, which means that they include the `htcondor` apple-incompatible extra when pip installed on apple computers (but not when built from source, since it checks for this when `setup.py` is run).
There is a conditional statement in setuptools to address this, but it would conditionally make using the `all` extra unusable on apple computers (which is kind of already the current behavior).  So I've opted to go for the simpler solution and omit `htcondor` from the `all` extra.
=> Htcondor in wheel breaking on apple computers.

src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
Addresses #2354.
Also changed the test file so that it will run from any directory, not just when cwd == its directory.
=> workDir defaults to tmpdir_prefix now if not set by the user.  Resolves #2354.

src/toil/provisioners/clusterScaler.py
Occassionally toil will get in a state where every message is logged
twice. The root cause of these extra messages was a stray logging
handler set up in clusterScaler.py.
=> Stop logging every message twice in certain cases

src/toil/batchSystems/torque.py
In the torque documentation, since at least version 4, it is supposed to throw an error if you use ncpus and nodes in the resource request argument (-l). http://docs.adaptivecomputing.com/torque/6-1-2/adminGuide/torque.htm#topics/torque/2-jobs/requestingRes.htm
=> Fix invalid qsub in torque.py

src/toil/__init__.py
When running toil in a Conda virtual environment instead of virtualenv,
_toil_worker could not be found without explicitely setting the PATH
environment variable. This commit adds recognition of Conda virtual
environments and fixes this issue.
=> Add recognition of conda virtual envs, resolves #2421

src/toil/leader.py
By no longer logging the failed jobs, the code for creating logs can be simplified. This PR would do that.
=> Simplify log creation in leader.

src/toil/serviceManager.py
This is an old bit I never merged upstream--probably only useful for Cactus on very large trees.
The ServiceManager thread previously launched only one "batch" of
services at a time. This caused massive bottlenecks when many services
needed to be started at once. This causes all services to be issued
simultaneously, *unless* they have a special hierarchy (i.e. parent
and child services), in which case the old behavior is kept to avoid
problems where e.g., Spark master services would crowd out Spark
worker services.
=> Make ServiceManager stop blocking while (most) services are established

src/toil/batchSystems/lsf.py
We were missing reporting job id on one error catching in LSF.
=> log job id on error

setup.py
Follow PR common-workflow-language/cwltool#982, which was [merged upstream](https://github.com/common-workflow-language/cwltool/commit/b82ce7ae901a54c7a062fd5eefd8d5ceb5a4d684).
Resolving software requirements using [Environment Modules](http://modules.sourceforge.net/) is a basic service of galaxy-lib, but only works since galaxyproject/galaxy@69a8700, available in 17.09.9 dated 2017-09-21. The test added upstream to cwltool demonstrated that version 17.09.3 of galaxy-lib is inadequate.
This PR bumps the minimum version of galaxy-lib to 17.09.9 for Toil as well.
=> Bump minimum version of galaxy-lib

src/toil/__init__.py, src/toil/batchSystems/__init__.py, src/toil/batchSystems/gridengine.py, src/toil/batchSystems/lsf.py, src/toil/batchSystems/lsfHelper.py, src/toil/batchSystems/parasol.py, src/toil/batchSystems/slurm.py, src/toil/batchSystems/torque.py, src/toil/common.py, src/toil/resource.py, src/toil/test/__init__.py, src/toil/wdl/wdl_functions.py, version_template.py
Sorry @markasbach, I screwed up your PR https://github.com/DataBiosphere/toil/pull/2492, here is a re-do
> This is a set of a few small commits to enhance python 3.x compatibility, especially when using slurm. Unfortunately, I'm not a git pro and didn't find an easy way so squash them to a single commit as requested by https://toil.readthedocs.io/en/latest/contributing/contributing.html#naming-conventions.
> Is related to #2408 but doesn't fix the issue (over 60 offline tests still fail).
=> fixes for python 3.x and slurm try 2

.travis.yml, src/toil/batchSystems/mesos/batchSystem.py
This fixes an annoying bug where Toil slows to a crawl when dealing with many jobs.
Previously the system had essentially 0 throughput when there were
more than ~100-300k queued jobs. The existing check took linear time
in the number of issued jobs, but was actually redundant for determining
the number of queued jobs, because `jobTypes` contains only queued
jobs. Checking the length of `jobTypes` is sufficient by itself to determine
whether there are jobs to issue to Mesos.
=> Remove linear-time bottleneck from Mesos batch system

src/toil/fileStore.py, src/toil/test/src/jobFileStoreTest.py
This should solve #1020 by making `writeGlobalFileStream` yield a stream that, when written to, updates the size of a real genuine FileID.
This should solve the issue where `str`s were masquerading as FileIDs after being introduced to workflows by `writeGlobalFileStream`.
=> Return stream FileID to fix #1020

Makefile, setup.py
Move the pytest-cov install to `make prepare` to join the existing
pytest installation command there.
This is a partial revert of beeb56c8b3c16e814e392987a327e904076a4cce
=> Don't force all users to install pytest

docs/running/cloud/clusterUtils.rst, src/toil/batchSystems/mesos/batchSystem.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/test/utils/utilsTest.py
While trying out Toil, I got the RuntimeError in awsProvisioner.py, and figured to send a small fix to change the rest of the code as well :)
=> Small typo fix: Replace 'insure' with 'ensure'.

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/options.py, src/toil/common.py
Add an option to run CWL internal jobs on workers instead of the master. This will speed up the pipeline considerably for very large workflows that contain many scatters and/or sub-workflows (provided that there are enough workers).
Tested:
Built a docker image with these changes and tested with the flag being true and false.
=> Add a flag for running CWL internal jobs on workers.

src/toil/cwl/cwltoil.py
This option is available in the cwltool, but not exposed in Toil.
Tested:
Built a docker image and ran the tool.
=> Add --no-read-only option to the CWL runner.

src/toil/__init__.py
An [empty credentials file is created](https://github.com/DataBiosphere/toil/blob/044970558318d28654d2f79d1c9ccf31c4dfab81/src/toil/__init__.py#L613) in case of permanent credentials. The check [here](https://github.com/DataBiosphere/toil/blob/044970558318d28654d2f79d1c9ccf31c4dfab81/src/toil/__init__.py#L565) simply returns if an empty file exists, but does not set the credentials. As a result, credentials are not found and it shows an error.
=> Fix boto3 credentials for permanent credentials.

src/toil/__init__.py
There were two other missing import errors when running on a clean EC2 instance. Would be great if there were tests covering these paths (perhaps there are integration tests already?).
=> Add missing imports to toil/__init__.py.

docker/Dockerfile.py, docker/customDockerInit.sh, docs/appendices/environment_vars.rst, src/toil/__init__.py, src/toil/provisioners/abstractProvisioner.py
This solves the private docker authentication issue #2166 as one can add `TOIL_CUSTOM_DOCKER_INIT_COMMAND='pip install awscli && eval $(aws ecr get-login --no-include-email --region us-east-1)'` to the environment variable, which is then executed on the docker instance in all workers (note: this is easy to do manually on the master, but not possible on the workers when running a large cluster).
Notes:
* I figured to make this more generic to allow any type of custom initialization and not be AWS ECR specific. We can even consider removing `waitForKey.sh` in favor of this.
* Using an environment variable is not ideal, but passing the argument through all provisioners made it complicated.
* This does not work if the Toil image itself is hosted in a private repository, but can be addressed …
=> Add support for running custom init commands in docker.

src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py, src/toil/test/cwl/download.cwl, src/toil/test/cwl/download_http.json, src/toil/test/cwl/download_https.json, src/toil/test/cwl/download_s3.json
The jobstore should be able to handle import from different file schemes
=> Fix s3 import for cwltoil (resolves #2234)

docs/contributing/contributing.rst
Our contributing guidelines have not been followed as written for many
months. Also, they did not describe the process we now have to go
through to test outside PRs.
I've revised the guidelines, to relax them a bit to reflect what
actually has been happening with no apparent ill effects, and to clarify
how we want to handle pulling outside PRs into CI. With the smaller team
we have been working with, I don't think spending the time to adhere to
the previous guidelines would pay off in reduced coordination costs
for the other team members.
This will fix #2565.
=> Revise contributing guidelines to reflect practice

src/toil/__init__.py, src/toil/jobStores/aws/jobStore.py, src/toil/statsAndLogging.py, src/toil/test/src/regularLogTest.py, src/toil/worker.py
This should fix #2594. We weren't encoding log lines before trying to feed them into the gzip compressor, which Python 3 was upset by.
I'm not sure why we didn't see the message in the test environment that I saw running the test workflow manually:
```
python -m toil.test.mesos.helloWorld ./toilTest '--clean=always' '--logLevel=debug' '--writeLogsGzip=testlog'
...
Exception in thread Thread-642:
File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/public/home/anovak/build/toil/src/toil/statsAndLogging.py", line 140, in statsAndLoggingAggregator
if jobStore.readStatsAndLogging(callback) == 0:
File …
```
=> Encode logs for gzip

Makefile, src/toil/__init__.py, src/toil/jobStores/aws/jobStore.py
It may make network requests that can fail.
Also, we want a good error message if it fails, and not a complaint about operating on None.
Fixes #2581 hopefully
=> Retry getting credentials from Boto3

src/toil/provisioners/aws/awsProvisioner.py, src/toil/provisioners/node.py
With this change, Toil can now launch clusters in environments that just have private IPs (tested on AWS only). Other SSH settings (e.g. ProxyCommand) are assumed to be provided through SSH config.
Fixes #2568
=> Add private IP support to node operations.

src/toil/wdl/toilwdl.py
I had to switch to python3 to get Toil working with `$PYTHONUSERBASE` (#2598). But I still have old python in my `$PATH`. This uses the proper python. (Some tests could be updated too, but this is the only actual bug I found.)
=> Use current python executable

src/toil/common.py
Fixes #2586
This was changed in https://github.com/DataBiosphere/toil/commit/2e54371ea316fe2803ce53d1477a51fadcfb5d2e , which effectively disables caching altogether (there is no way to turn caching on). Was that the intention?
This PR changes the existing default behavior though. I can add an `enableCaching` option if we want to keep the existing default behavior. Please let me know!
=> Add an option to set disableCaching to false.

src/toil/jobStores/fileJobStore.py
Addresses #2553. Updating FileJobStore.readFile() to resolve symlinks before creating a hard link to avoid "Invalid cross-device link" error if the symlink is on a different device.
=> Update fileJobStore to resolve symlinks (resolves #2553)

src/toil/jobStores/fileJobStore.py
Reverts DataBiosphere/toil#2556.  I believe I may have been overzealous in merging this as it seems to be causing jobs to fail.
Will test this more after reversion.
=> Revert "Update fileJobStore to resolve symlinks (resolves #2553)"

src/toil/job.py
This should fix https://github.com/ComparativeGenomicsToolkit/cactus/issues/72 and fix #2590
We still will want to enforce a lower bound on job resource requirements when scheduling that is sufficient to run Toil itself.
We also will want to treat lost jobs (that finished according to the scheduler but never reported to us) as failures.
=> Increase hardcoded encapsulate follow-on resources

.travis.yml, docs/contributing/contributing.rst, src/toil/statsAndLogging.py, src/toil/test/jobStores/jobStoreTest.py
I've been trying out Toil on a cluster with Python 3.4. It looks like the stats and logging files are being written in binary mode (`wb`) but `json.load()` doesn't handle binary files [until Python 3.6](https://docs.python.org/3.6/library/json.html#json.load). I therefore get errors like this:
```
File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.4/threading.py", line 859, in run
self._target(*self._args, **self._kwargs)
File ".../toil/src/toil/statsAndLogging.py", line 142, in statsAndLoggingAggregator
if jobStore.readStatsAndLogging(callback) == 0:
File ".../toil/src/toil/jobStores/fileJobStore.py", line 480, in readStatsAndLogging
callback(fH)
File ".../toil/src/toil/statsAndLogging.py", line …
```
=> StatsAndLogging(): ensure json.load() receives only string input

docs/appendices/environment_vars.rst, docs/developingWorkflows/toilAPIBatchsystem.rst, src/toil/batchSystems/htcondor.py
This MR is a series of bug fixes and new features for HTCondor support in Toil. The cluster I'm using has HTCondor 8.8.2, and I'm using Python 3.6.
`HTCondorBatchSystem(): try iterating ClassAds with next(ads) before ads.next()`: It looks like iteration of ClassAds requires `next(ads)` instead of `ads.next()`. I'm not sure whether this was an interface change in the Python bindings to HTCondor, or a Python 2-vs-3 issue, or something else. A `try ... catch` is used to fall back to `ads.next()` if required.
`HTCondorBatchSystem(): encode 'command' to 'utf-8' after formatting`: This may be another Python 3 issue. Python >= (at least) 3.4 will format a byte string quoted with `b` prefix:
```
>>> "{0}".format('string'.encode('utf-8'))
"b'string'"
```
The `b` prefix is then included in the …
=>  HTCondorBatchSystem(): fixes and features

docs/running/hpcEnvironments.rst
It would be good to mention HTCondor explicitly in `docs/running/hpcEnvironments.rst`: it's a reasonably popular scheduler for high-throughput computing (HTC), and is used e.g. by the [Open Science Grid](https://opensciencegrid.org/).
=> docs/running/hpcEnvironments.rst: mention support for HTCondor

src/toil/batchSystems/slurm.py
- Out-of-memory-killed jobs will show zero exit code but non-zero terminating signal
code, so only returning the exit code will tell Toil these jobs have succeeded.
- If terminating signal code N > 0, instead return 128+N (following Bash behaviour).
=> SlurmBatchSystem(): include both exit code and terminating signal in job return status

.gitlab-ci.yml
The Gitlab runner did not like our Python 3 tests, because its locale is set such that Python doesn't want to print anything but ASCII to the console.
This tells Python to treat its standard IO streams as UTF-8, whatever the locale says.
I'm also setting the Python 2 and 3 tests to run in parallel so we aren't tempted to rely on just one of them.
=> Adjust test encoding to fix #2652

src/toil/provisioners/aws/awsProvisioner.py, src/toil/utils/toilLaunchCluster.py
Adds an option to specify EC2 IAM profile via `--awsEc2ProfileArn` flag. If not provided, it creates the profile automatically (existing behavior). This also only destroys the profile if it matches the one that was automatically created. I think this heuristic is ok for now to keep things simple (assumes custom roles won't have the same name as the one that Toil creates), but please let me know if you have better ideas!
P.S. I also renamed `ARN` to `Arn` to match the AWS field name in instanceMetadata.
Resolves #2575
=> Add an option to set custom AWS IAM roles (resolves #2575).

src/toil/batchSystems/mesos/executor.py
This fixes the root cause in issue #2655 . I still need to add tests for it, but decided to fix the root cause in the meantime while I figure out how tests work :)
Tested to ensure tasks do indeed get killed once the timeout is reached.
=> Get value of taskId in Mesos' killTask method.

src/toil/test/src/fileStoreTest.py
Addresses the bug in #2645.  I'll fix the warnings in a separate PR.
=> Fix python3.7 break on __new__ static method.

docker/Dockerfile.py
=> Drop python3-dev since we have python3.6-dev which conflicts

src/toil/batchSystems/singleMachine.py, src/toil/lib/context.py, src/toil/lib/ec2.py, src/toil/lib/exceptions.py, src/toil/realtimeLogger.py, src/toil/resource.py, src/toil/test/batchSystems/batchSystemTest.py, src/toil/test/cwl/cwlTest.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/sort/sortTest.py, src/toil/test/src/importExportFileTest.py, src/toil/test/src/jobEncapsulationTest.py, src/toil/test/src/jobGraphTest.py, src/toil/test/src/jobServiceTest.py, src/toil/test/src/jobTest.py, src/toil/test/src/miscTests.py, src/toil/test/src/promisesTest.py, src/toil/test/src/resourceTest.py, src/toil/test/src/systemTest.py, src/toil/test/src/toilContextManagerTest.py, src/toil/test/src/workerTest.py, src/toil/test/utils/utilsTest.py
There are pages and pages of warnings when run in python3.
Changes the two main offenders:
`log.warn` -> `log.warning`
`assertEquals` -> `assertEqual`
=> Address python3 deprecation warnings.

src/toil/job.py, src/toil/lib/docker.py, src/toil/test/lib/dockerTest.py
Ugh, only tested in py2 so missed this.
=> Subprocess dockercall bytestring compatibility for py2/3.

src/toil/provisioners/aws/awsProvisioner.py
Making sure that the leader is terminated first results in a guarantee that no other worker has started in the meantime (from when the destroyCluster call is made until when the instances are actually terminated). This is only an issue in a cluster where a workflow is actively running.
Resolves #2670
=> Terminate the leader first in a running cluster.

src/toil/provisioners/aws/awsProvisioner.py
Reverts DataBiosphere/toil#2671
The original PR introduced a bug about cleaning up security groups and IAM profiles if the leader is the only instance running (most common case). Reverting this now as I like to take some time to figure out the best way to address this and hope to avoid special-casing things in two places.
Issue #2670
=> Revert "Terminate the leader first in a running cluster."

docker/Dockerfile.py
This makes sure apt package lists can't get cached in the docker cache separately from the command to install packages using them. It also makes sure that they don't go into the stack of layers used to build the final image.
=> Make sure we always have current package lists (fixes #2674)

src/toil/provisioners/aws/awsProvisioner.py
Related to #2671 and #2685 
This is the cleanest solution that I could come up with: to special case `vpcId` and group other termination operations (for now just IAM role deletion) into a single method.
Tested with various configurations:
* Only the leader running
* Only workers running
* Both leader and workers running
* No instances running (this is a no-op).
Resolves #2670
=> Terminate the leader first when destroying a cluster.

docs/appendices/aws_min_permissions.rst, docs/index.rst, docs/running/cloud/amazon.rst
Add documentation about the new `--awsEc2ProfileArn` flag. I added an appendix section so that we can include all customized permissions when @tthyer finalizes the list in #2700.
=> Add documentation about --awsEc2ProfileArn.

src/toil/cwl/cwltoil.py
This should fix #2601 
cwltoil has a whole system for creating job-specific temporary directories
under its work directory. It should instead probably be using Toil's built-in
concept of a work directory, and not maintaining its own. After #2587 merges I
think they will always be under the same path, so then we can rip out the
second system and see if anything breaks.
=> Clean up temporary directories cwltoil uses to hold output streams

src/toil/batchSystems/lsf.py
Hi Toil team,
Our cluster doesn't have any nodes with this `type`, and thus this hard-coded param is preventing bsub submissions for lsf.
We currently have successfully made this change in my fork of Toil, but were hoping to get it merged into DataBioSphere so we can get back to the main fork, if there are no other users that this could cause an issue for.
I've ran the test suite locally with `make test`, and received two errors related to HTCondor support, which may be due to incompatibilities of the HTCondor pypi package installing on my mac. Any advice would be appreciated.
```
Successfully tagged quay.io/ucsc_cgl/toil-mtail:3.21.0a1-81315b28d46177db81a233c92fef76ce0d17e830
TOIL_APPLIANCE_SELF=/:3.21.0a1-81315b28d46177db81a233c92fef76ce0d17e830 \
python -m pytest --cov=toil -vv …
```
=> Remove X86_64 type requirement from lsf support

src/toil/resource.py
Added a check to not allow user to execute toil in a dir such as /tmp or /var.
=> Prevent Toil from zipping entire dirs

src/toil/provisioners/aws/__init__.py, src/toil/test/__init__.py
Follows the suggested method here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/identify_ec2_instances.html
Fixes #2732
=> Fix runningOnEC2 to work with all instances.

src/toil/cwl/cwltoil.py
Setting `tmpdir` actually [overrides tmpdir_prefix](https://github.com/common-workflow-language/cwltool/blob/master/cwltool/command_line_tool.py#L542) and is not needed (results in a bug where files get corrupted if multiple jobs are running in the same worker and dont create unique tmp files in the `/tmp` folder).
Just setting `tmpdir_prefix` is enough for cwltool to create a unique tmpdir in the specified directory.
Tested with both `--tmpdir-prefix` and without.
Fixes #2744
=> Fix CWL tmpdir to be unique per job.

docker/Dockerfile.py
Error looks like this:
```
(venv) quokka@qcore:~/git/toil$ make test tests=/home/quokka/git/toil/src/toil/test/jobStores/jobStoreTest.py::AWSJobStoreTest::testDestructionOfCorruptedJobStore
python setup.py sdist
running sdist
running egg_info
writing requirements to src/toil.egg-info/requires.txt
writing src/toil.egg-info/PKG-INFO
...
...
...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
python3.6 : Breaks: python3-dev (< 3.6.5~rc1-1) but 3.5.1-3 is to be installed
E: Unable to correct problems, you …
```
=> Fix python3-dev conflict.

src/toil/statsAndLogging.py
Set a limit for how long a log name can be (<255 char)
=> Limit Length of Log Name

.gitlab-ci.yml, Makefile, setup_gitlab_ssh.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/mesos/executor.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/aws/utils.py, src/toil/jobStores/googleJobStore.py, src/toil/lib/compatibility.py, src/toil/lib/encryption/_nacl.py, src/toil/provisioners/clusterScaler.py, src/toil/test/__init__.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/worker.py
Python2.7 tests are working.  Hopefully python3.6 tests will now follow suit (python3.6 jobstores tests are working in #2749 but I didn't realize until I was a bit further in that they'd broken the python2.7 tests).  This PR should reconcile #2749 and the working python2.7 tests in `master` currently.
=> WIP Run aws jobstore tests redux.

src/toil/lib/docker.py
This ought to fix #2767, or at least allow working around the underlying slow Docker container creation problem. It lets you set the Docker communication timeout in apiDockerCall, and it gives it a very long default, seeing as a short timeout doesn't actually result in us regaining control from the `docker` module any faster in my testing anyway.
=> Expose the docker socket timeout with a long default

src/toil/common.py, src/toil/statsAndLogging.py, src/toil/worker.py
Useful option for debugging without enabling `--logDebug`. This is especially useful when trying to get raw logs from several thousand jobs (`--logDebug` is too verbose and slow).
Fixes #2779
=> Add --writeLogsFromAllJobs option.

src/toil/batchSystems/slurm.py
Removed `-Q` (quiet) option from `sbatch` command in `submitJob` method.
This allows passing Slurm job id to Toil and succesful calling of `submitJob`.
=> Fixing Slurm sbatch command (resolves #2774)

src/toil/provisioners/clusterScaler.py
* Fixes lookup by IP when checking ignored nodes.
* Fixes the case where an ignored worker is terminated externally (e.g. through spot instance termination), but appears with the same IP later (e.g. as part of scaling up).
Fixes #2788
=> Ensure terminated ignored nodes are cleared from batch system.

src/toil/leader.py, src/toil/statsAndLogging.py
Makes it easier to distinguish logs from failed jobs and successful ones.
Fixes #2791
=> Add "failed_" prefix to failed logs.

src/toil/test/provisioners/clusterScalerTest.py
=> Use argparse Namespace because setattr on Object doesn't always work in the tests

src/toil/jobStores/aws/jobStore.py
This now allows cleaning up any s3 jobstore bucket (no more failures observed).
Tested with non-existent jobstore (no-op) and existing jobstore with various configurations.
Fixes #2825
=> Ignore checking versioning consistency when cleaning s3 jobstore.

src/toil/provisioners/gceProvisioner.py
When launching a cluster in Google Cloud, uses the family name `coreos-stable` rather than a specific image release `coreos-stable-1576-4-0-v20171206`, which is not currently available
=> Specify GCE coreos image by family name instead of specific version

docs/contributing/contributing.rst
Updating the guide to prefer using `Squash and merge` when merging PRs to master. More details are in #2816 
Fixes Issue #2816
=> Update contribution guide to prefer Squash and merge.

src/toil/jobStores/aws/utils.py
Use `wait_until_exists` from the S3 object summary to avoid intermittent 404s from calling head_object immediately after object creation.
=> Add wait_until_exists before calling head_object, resolves #2808

src/toil/jobStores/aws/utils.py
Reverts DataBiosphere/toil#2810
This should hopefully fix our Python 2 integration tests, until we figure out why we keep getting WaitErrors due to "Bad Request"s.
=> Revert "Add wait_until_exists before calling head_object, resolves #2808"

src/toil/batchSystems/kubernetes.py
`kubectl` is clever enough to pick up its config and credentials from an enclosing pod, but the `kubernetes` Python module can't do it by itself.
This PR adds some code to try and grab the Kubernetes configuration form the currently running pod if it can't be obtained from a config file.
This fixes #2850.
=> Try service account configuration for Kubernetes

src/toil/batchSystems/kubernetes.py
This fixes #2866 and also includes some quieting of the logging from event watching, which was swamping the actual output from my jobs.
=> Raise job limits to be more than their requests

src/toil/fileStores/__init__.py, src/toil/fileStores/abstractFileStore.py, src/toil/fileStores/cachingFileStore.py, src/toil/fileStores/nonCachingFileStore.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/jobStores/googleJobStore.py, src/toil/utils/toilStats.py
Should fix #2854 by adapting Toil to still allow some of the things that Cactus does that we no longer allow.
This *should*, so far, allow Cactus to keep passing around strings as file IDs, by letting the FileStore recover file size information from the JobStore when it isn't passed along with the ID.
=> Cactus compatibility fixes

.gitlab-ci.yml, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/aws/utils.py, src/toil/jobStores/utils.py, src/toil/lib/encryption/_nacl.py, src/toil/test/jobStores/jobStoreTest.py
This is my attempt to fix #2873. Right now I can't replicate the failure locally, so I've added some more specific errors/logging to see if I can get more information on failures on Gitlab.
=> Attempt to fix AWS jobstore test

docs/appendices/environment_vars.rst, src/toil/__init__.py, src/toil/batchSystems/kubernetes.py
Added env var ```TOIL_KUBERNETES_OWNER``` to help identify different users kube jobs.
=> kubernetes job owner name

src/toil/batchSystems/kubernetes.py
This will fix #2876 by not floor-ing the CPU requirement.
It now uses the same requirements and limits, to make our admins happy, and also now adds half a gig of memory and storage for Toil overhead (like the hot-deployed user scripts, or the logs), instead of using that as a minimum job size, which didn't quite make sense.
=> Change Kubernetes job sizing logic

docker/Dockerfile.py
The python3.6 package was recently made private by Jonathon: https://launchpad.net/~jonathonf , which leads to the following error when building the docker image:
```
Err:13 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main amd64 Packages
403  Forbidden
Ign:14 http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial/main all Packages
Fetched 16.3 MB in 2s (6208 kB/s)
Reading package lists...
W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
The deadsnakes ppa contains the required …
=> Change python3.6 ppa to deadsnakes.

src/toil/common.py, src/toil/jobStores/aws/jobStore.py
This ensures that files are not corrupted during transfer. Since this is a very rare, but important event, I figured it's simpler to just fail and let the pipeline retry the task rather than trying to re-download the file. Also, since this is a safety check, I think it should be enabled by default and only disabled if explicitly specified.
I used `sha1` to match the checksums from CWL.
Tested on various pipelines for a couple of months on our branch. So far, we've seen at least one instance of this happening in a production run when handling large files.
Fixes #2870
=> Add checksum verification for AWS job store.

src/toil/jobGraph.py
This should fix #2879; you should be able to `--restart` with a higher `--defaultDisk` (and a nonzero number of retries) and at least eventually get your job to run through, after one more failure at the old disk limit.
What we might really want is a separation between the default job size and the max job size we will increase to, and some kind of doubling logic that is ideally aware of what limit a job hit when it failed. But this should at least allow recovering a stuck workflow.
=> Up the disk to the default as well as the memory

src/toil/batchSystems/kubernetes.py
This (written on top of #2868) will fix #2867 by reloading the Kubernetes config and making a new API clients every 5 minutes, as suggested in https://github.com/kubernetes-client/python/issues/741#issuecomment-518052241.
We'll still get in trouble if we have a single watch or loop over pods that runs for more than the credential expiration time, but that seems unlikely to happen and would be its own slowness problem anyway.
=> Constantly reload Kubernetes config

src/toil/batchSystems/kubernetes.py
Since we bump up the Toil job's memory request when making the pod, we can safely look for pods that are almost at their memory limits and consider them to be stuck to fix #2858. We might catch some pods that will eventually finish, but those pods will be for Toil jobs that went over their requested memory, so we are allowed to fail them.
=> Consider pods that are very close to their memory limits to be stuck

src/toil/fileStores/cachingFileStore.py
Related to issue #2910 : increasing the timeout dramatically reduces the "database is locked" errors (actually, I haven't seen the error since increasing the timeout; it's still possible that it'll get thrown for larger workflows though).
Default is 5s.
=> Increase SQLite DB timeout to 60s.

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/kubernetes.py, src/toil/test/batchSystems/batchSystemTest.py
The Kubernetes batch system should now always produce positive runtimes, even
when pods behave strangely. It also does a bit more work to come up with
meaningful runtimes for cases where pods don't formally end.
This should fix #2919.
=> Improve Kubernetes job timing

.gitlab-ci.yml, Makefile, setup_gitlab_docker.py, setup_gitlab_ssh.py, src/toil/batchSystems/mesos/executor.py, src/toil/batchSystems/mesos/test/__init__.py, src/toil/batchSystems/options.py, src/toil/batchSystems/parasolTestSupport.py, src/toil/batchSystems/singleMachine.py, src/toil/lib/threading.py, src/toil/test/__init__.py, src/toil/test/batchSystems/batchSystemTest.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/src/deferredFunctionTest.py, src/toil/test/src/systemTest.py
This will fix #2902.
When nobody else is using CI, I am going to want to manually pause the non-Kubernetes runner, unpause the Kubernetes runner, and verify that these changes are indeed sufficient to make jobs run through on the Kubernetes runner. I'm not sure if I want to do that before or after we merge this; there should be no trouble with these changes on the existing non-Kubernetes runner.
=> Set up Gitlab testing for Kubernetes runners

setup.py
This should fix #2924 (as long as your pip is new enough to respect [PEP 508](https://www.python.org/dev/peps/pep-0508/)).
If someone with permissions forked http-parser into databiosphere, or if https://github.com/benoitc/http-parser/pull/88 were to be merged, we could use a better place than my fork of `http-parser` as the source for this.
=> Use an http-parser for pymesos that builds on 3.7+

setup.py
Reverts DataBiosphere/toil#2931
Fixes the pip install issue:
```
pip install --no-cache-dir toil[aws,mesos]
Collecting toil[aws,mesos]
Downloading toil-3.22.0.tar.gz (377 kB)
|████████████████████████████████| 377 kB 2.5 MB/s 
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
toil depends on http-parser@ https://github.com/adamnovak/http-parser/archive/190a17839ba229c635b59d960579451a81fe73f3.zip#sha256=3d30c84a426627e468657c44de199daee9d3210a48e392d4ad2e7497c5010949 
```
=> Revert "Use an http-parser for pymesos that builds on 3.7+"

.gitlab-ci.yml, src/toil/batchSystems/kubernetes.py, src/toil/lib/threading.py, src/toil/test/__init__.py, src/toil/test/batchSystems/batchSystemTest.py, src/toil/test/docs/scriptsTest.py, src/toil/test/src/promisedRequirementTest.py
This will fix #2932 by making sure to actually read the quota files when trying to get CPU counts.
That should fix both the total cores it is expecting, and the number of jobs it actually attempts to run in parallel.
=> Fix cpu_count() to actually read quotas

src/toil/fileStores/cachingFileStore.py
This should fix #2947, assuming that workflow attempt numbers are increasing integers, and nobody is trying to race us to clean up the workflow when there are old databases from previous attempts, or dropping databases from new attempts in while we are cleaning up.
=> Scan for the latest caching database instead of using a hard link

src/toil/deferred.py, src/toil/fileStores/cachingFileStore.py, src/toil/test/src/fileStoreTest.py
This should fix #2910, but harder.
I've wrapped all the writes to the database to go through a single function, which uses Toil's retry system to retry forever, with increasing backoff, if it tries to write and the database is locked. It also takes care of committing.
I've also inserted some sleeps into the loops that poll the database with conditional writes. This should reduce the portion of the time that the database is locked, overall.
I've also added a test that was able to reproduce the database is locked error with the sqlite timeout set to 5 seconds. I'm bumping it back up to 60, so I'm not sure how good the test will be anymore at checking the logic that deals with timeouts from sqlite, but the higher timeout should provide better protection from timeouts on the read side (which …
=> Fix database being locked when trying to write in the CachingFileStore

docker/Dockerfile.py, version_template.py
Should fix #2964, but needs to be tested.  The image I pushed is:
```quay.io/ucsc_cgl/toil:3.24.1a1-efeaa75465e9c6dd3df8e4535a810a47b17f0561-dirty-py3.6```
=> Specify py3.6 or py3.x instead of just py3.

src/toil/lib/ec2.py, src/toil/provisioners/abstractProvisioner.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/provisioners/clusterScaler.py
I ran 01036ae through with this Cactus test, and it finished successfully:
```
cactus --nodeTypes c5.xlarge:0.12,r5.xlarge --root mr --minNodes 0,0 --maxNodes 2,2 --provisioner aws --batchSystem mesos --logDebug --latest aws:us-west-2:adamnovak-jobstore ./examples/evolverMammals.txt adamnovak-output.hal  --logFile adamnovak-log
```
I think that this will fix @glennhickey's problems in https://github.com/DataBiosphere/toil/issues/2964#issuecomment-584636883
This fixes #2970.
=> Fix py3 spot market scaling

setup.py
Same entry point is provided by `toil-cwl-runner`
=> Drop the long-deprecated cwltoil

README.rst, setup.py
We can start merging python2.7 incompatible code into `master` now.  I plan to merge a few in today.
=> Dropping python2.7 announcement.

src/toil/batchSystems/mesos/executor.py
Looks like this accidentally got removed in PR #2842 ... results in `'NameError: name 'subprocess' is not defined`, which is imported in the module.
=> Add import subprocess to executor.py

src/toil/common.py
Fixes #2977  about `a bytes-like object is required, not 'str'` and also flushes the stdin so that stats appear immediately on the dashboard (looks like the new subprocess module has a different buffer/flushing logic that results in 10+ min delay).
=> Encode mtail stdin to utf-8 and flush.

src/toil/fileStores/abstractFileStore.py, src/toil/fileStores/cachingFileStore.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/jobStores/googleJobStore.py, src/toil/lib/misc.py
This should pass the stage of needing to check for jobstore on `--restart`.
=> Eliminate sleep time on --restart

docs/running/cloud/amazon.rst, src/toil/provisioners/aws/awsProvisioner.py, src/toil/utils/toilLaunchCluster.py
Adds the ability to specify other predefined security groups for a Toil cluster (e.g. if a DB access is restricted to a set of security groups and cannot be dynamically modified).
Tested:
* Launched, ran, and destroyed a cluster with multiple `--awsEc2ExtraSecurityGroupId`
* Launched, ran, and destroyed a cluster without specifying `--awsEc2ExtraSecurityGroupId`
Resolves #2995
=> Add support for --awsEc2ExtraSecurityGroupId.

src/toil/batchSystems/options.py, src/toil/common.py, src/toil/fileStores/__init__.py, src/toil/fileStores/abstractFileStore.py, src/toil/fileStores/cachingFileStore.py, src/toil/fileStores/nonCachingFileStore.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/lib/misc.py, src/toil/test/__init__.py, src/toil/test/jobStores/jobStoreTest.py
Toil currently has a "linkImports" parameter, used by fileJobStores only, to prevent copying of files present in the input into the job store and replacing the copy by a link.
This pull request introduces a "moveExports" parameter, also used in fileJobStores only, allowing to move the file from the job_store to the output directory, preventing the copy. In the job store, the file is replaced by a link to its new location in the output directory.
=> Add moveExports option.

setup.py, src/toil/cwl/cwltoil.py
Using `cwltoil` now can result in a confusing error (see: https://github.com/DataBiosphere/toil/issues/2987).
```
File "/home/ubuntu/toil/src/toil/worker.py", line 366, in workerScript
job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
File "/home/ubuntu/toil/src/toil/job.py", line 1392, in _runner
returnValues = self._run(jobGraph, fileStore)
File "/home/ubuntu/toil/src/toil/job.py", line 1329, in _run
return self.run(fileStore)
File "/home/ubuntu/toil/src/toil/cwl/cwltoil.py", line 809, in run
if self.conditional.is_false(cwljob):
AttributeError: 'CWLJob' object has no attribute 'conditional'
```
This adds a function to be called when `cwltoil` is run to raise and warn the user.
=> [easy] Raise and warn the user if using "cwltoil".

src/toil/batchSystems/singleMachine.py, src/toil/test/__init__.py, src/toil/test/batchSystems/batchSystemTest.py
This should fix #1902 and a swathe of related issues, by refactoring the SingleMachineBatchSystem to just use one "daddy" thread to mind all its child processes.
It basically keeps all the jobs in a delay line of a queue until they have the resources they need, which isn't efficient, but I doubt it's worse then 640 contending threads, and it won't stop scheduling small jobs if they queue up behind a lot of jobs that can't run yet.
It passes some local tests but I want to see what the real tests think of it.
=> Cut the Threads

src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
This adds support for the EnvVarRequirement portion of the following CWL1.1 tests:
=> [Part 2] CWL v1.1 Support

Makefile
A temporary fix for https://github.com/DataBiosphere/toil/issues/3006 .  Unfortunately, I'm going to have to set up (hopefully temporary) separate pypi dependencies with our needed fixes for the related issue: https://github.com/DataBiosphere/toil/issues/2924.
=> Pin setuptools during 'make prepare'.

src/toil/test/cwl/alwaysfails.cwl, src/toil/test/utils/utilsTest.py, src/toil/utils/toilStatus.py
Adds `decode('utf-8')` method call to fix the following error:
```
.../toil/utils/toilStatus.py", line 83, in printJobLog
msg += fH.read()
TypeError: can only concatenate str (not "bytes") to str
```
This fix is already being used in leader.py FailedJobsException:
https://github.com/DataBiosphere/toil/blob/993be0c3d95c83ca969d783e708c48d918407b16/src/toil/leader.py#L79-L80
Let me know if you would prefer a new function to abstract out this duplication. 
For testing the bug I added an example CWL workflow that always fails.
Fixes problem raised in #3004
=> fix python3 string/bytes error when using --printLogs

docs/vendor/sphinxcontrib/fulltoc.py, setup.py
This should fix #3010. I had to hack the Sphinx TOC hack we got from DreamHost, which I think was the thing holding us back on Sphinx <1.7.6. I've made it a bit more robust against new Sphinx kwargs being added, and I've relaxed the Sphinx constraint to anything between the current latest version (2.4.4) and 3.0, whatever that will be.
@rikardn does that work for you? Or is there a particular Sphinx version other than the very latest that you want us to support?
=> Update Sphinx and let its version float

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/kubernetes.py, src/toil/batchSystems/mesos/batchSystem.py, src/toil/batchSystems/parasol.py, src/toil/batchSystems/singleMachine.py, src/toil/batchSystems/torque.py, src/toil/common.py, src/toil/jobGraph.py, src/toil/leader.py, src/toil/test/batchSystems/batchSystemTest.py
This change adds the option to set `--retryCount` to a low value since spot/premptable terminations no longer count as failures.
I decided to use `2550` as the exit code for lost jobs, but open to other suggestions as well! Rationale:
* Using anything but an int can result in unexpected bugs, since there could be assumptions in the code about the nature of the arg (now or in the future).
* Using anything in 0-255 can be problematic as it can conflict with other values.
* Using `-1` is also a good option, but I figured it's a 'common' special value and someone else could use it for something else accidentally.
Tested with and without `--enableUnlimitedPreemptableRetries` on a pipeline and forced terminations.
Fixes #2890
=> Add --enableUnlimitedPreemptableRetries option.

docker/Dockerfile.py
I've often found using `less` and `vi` when debugging things inside the Toil appliance image, and kinda annoying to have to install it every time. I figured since they don't really add much overhead to the image, we could just include them by default.
I didn't create an issue for this since it's a trivial change, but lemme know if you like one!
=> Add less and vim to docker.

src/toil/batchSystems/singleMachine.py, src/toil/jobStores/fileJobStore.py, src/toil/leader.py, src/toil/resource.py, src/toil/statsAndLogging.py, src/toil/test/docs/scripts/example_alwaysfail.py, src/toil/test/utils/utilsTest.py, src/toil/utils/toilStatus.py
I think this will fix #3004.
I initially meant to make it print out a message encouraging the user to run `toil status --printLogs`, but it turns out FailedJobsException is supposed to dump the logs, and it wasn't doing it because of changes to exceptions in Python 3.
So I went through and made the job log dumping consistent in all the places I could find it happening. It now goes through a single method, and it should be easier to see in a noisy Toil log.
@arostamianfar The output from `toil status --printLogs` looks vaguely machine-readable, and I'm changing its format a bit. Will that upset your dashboards?
We might want to have a test for FailedJobsException and/or the leader dumping job logs, but I'm not quite sure where to put it.
=> Improve and Unify Log Dumping

setup.py
I don't want to pin to 3.6 exactly because we can work fine on newer versions without the Mesos extra.
This might make #3020 be magically solved by a Conda bot.
=> Make dependency on Python3.6+ machine-readable

.gitlab-ci.yml, setup.py, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
When running all the CWL v1.1 conformance tests, there are 9 more tests that successfully pass:
`246 tests passed, 7 failures, 0 unsupported features`
(4 "unsupported features" are now failing tests)
=> don't list specific CWL features, try them all (and fix some CWL running bugs)

.gitlab-ci.yml, docker/Dockerfile.py, setup.py
After tests run and pass, ~~I'd like to remove all but the `main` tests for python3.6 and python3.7 and begin running toil in python3.8.~~
Edit: Hmmm... the `main` tests pass with the updated `dill` package, but it's concerning to me that the run times seem to be:
`python3.6`: 20 minutes 49 seconds (https://ucsc-ci.com/databiosphere/toil/-/jobs/48177)
`python3.7`: 23 minutes 36 seconds (https://ucsc-ci.com/databiosphere/toil/-/jobs/48179)
`python3.8`: 45 minutes 18 seconds (https://ucsc-ci.com/databiosphere/toil/-/jobs/48181)
Maybe we should stick to python3.7 as our main test version for the moment and create an issue to log more fine-grained test times as a summary at the end of each run so that we know exactly which tests are taking longer.
=> Test python3.8 and build a python3.8 appliance.

setup.py
This gets rid of the toil-pymesos package stuff we originally created as a work around.
=> Use the original pymesos.

src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/utils.py
This should fix #2375, at least enough to satisfy me. We now compute checksums even for streamed uploads and downloads (as long as the downloads read through to EOF). We also retry non-streaming downloads if the checksum fails.
This doesn't quite implement the resume-from-last-obtained-byte functionality that #2375 wants,. If we want to do that, I think we need to track expected sizes in the job store, in addition to checksums. But even without the resume feature, this should protect user code from ever seeing a silent partial download.
If we run into a file that's so enormous that AWS keeps failing during the download *and* retrying the download from the beginning stops us from actually making progress, then we can implement byte range resumes of partial downloads.
=> Do More Hashing

.gitlab-ci.yml
This keeps all python 3.7 tests, deletes python 3.6 and 3.8 tests except for the basic python `src`/`utils` tests.  This still tests building the appliance for python3.6, python3.7, and python3.8.
This also adds `--duration=0` so all test times will be displayed at the end of each run.  Ideally at some point we can log these in a data base and notice when we significantly increase test times.
=> Mainly test python3.7.

docs/running/cliOptions.rst, src/toil/batchSystems/__init__.py, src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/singleMachine.py, src/toil/common.py, src/toil/jobStores/fileJobStore.py, src/toil/leader.py, src/toil/lib/threading.py, src/toil/lib/throttle.py
This fixes #3016. 
That issue is really caused by Cactus setting the deadlock checking time too high, so it takes us an hour to even see the oops-all-services deadlock, and another hour to do anything about it.
This PR changes Toil to separate the time we wait to terminate the workflow from the time we wait to see if there's a deadlock. It adds some warning-level log messages when the deadlock checker *starts* to think there's a deadlock, and it is able to pull a hint from the batch system (currently only implemented for `SingleMachineBatchSystem`) that can suggest to the user why the deadlock might be happening.
With Cactus installed, I did this to produce a service deadlock:
```
mkdir -p ~/mnt/tmpfs
sudo mount -t tmpfs -o size=2200000000 tmpfs ~/mnt/tmpfs
TMPDIR=$HOME/mnt/tmpfs cactus …
```
=> Detect insufficient resources and deadlocks more usefully

src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
[`cwltool` seems to treat `_:` as a special protocol for directories that need to be created rather than resolved to a filesystem path that gets copied.](https://github.com/common-workflow-language/cwltool/blob/9f3b9e7b74d5a904b12674dfd1300b56a48c3d33/cwltool/process.py#L311-L313) Since the Toil file store only stores files, and CWL ships around the whole metadata tree of files and directories needed to fulfill an InitialWorkDir input, we can just tell CWL that all the directories in the metadata come from the `_:` protocol.
For some reason, we can't just set all the directories' locations to just `_:`. They need to be unique for the `PathMapper` to be able to keep them straight. So I'm just prefixing `_:` onto the source `file:` URL that the directory had on the originating machine. This …
=> Stop CWL from trying to copy downloaded directories from somewhere local

src/toil/batchSystems/singleMachine.py
Logging about trying and scheduling to start jobs, at 0.01 second intervals, makes `--logDebug` useless for debugging anything except the scheduler.
Fixes #3064.
=> Don't log in the inner scheduling loop

src/toil/__init__.py, src/toil/batchSystems/kubernetes.py, src/toil/batchSystems/mesos/executor.py, src/toil/lib/bioio.py, src/toil/worker.py
This fixes #3072 by making sure that messages logged in the worker have timestamps on them.
I'm also trying to follow the recommendations at https://reflectoring.io/logging-format/ for "Human-Readable Logging Formats" by reformatting the logging messages. I've made them look like this on both the leader and the worker:
```
[2020-05-27 14:43:04,578] [MainThread] [W] [toil.resource] Can't globalize module ModuleDescriptor(dirPath='/z/home/anovak/workspace/cactus/venv/lib/python3.6/site-packages', name='cactus.progressive.cactus_progressive', fromVirtualEnv=True).
```
The thread name is clipped at/padded to 10 characters, and the level is reduced to a single character. All the fixed-length fields come first so they are lined up. All the metadata is in `[]` to distinguish it visually from the …
=> Unify logging format

src/toil/job.py
It looks like if we create really long sticks of jobs, Toil can run out of stack when traversing connected components.
This makes it use an on-heap stack instead.
=> Eliminate recursion in root finding to fix #3080

.gitlab-ci.yml
This should fix #1739, although I think the test still is going to take half an hour longer than we want it to.
I'm just running the test as a Gitlab test, rather than writing a pytest test that tries to talk to a real Kubernetes and clone Cactus.
=> Add a Cactus Kubernetes test to the integration tests on Gitlab

.gitlab-ci.yml, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
This adds support for the new listing behavior in CWL1.1+.  See tests 242-246.
CWL1.0 tests appear to be passing: https://ucsc-ci.com/databiosphere/toil/-/jobs/53988
CWL1.1 tests appear to pass but 2 fail when caching: https://ucsc-ci.com/databiosphere/toil/-/jobs/53989
The 2 caching failures appear on the master build, so I suppose I should just make an issue to fix it since it's not directly related to this PR: https://ucsc-ci.com/databiosphere/toil/-/jobs/54084
=> Support CWL 1.1 Listing.

docs/running/cliOptions.rst, docs/running/cloud/clusterUtils.rst, src/toil/common.py, src/toil/provisioners/__init__.py, src/toil/provisioners/abstractProvisioner.py, src/toil/provisioners/aws/awsProvisioner.py, src/toil/provisioners/gceProvisioner.py, src/toil/test/provisioners/aws/awsProvisionerTest.py
Adds an option to override `nodeStorage` for specific `nodeTypes`. Useful for heterogeneous jobs where some tasks need much more disk than others.
Example use case:
`--nodeTypes c5.2xlarge,c5.9xlarge,m4.10xlarge --nodeStorage 100 --nodeStorageOverrides c5.9xlarge:2000`
Fixes #3084
=> Add --nodeStorageOverrides option.

src/toil/job.py, src/toil/leader.py, src/toil/worker.py
Fixes #3102 by:
* Not calling `setupJobAfterFailure` in the worker as it'll be done in the leader now that we return non-zero exit status (fixes double counting failures).
* Always calling `logCompletedJob` when the job finishes regardless of whether it succeeded. This is consistent with both the previous logic (i.e. when we used to return `0` even for failed jobs) and also fixes accounting for failures of other reasons (e.g. `LOST` jobs) as we always re-issue jobs if there are any retry attempts left.
* Remove `_succeeded` flag altogether as it was added back in https://github.com/DataBiosphere/toil/commit/9656354816542648b63b30fb6b047766857e0e30 , but is no longer needed/used.
=> Fix failed job accounting.

src/toil/jobGraph.py, src/toil/leader.py, src/toil/toilState.py
As is, multiple JobGraphs for the same job ID can be updated in the same tick.
I don't think multiple job graphs for the same job ID are supposed to exist at
all.
I'm now deduplicating everything by job ID. The first update with the first
status will win.
Really we should change the whole system to pass around just the IDs of updated
things, and store a single source of truth for the job graph's state, so it is
impossible to have conflicting updates in flight.
This is a workaround for some test failures caused by #3106 in #3088.
=> Deduplicate updated jobs

src/toil/cwl/cwltoil.py
Addresses #3105 
Toil filepaths were missing the import of secondary files (and thus the mapping).
=> More robust CWL filepaths and secondary files.

src/toil/fileStores/cachingFileStore.py, src/toil/worker.py
Fixes #3121 by:
* Ensuring we revert the state of files that failed to upload back to `uploadable` so that they can be retried again later.
* Removing the unnecessary extra commit thread.
Note: I didnt see anything in `_executePendingDeletions` that needed to be changed, so left it as is.
=> Fix database state when file upload fails.

src/toil/__init__.py, src/toil/deferred.py, src/toil/fileStores/cachingFileStore.py, src/toil/jobStores/fileJobStore.py, src/toil/lib/misc.py, src/toil/lib/threading.py, src/toil/test/__init__.py, src/toil/test/lib/dockerTest.py, src/toil/test/src/resourceTest.py
"exist_ok" was added in Python 3.2, so I think we're okay.
=> [easy] Replace custom mkdir_p with the built in.

src/toil/lib/docker.py
Created to test a solution proposed by Adam for https://github.com/DataBiosphere/toil/issues/3116 .
I don't have a Mac, so I can't test this.
=> Create dirs that do not exist when bind-mounting to docker.

.gitlab-ci.yml
#3123 broke the Cactus tests because we don't use the new Cactus that tolerates it. Now we will.
=> Use a Cactus that no longer needs mkdir_p

src/toil/batchSystems/slurm.py
Possible fix for https://github.com/DataBiosphere/toil/issues/3132
When running CWL workflows with `--batchsystem Slurm` option the execution was failing due to an error:
```
$ toil-cwl-runner --batchSystem Slurm --workDir=(...) --jobStore=./jstore wf1.cwl task1.yaml 
...
(...)/toil/lib/python3.7/site-packages/toil/batchSystems/slurm.py", line 106, in _getJobDetailsFromSacct
values = line.decode('utf-8').strip().split('|')
AttributeError: 'str' object has no attribute 'decode'
```
This is the referenced fragment (lines 103-104 from `batchSystems/slurm.py`):
```
stdout = call_command(args)
for line in stdout:
```
Function `call_command()` from `lib/misc.py` (lines 304-329) returns a string so calling `decode()` causes an error.
First issue is that `for line in stdout` loops over a string …
=> Change command output processing (resolves #3132)

src/toil/test/wdl/builtinTest.py, src/toil/test/wdl/standard_library/round.json, src/toil/test/wdl/standard_library/round_as_command.wdl, src/toil/test/wdl/standard_library/round_as_input.wdl, src/toil/test/wdl/toilwdlTest.py
Address #3152.
`round()` is not added to https://github.com/DataBiosphere/toil/blob/master/src/toil/wdl/wdl_functions.py because we are using the Python built-in function. 
Note that `src/toil/test/wdl/toilwdlTest.py` still contains tests for WDL functions. In the future these tests will be moved to `WdlStandardLibraryFunctionsTest` as we add in the corresponding workflow tests. I'm not moving them all at once because there are tests that depend on the test files in `toilwdlTest.py` and I don't want to mess with those in this PR.
=> Add WDL builtin test 'round'.

docs/appendices/environment_vars.rst, src/toil/__init__.py, src/toil/provisioners/abstractProvisioner.py
Similar to #2561 except that it provides a way to run custom commands before running the appliance itself (e.g. we use this to authenticate to a private docker registry to pull the Toil appliance itself). May be useful for other use cases now that there seems to be more restrictions on doing a lot of pulls from public registries.
Resolves #3182
=> Add support for TOIL_CUSTOM_INIT_COMMAND.

src/toil/fileStores/cachingFileStore.py
This should stop us trying to join the thread that we're running in, and fix #3176.
=> Check against joining the current thread during CachingFileStore destructor

src/toil/batchSystems/slurm.py
This should fix #3192 and also remove some of the old python2 imports.
=> slurm.py error, undefeind stdout - stdout should be stderr in code

setup.py
Address #3218. 
Our docker dependency version is currently at `2.7.0` and the latest stable release is `4.3.1`. 
This is to support the hidden "content" attribute in the docker iterator and multiplexed streams, which are part of docker-py's  3.2.0 and 3.7.0 release, respectively. (https://github.com/DataBiosphere/toil/issues/3184#issuecomment-689048387)
This is a big upgrade but our docker wrapper doesn't seem to be affected by the breaking changes described in the [docker change log](https://docker-py.readthedocs.io/en/stable/change-log.html).
=> Update docker module version to 4.3.1

src/toil/lib/docker.py, src/toil/test/lib/dockerTest.py
Resolves #3184. 
The `demux` implementation follows [docker-py's docs](https://docker-py.readthedocs.io/en/stable/user_guides/multiplex.html) for `exec_run` and `attach`. It is extremely inconvenient that this isn't supported in `client.containers.run()`. I had to add a modified version of [`_multiplexed_response_stream_helper()`](https://github.com/docker/docker-py/blob/4.3.1-release/docker/api/client.py#L370) to handle different stream types. 
Note: when upgrading docker in the future make sure that the private `_response` attribute in [`CancellableStream`](https://github.com/docker/docker-py/blob/master/docker/types/daemon.py#L11) has not changed.
=> Add 'stream' and 'demux' options to apiDockerCall

src/toil/wdl/toilwdl.py, src/toil/wdl/wdl_analysis.py, src/toil/wdl/wdl_functions.py, src/toil/wdl/wdl_synthesis.py
Removes old Python 2 imports + PEP 8 changes.
Edit: revert part that breaks tests.
=> Remove Python 2 imports in WDL

src/toil/jobStores/fileJobStore.py
Many filesystems can't handle path components longer than 256 characters.
This should fix #3226.
=> Prevent job kind filenames from getting too long

.travis.yml, src/toil/lib/retry.py
Since `kubernetes` is a Toil "extra", we can't import it unless the module is present.  This follows up on https://github.com/DataBiosphere/toil/pull/3259 to catch additional `kubernetes` modules that may error if the `kubernetes` extra is not installed.
=> Catch other kubernetes imports.

.gitlab-ci.yml, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
This PR adds support for CWL1.1 and allows us to pass conformance test 213.
Input files evaluated in `StepValueFrom` weren't resolving the toil specific uris we use, so were returning `None` for toil paths, which were seen as files that don't exist.
Adds the check if `loadContents == True`, as well as the `loadContents` content size limit.
In cwltool, this is done here: https://github.com/common-workflow-language/cwltool/blob/876e5bd384843bae41c98dcd36641bc71b2bf729/cwltool/workflow_job.py#L647
Closes #3257 .
=> CWL Test #213: Evaluate loadContents if True for StepValueFrom objects.

src/toil/wdl/wdl_synthesis.py
In WDL, I noticed that `0` in the JSON file is interpreted as `None` when I was testing `range()`. 
I don't think this would break anything from before (?), but  `''`, `false`, `0`, and `[]` in the JSON file would be parsed to the correct value in the compiled Python script.
=> Fix None check when parsing WDL JSON file

src/toil/test/wdl/builtinTest.py, src/toil/test/wdl/standard_library/range.json, src/toil/test/wdl/standard_library/range_0.json, src/toil/test/wdl/standard_library/range_as_input.wdl, src/toil/test/wdl/standard_library/range_invalid.json, src/toil/test/wdl/standard_library/transpose_as_input.wdl, src/toil/wdl/wdl_analysis.py, src/toil/wdl/wdl_functions.py, src/toil/wdl/wdl_synthesis.py
Closes #3196. 
`range()` is a Python built-in function but the return type is `range`, so I'm adding a new function to make sure the correct type is returned.
=> Add WDL builtin test 'range'.

src/toil/cwl/cwltoil.py, src/toil/deferred.py, src/toil/jobStores/fileJobStore.py
Instead of using python tempfile to create files and dirs in the
work dir use regular files with uniq names. This allows those files
and folders to honor the system permissions and umask.
This will fix #2355
=> Fixes the problem with folders and files in the workdir permissions

src/toil/batchSystems/torque.py
This pull request attempts to fix #3254 .
@mr-c @adamnovak 
The problem is caused by `generateTorqueWrapper()` within `src\toil\batchSystems\torque.py`：
```python
def generateTorqueWrapper(self, command, jobID):
"""
A very simple script generator that just wraps the command given; for
now this goes to default tempdir
"""
stdoutfile = self.boss.formatStdOutErrPath(jobID, 'torque', '$PBS_JOBID', 'std_output')
stderrfile = self.boss.formatStdOutErrPath(jobID, 'torque', '$PBS_JOBID', 'std_error')
_, tmpFile = tempfile.mkstemp(suffix='.sh', prefix='torque_wrapper')
fh = open(tmpFile , 'w')
fh.write("#!/bin/sh\n")
fh.write("#PBS -o {}\n".format(stdoutfile))
fh.write("#PBS -e {}\n".format(stderrfile))
fh.write("cd $PBS_O_WORKDIR\n\n")
fh.write(command + "\n")
fh.close
return tmpFile
```
The …
=> Fix broken stdout/stderr in  torque job (#3254)

src/toil/test/wdl/builtinTest.py, src/toil/test/wdl/standard_library/length.json, src/toil/test/wdl/standard_library/length_as_input.wdl, src/toil/test/wdl/standard_library/length_as_input_with_map.json, src/toil/test/wdl/standard_library/length_as_input_with_map.wdl, src/toil/test/wdl/standard_library/length_invalid.json, src/toil/wdl/wdl_analysis.py, src/toil/wdl/wdl_functions.py, src/toil/wdl/wdl_synthesis.py
Closes #3204. 
\- `length()` was supported but I'm making it part of `wdl_functions` for completeness, and to validate input.
=> Add length() WDL function

docs/running/cliOptions.rst, src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/lsf.py, src/toil/common.py, src/toil/job.py, src/toil/leader.py
Often in genomics pipelines, especially for post-processing, memory limits of programs are not well-defined and can be dependent on data. This PR will add a memory doubling functionality if the flag --doubleMem is included on the command line for the LSF scheduler which will double the memory of and resubmit jobs that die due to reaching the LSF imposed memory limit. This functionality is incredibly useful for on-prem clusters. This addresses the issue opened by me: #3269
=> added doubleMem functionality for LSF for lsf jobs that die due to reaching imposed memory limit

.gitlab-ci.yml, src/toil/test/cwl/cwlTest.py
Takes all of the extra minor refactors out of https://github.com/DataBiosphere/toil/pull/3323 to be added separately until the CWL conformance tests in kubernetes are running.
Changes:
- Refactored the 1/1.1/1.2 CWL conformance tests so that they share the same function.
- Corrected batch system names (i.e. `gridEngine` -> `grid_engine`) since https://github.com/DataBiosphere/toil/pull/3225 (and placed the `--batchSystem` arg at the correct position)
- Removed any remaining `@pytest.mark.xfail` decorators on CWL cache tests.
- CWL tests now only install the `[cwl,aws]` extras
- Other minor refactors/renames
=> CWL test script refactor.

src/toil/jobStores/aws/utils.py
=> Add 500 status to the list of retriable SDB BotoServerErrors.

.github/PULL_REQUEST_TEMPLATE.md, docs/contributing/contributing.rst
This adds a PR template that prompts you for a changelog entry, notes that the merger should add it to a wiki page, and has a step in the release process to pull the list of changes from the wiki page.
It also documents at least part of a release checklist, so that there's a place to put the note about pulling the changelog from the wiki. @DailyDreaming we probably will need the steps for doing the PyPI release on there too eventually.
This should fix #3315 .
=> Define a changelog process

Makefile, setup.cfg, setup.py, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
For `cwltool` `tmpdir_prefix` is not just a path to a directory, it can also include a suffix after the last path separator that become the prefix of the generated temporary directory.
=> CWL: Reformat w/ Black and better support for tmpdir_prefix with suffix.

.gitlab-ci.yml, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py, src/toil/test/lib/dockerTest.py
Tests seem to be failing on anything that pulls `docker.io`.  From `docker.io` itself:
```
The rate limits of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts are now in effect.
```
Will wait and rerun these later today, which should put us outside of the 6 hour window.  Running locally with caching, the CWL v1.2 conformance tests seem to pass (with the exception of 307 and 332 of course).
* Removed a cwltoil double import, which avoids missing secondaryFile imports defined by only a pattern before they've resolved.  Specifically, this now allows us to now support CWL v1.2 conformance tests: …
=> More CWL v1.2 conformance tests.

.gitlab-ci.yml, src/toil/test/__init__.py, src/toil/test/wdl/toilwdlTest.py, src/toil/wdl/wdl_functions.py
Making these non-manual now.  GATK has changed quite a bit and it looks like the WDL tutorials contain commands that don't exist in GATK anymore (they don't exist in version 4 and the version 3 in our bucket seems to have imports that break it): https://support.terra.bio/hc/en-us/sections/360007347652-WDL-Tutorials
The scripts and data have been updated and uploaded back into the s3 test data bucket and the tests have been re-enabled to help prevent future breakage.  Tutorials 1-3 seem to still work.  Tutorial 4 is breaking though and the test is skipped until the issue can be addressed: https://github.com/DataBiosphere/toil/issues/3339
Not sure how java is setup on gitlab currently, so the test environment may need further tweaking. …
=> Re-enable running WDL GATK Tutorial Tests.

src/toil/jobStores/aws/utils.py
Fixes #3263 
While ideally this should only be added to `_delete_bucket`, this exception is very specific and isn't expected to happen elsewhere, so didn't seem like it was worth the extra complexity, but lemme know if you feel strongly about only having it there!
=> Add a retry logic for BucketNotEmpty error.

src/toil/batchSystems/slurm.py
* getting job details from `scontrol show jobs` was non-functional. This PR enables this behavior in the case of sacct not being configured.
=> getting job details from scontrol is now functional.

src/toil/deferred.py
Many deferred jobs all seem to be attempting to delete the same state file at the end of the logs for: https://ucsc-ci.com/databiosphere/toil/-/jobs/67478/raw
The error seems to be ignored but it spams the screen until it finishes.  This should resolve the issue.
* Only rm a statefile that exists.
=> Only rm a statefile that exists.

src/toil/batchSystems/lsfHelper.py
Fixes #3353 
* LSF configuration files are now assumed to be unicode
=> LSF: handle unicode configuration files

src/toil/jobStores/fileJobStore.py, src/toil/lib/bioio.py, src/toil/test/jobStores/jobStoreTest.py
Attempting to reduce the amount of needless complexity.
* Replace abssympath w/ builtin.
=> Replace abssympath w/ builtin.

src/toil/__init__.py, src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/singleMachine.py, src/toil/test/batchSystems/batchSystemTest.py, src/toil/worker.py
Resolves #3359 .  Also refactored a little, somewhat due to making it easier to pass the `dir` name needed for the error message.
* Better error message for insufficient disk.
=> Add a better error message for insufficient disk.

src/toil/batchSystems/abstractBatchSystem.py, src/toil/batchSystems/lsf.py, src/toil/batchSystems/singleMachine.py, src/toil/batchSystems/slurm.py
Fixes #3368 
* Fixed LSF batch system `AttributeError: 'int' object has no attribute 'bytes'`
@caballero  can you test this?
=> fix maxMEM comparision

src/toil/jobStores/aws/jobStore.py
Just adds a generic retry.  I feel like it might be more robust to exclude specific retries we don't want in the future (like a `KeyError`), which should appear after the default of `[1, 1, 2, 4, 8, 16]` seconds, rather than implement something very specific now and then add as failures occur.
Resolves: https://github.com/DataBiosphere/toil/issues/3378
* Add a retry to AWS destroy.
=> Add a retry to AWS destroy.

src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
Looks like this was a simple fix.  Our `ToilPathMapper` is very nearly identical to the cwltool `PathMapper`, and so updates there should probably also be effected in Toil.  This could probably be refactored better on either side to reduce the amount of duplicated code (and increase the odds that cwltool side features/fixes will be automatically inherited by Toil).
* Support for CWL version 1.2: Passing CWL v1.2 Conformance Test #333.
=> CWL Test #333: Test input mount locations when container required.

docs/running/cliOptions.rst, src/toil/common.py
This option said it wasn't used on AWS (and the cgcloud provisioner which is long gone) and went I went to look at what it did, it seemed completely unused.
* Remove unused --nodeOptions arg.
=> Remove unused --nodeOptions arg.

src/toil/jobStores/aws/jobStore.py, src/toil/jobStores/aws/utils.py, src/toil/test/jobStores/jobStoreTest.py
* Move AWS job store uploads/downloads to boto3
=> Move AWS job store uploads/downloads to boto3 (reopened)

.gitlab-ci.yml
This should fix #3337 by pointing CI at the local Docker Hub mirror Lon set up.
* CI now uses a caching Docker mirror
=> Use a Docker Hub mirror when pulling Docker images

src/toil/batchSystems/gridengine.py
Using v5.1.0 with SGE kicked out an error about a missing byte subclass for the int object - so I've corrected this check to use the same MemoryString construct that maxMEM is initialised with.
* bugfix for gridengine maxMEM check
=> Corrected gridengine maxMEM check to use memorystring, not a plain int 0

src/toil/test/wdl/builtinTest.py, src/toil/test/wdl/toilwdlTest.py, src/toil/wdl/toilwdl.py, src/toil/wdl/utils.py, src/toil/wdl/versions/dev.py, src/toil/wdl/versions/draft2.py, src/toil/wdl/versions/v1.py, src/toil/wdl/wdl_analysis.py, src/toil/wdl/wdl_synthesis.py, src/toil/wdl/wdl_types.py
A few internal structural changes to `self.workflows_dictionary` in AnalyzeWDL to make integration with the other versions easier. In preparation for #3384.
Summary
* draft-2 implementation changes
- Use `parse_declaration()` and return a `tuple=(name, type, expr)` for both workflow and task declarations
- Use the same `parse_workflow_body()` function to parse all inner workflow elements (declarations, calls, scatters, and conditionals) 
* declarations are treated the same as calls, scatters, and conditionals instead of declaring them at the top, so the order will be preserved in cases like [this example workflow](https://github.com/openwdl/wdl/blob/main/versions/draft-2/SPEC.md#declarations):
```wdl
workflow wf {
call test as x {input: var="x"}
call test as y {input: var="y"} …
```
=> Update dictionary structure in AnalyzeWDL.

src/toil/common.py
Resolves #1632.
* Allow setOptions to accept argparse groups.
=> Allow setOptions to accept an argparse group.

src/toil/test/__init__.py
I'm not sure why we were checking boto for our tests.
* Better Google check when testing.
=> Check google storage import as evidence of google extras installed.

src/toil/wdl/versions/dev.py, src/toil/wdl/versions/v1.py
This can probably close #3384, but we still need to implement the following to fully support the development version of WDL: 
- [Import statements](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#import-statements)
- [Directory type](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#types)
- [Structs](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#struct-definition)
- [`after` keyword in call statements](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#call-statement)
* Add basic WDL development support.
=> Add basic WDL development support

src/toil/test/utils/toilDebugTest.py
* src/toil/test/utils/toilDebugTest.py no longer assumes that there is a executable named `python`; fixes tests for systems without Python2 (like the upcoming 'Bullseye' release of Debian, which does not install Python2 by default)
=> Ensure that python3 and not python (2) is used

src/toil/jobStores/abstractJobStore.py
Debian purposely sets an invalid HTTP_PROXY during some build situations
* Improve the tests ability to cope with an invalid HTTP_PROXY
=> cope with an invalid HTTP_PROXY

src/toil/common.py, src/toil/leader.py, src/toil/provisioners/__init__.py
This should fix #3414 for cactus.
There are two `--provisioner` args, unfortunately.  One is used with our utils like `launch-cluster` and `destroy-cluster` and should default to `aws`, whereas the the other is the main toil arg, and should default to `None` for single machine.  We should probably consolidate these to do the Right Thing when it detects `single_machine`, etc. but that might involve a larger refactor of how all of our options are set, so this is a lighter weight fix to restore old behavior.
* Restore `--provisioner` to not error when unset ("Error: None is not a valid choice").
* Stop printing that jobs have failed when they exit with a `0`.
```
contrib/admin/test-pr …
```
=> Quality of life improvements for cactus.

.gitlab-ci.yml
Closes #3431.
This PR adds a step in gitlab-ci.yml that runs make docs to ensure that the docs don't break.
=> Run make docs step in gitlab-ci.yml

common.mk, docs/running/cloud/amazon.rst, src/toil/provisioners/abstractProvisioner.py, src/toil/provisioners/aws/awsProvisioner.py
Closes #3435.
Removed mentions of CoreOS in the docs and in comments.
Migrated to Container Linux Config for provisioning since cloud-config is deprecated.
=> Replace mentions of CoreOS with flatcar

src/toil/provisioners/aws/__init__.py
If a proxy is configured, but the proxy can't connect to the
target host, the request times out with socket.timeout instead
of failing with URLError.
File "/usr/lib/python3/dist-packages/toil/test/batchSystems/batchSystemTest.py", line 360, in <module>
class KubernetesBatchSystemTest(hidden.AbstractBatchSystemTest):
File "/usr/lib/python3/dist-packages/toil/test/__init__.py", line 286, in needs_aws_s3
if not (boto_credentials or os.path.exists(os.path.expanduser('~/.aws/credentials')) or running_on_ec2()):
File "/usr/lib/python3/dist-packages/toil/provisioners/aws/__init__.py", line 39, in running_on_ec2
urlopen('http://169.254.169.254/latest/dynamic/instance-identity/document', timeout=1)
File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen …
=> AWS: Handle socket timeout during AWS discovery

src/toil/fileStores/cachingFileStore.py, src/toil/leader.py, src/toil/test/src/jobFileStoreTest.py
We were seeing some failures in our file job store tests because the caching file store was actually inconsistent: you wouldn't have read your own writes consistency when writing a file and then trying to stream it back, because the file would be uploaded asynchronously but the streaming read would always come from the backing job store.
This fixes the problem by making sure to do streaming reads from the cache when the file being read is there and in an uploading/uploadable state.
I ran the offending `src/toil/test/src/jobFileStoreTest.py::JobFileStoreTest::testJobFileStore` test in a loop, and this change stopped me being able to reproduce the error:
```
FAILED=0
for TRY_NUM in {1..5} ; do
for ITER in {1..32} ; do
make test_offline cov="" …
```
=> Handle streaming reads from the cache when the data isn't written back yet

src/toil/common.py
Fixes issue #3770
`Config.statePollingWait` should not be set by default, but only when the command-line option `--statePollingWait` is provided. Otherwise, when using `--batchSystem slurm`, the function `SlurmBatchSystem.Work.getWaitDuration()` will never be called in line 54 of `batchSystems/abstractGridEngineBatchSystem.py`. This will effectively set the state polling interval to 1 second, which could overload the Slurm Job accouting service.
* Don't set Config.statePollingWait to 1 by default. Fixing this allows the Slurm backend to query the SchedulerTimeSlice or AcctGatherNodeFreq for a sane default; the code to do so previously existed but was being bypassed.
``` …
```
=> Do not set default for statePollingWait

src/toil/bus.py, src/toil/fileStores/cachingFileStore.py, src/toil/leader.py, src/toil/serviceManager.py, src/toil/toilState.py
This implements a couple fixes to #3925. I'm now making sure that the job update messages are actually handled in chronological order, so the update that services are started, which was sent *before* the last service failed, doesn't get mistaken for the update that services are all stopped.
I'm also making sure that if checkpoint jobs get updates while they're running, they don't start running again.
And I'm insisting that we not issue jobs that are already running, and that we should crash if we try. Similarly, if a service job goes away without ever starting, we now crash instead of hanging around waiting forever for it to start.
So far, this has passed a couple iterations of this very vigorous test (which turned up an unrelated caching database bug which I also fix); hopefully the test …
=> Stop checkpoints from being reissued multiple times

src/toil/cwl/cwltoil.py, src/toil/test/cwl/colon_test_output.cwl, src/toil/test/cwl/colon_test_output_job.yaml, src/toil/test/cwl/cwlTest.py
Correcting logical checks inside upload_directory and
upload_file, to use schema_salad.ref_resolver.uri_file_path
for resolving file:/// paths. This ensures that encoded
special characters within the path are properly decoded again.
Will fix #3973 
* CWL input uploading to the file store: decode file paths that were previously URL encoded
```
```
=> Using uri_file_path to properly check for file existence

docs/appendices/environment_vars.rst, docs/developingWorkflows/toilAPIBatchsystem.rst, src/toil/batchSystems/slurm.py
Previously, setting `--partition=multicore` in TOIL_SLURM_ARGS
was trying to force serial tasks into the parallel partition,
which were failing to run due to requesting a single core.
I was running a CWL workflow with multiple steps, 
some of which were serial, and some parallel.
TOIL was not sending jobs to the appropriate queue -
if `--partition=serial` was set in `TOIL_SLURM_ARGS`,
or no partition was set, serial steps would run, but not
parallel.
If `--partition=multicore` was set in `TOIL_SLURM_ARGS`,
serial steps would not run, as this option applies to
all steps.
The proposed fix uses an environment variable to store 
the name of the parallel partition, and add this to the
sbatch command for tasks requiring more than 1 core. …
=> Use environment variable to set parallel partition name

contrib/assets/toil-slug-logo-wordmark-2022.svg
Here's the logo update we were kicking around in Slack.
I think the ends of the antennae might need to be hidden behind the main outline still, but we can run with this.
I am going to see if Gitlab is willing to skip CI-ing this.
=> Add new version of Toil logo from Slack [ci skip]

docs/running/cliOptions.rst, src/toil/common.py, src/toil/provisioners/clusterScaler.py, src/toil/test/provisioners/clusterScalerTest.py
This will fix #2103. This is also relevant to https://github.com/DataBiosphere/toil/issues/4147#issuecomment-1179587561 where a node with memory size very close to the job's requirements was provisioned but not able to be used.
This changes the cluster scaler so that it preprocesses its node sizes to remove some resources for overhead (i.e. the kernel, other processes on the system, and Mesos/Kubernetes). Currently we reserve memory and disk.
To guess at how much memory might be used, in the absence of much real data, we use [a formula from Google Kubernetes Engine](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#memory_cpu) which describes how much memory GKE clusters keep for themselves, as a function of node memory size. We assume that Toil-managed Mesos …
=> Account for overhead in Cluster Scaler

.gitlab-ci.yml, setup.cfg, src/toil/test/cwl/cwlTest.py
As running the tests post-installation can result in errors otherwise. We need this for the Debian package of `toil`
* Tests are now more runnable post-installation. Temporary paths are not selected based upon the location of the tests themselves.
```
```
=> Use pytest tmp_dir fixture for safe test paths

src/toil/cwl/cwltoil.py, src/toil/test/cwl/conditional_wf.cwl, src/toil/test/cwl/conditional_wf.yaml, src/toil/test/cwl/cwlTest.py, src/toil/test/cwl/echo.cwl
Fix #3991 by adding a condition to check if the input is `SkipNull` in `ResolveSource::pick_value()`.
```cwl
...
outputs:
out1:
type: File
outputSource:
- echo/echoOut
pickValue: first_non_null
...
```
When the `outputSource` only has one element, we internally store it as a tuple instead of a list of tuples. This source could evaluate to null but our [`pick_value()` function](https://github.com/DataBiosphere/toil/blob/releases/5.7.x/src/toil/cwl/cwltoil.py#L370) would return early and not filter out the SkipNull. 
- CWL: fix false warning when `outputSource` contains only one `None` value
```
```
=> CWL: fix false warning when `outputSource` contains only one `None` value

.gitlab-ci.yml, requirements-htcondor.txt, src/toil/cwl/__init__.py
This should fix #4315.
Is there a good way to tell Pip that we haven't *tested* with htcondor 11+, so we don't *know* that we'll work on those not-yet-released versions, but also we don't know that we *won't* work, and having released Toil X.X.X we won't be able to go back and *change it* to allow newer htcondor versions that *might* work, so do something sensible?
* Require htcondor 10 exaclty
```
```
=> Support (only) current htcondor

requirements-cwl.txt, src/toil/cwl/cwltoil.py
Reverts DataBiosphere/toil#4344
I'm going to immediately merge this, because force-merging a revert PR narrowly beats tampering with the branch protection and force pushing.
We will see if the new run of CI tests pass or not, which will help us work out if what I'm reverting here is in fact the source of the problem.
=> Revert "Bump cwltool from 3.1.20221201130942 to 3.1.20230127121939"

src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py, src/toil/test/cwl/test_filename_conflict_detection.cwl, src/toil/test/cwl/test_filename_conflict_detection_at_root.cwl, src/toil/test/cwl/test_filename_conflict_resolution.cwl
This will fix #3449 by failing the workflow if it asks for a `Directory` where two things are supposed to be at the same path. This includes the initial work directory from `InitialWorkDirRequirement`.
As far as I understand it, this is what the runner is always supposed to do. If `File` objects passed as inputs share a name we are supposed to rename them apart, but if the user is putting them together into a `Directory`, the user is supposed to guarantee that they have unique names. We are supposed to make sure that that is the case, not rename them apart, and not clobber one with another, because either of those would be too astonishing.
Previously we would sometimes catch this for non-workdir-root `Directory`s for uncontained jobs, but not for Docker-contained jobs because the …
=> Create necessary file staging conflicts

src/toil/batchSystems/slurm.py, src/toil/lib/misc.py
This will fix #4478 by making the Slurm batch system more quiet at debug level. We haven't had many problems with parsing Slurm's output; this should make the debug logs easier to scan for the sorts of problems we have actually been having.
* Slurm batch system no longer logs job listing/polling command output even with `--logDebug`, because there is a lot of it.
```
```
=> Suppress Slurm job listing and polling output from debug logs

setup.py, src/toil/lib/misc.py, src/toil/test/batchSystems/test_slurm.py
Fixes: https://github.com/DataBiosphere/toil/issues/3823
* Include tests in the source distribution that gets published to PyPI
```
```
=> include tests

requirements-cwl.txt, src/toil/cwl/__init__.py, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
Highlights:
- `--leave-tmpdir` includes the input staging directories by @mr-c in https://github.com/common-workflow-language/cwltool/pull/1674 https://github.com/common-workflow-language/cwltool/pull/1840
- use importlib instead of the deprecated pkg_resources by @mr-c in https://github.com/common-workflow-language/cwltool/pull/1844
* Upgrade cwltool to verstion 3.1.20230601100705
```
```
=> upgrade to cwltool 3.1.20230601100705

src/toil/batchSystems/singleMachine.py
We were using a magic `[3]` to get the accelerator set, and then I added a new resource pool in #4461 and didn't manually test GPU support.
This now uses a slightly less magic `[-1]` and should keep working as long as accelerators are the last resource type.
This will fix #4503.
* Single machine batch system now works with GPUs again
```
```
=> Grab accelerator set off the end of the list instead of by index

requirements-google.txt, setup.cfg, src/toil/common.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/googleJobStore.py, src/toil/test/__init__.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/provisioners/gceProvisionerTest.py, src/toil/test/sort/sortTest.py, src/toil/test/src/fileStoreTest.py, src/toil/test/wdl/md5sum/md5sum-gs.json, src/toil/test/wdl/wdltoil_test.py, src/toil/wdl/wdltoil.py
This fixes #4517.
* Toil can now read `gs://` URIs without a Google account and Google Cloud billing project
* WDL tests can now run with Singularity or Docker
* Stopped WDL input polling from failing before polling all the places by fixing import file existence sniffing
```
```
=> Anonymous access to Google Storage

.gitlab-ci.yml, requirements-wdl.txt, src/toil/test/wdl/wdltoil_test.py
This resolves #4508. I also updated MiniWDL from 1.9.1 to 1.10.0 as the latest version fixes an issue with expression placeholders that lets two more conformance tests to run. I also marked them as slow as on my machine, each took about 2 minutes to run.
* Added WDL conformance tests for toil-wdl-runner to CI
```
```
=> Add WDL conformance tests to CI

.gitlab-ci.yml, Makefile, src/toil/test/wdl/wdltoil_test.py
This fixes #4521. Only the `batch_systems`, `jobstore_and_provisioning`, and `wdl` tests are affected, as I think the integration tests and `py310_main` benefit from running all their current tests.
* Prevent certain tests from being run twice in CI
```
```
=> Prevent certain tests from being run twice in CI

src/toil/wdl/wdltoil.py
This should fix problems with WDL file manipulation functions not working right when called from command placeholder substitutions.
Now we have the "virtual" file name space be the inside of the container path space during WDL task commands, while the devirtualized path space is always the host side path space.
This should fix #4514 for files that aren't just converted from strings where that isn't really allowed, and should also fix #4515.
It doesn't really do anything for #4516, but is sort of relevant. With this, you *only* get the in-container path insode the command itself. If you go File to String elsewhere in the task, you get a URI.
* WDL commands now see in-container paths …
=> Virtualize filenames as in-container paths from point of view of WDL command

Makefile, src/toil/fileStores/abstractFileStore.py, src/toil/fileStores/cachingFileStore.py, src/toil/fileStores/nonCachingFileStore.py, src/toil/job.py, src/toil/jobStores/abstractJobStore.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/test/src/fileStoreTest.py, src/toil/test/src/resumabilityTest.py, src/toil/worker.py
This will fix #4504 by improving the semantics of `jobsToDelete` (which is now `merged_jobs`, to make it clear that it has very different semantics than `filesToDelete`, which journals file deletions).
Previously, when a job was chained to, we would put it in `jobsToDelete` on the chaining-from job, and then delete it when that job finished successfully.
But we also at some point started cutting the successor relationship to the chained-to job, which meant that if the chained-to job failed, when we went through the job tree during the restart, we would find the chained-to job's original job description under its original ID as an orphaned job and delete it.
This adds code to treat the original chained-to job as more properly merged into the chained-from job, and so still reachable from …
=> Stop deleting chained-to jobs which fail as orphaned jobs

.gitlab-ci.yml
This should fix #4607.
I'm trying to take some advice from https://softwareengineering.stackexchange.com/a/299262 and https://martinfowler.com/articles/nonDeterminism.html to get the integration tests and the tests that talk to things that can be down out of our main CI test set.
This doesn't actually sort/tag all the tests, but it does organize the Gitlab jobs a bit so that we have some jobs that run on a schedule, and others that run only for unit testing commits.
* Toil integration tests now happen periodically instead of on every commit
```
```
=> Separate out integration tests to run on a schedule

src/toil/wdl/wdltoil.py
This will resolve #4596 
* toil-wdl-runner will collect all task outputs when there is no output section in the workflow
```
```
=> Collect all task outputs when the workflow output section is undeclared

src/toil/wdl/wdltoil.py
This will resolve #4595
* Ensure that sibling files are preserved between node uploads in toil-wdl-runner
```
```
=> Ensure sibling files in toil-wdl-runner

src/toil/wdl/wdltoil.py
This improves WDL error reporting for #4608 by calling into MiniWDL to report errors.
Now if you run:
```
toil-wdl-runner https://raw.githubusercontent.com/human-pangenomics/hpp_production_workflows/655cbcdb659b38ab8c8472a14e97fea41dab0ca9/QC/wdl/workflows/comparison_qc.wdl
```
You will get a nice message calling out the chain of errors, formatted by MiniWDL:
```
[2023-10-19T09:38:37-0700] [MainThread] [C] [toil.wdl.wdltoil] Could not run workflow
(https://raw.githubusercontent.com/human-pangenomics/hpp_production_workflows/655cbcdb659b38ab8c8472a14e97fea41dab0ca9/QC/wdl/workflows/comparison_qc.wdl Ln 7 Col 1) Failed to import https://raw.githubusercontent.com/biomonika/HPP/main/assembly/wdl/workflows/findAssemblyBreakpoints.wdl
(https://raw.githubusercontent.com/biomonika/HPP/main/assembl …
```
=> Report errors in WDL using MiniWDL's error location printer

contrib/mypy-stubs/configargparse/configargparse.pyi, src/toil/common.py, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py, src/toil/wdl/wdltoil.py
This resolves #4615.
* Fix config file support for CWL
```
```
=> Fix configargparse in CWL

src/toil/lib/threading.py
This should fix #4654 by not aborting a job if, when it goes to unlock a filesystem-based mutex, the mutex lock has been tampered with. Instead, it will log an error message but continue.
This means that we aren't going to catch cases where really the mutexes aren't protecting the critical sections, for whatever reason, until some other problem results. But it might allow more workflows to finish on bad filesystems, or provide more insight into exactly what is weird about the offending filesystems.
This also fixes #3867 by handling stale file handle errors the same as `FileNotFound` errors.
* Toil mutex failure is no longer a good reason to fail a job
```
contrib/admin/test-pr …
```
=> Handle vanishing mutex files more gracefully

src/toil/cwl/cwltoil.py
This should fix #4691.
* Toil no longer refuses to run CWL tasks whose outputs are too big for temp storage, if the file store is bypassed
```
```
=> Only count output file usage when using the file store

src/toil/common.py, src/toil/job.py, src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/fileJobStore.py, src/toil/test/utils/toilDebugTest.py, src/toil/utils/toilClean.py, src/toil/utils/toilDebugFile.py, src/toil/utils/toilDebugJob.py, src/toil/utils/toilDestroyCluster.py, src/toil/utils/toilKill.py, src/toil/utils/toilLaunchCluster.py, src/toil/utils/toilRsyncCluster.py, src/toil/utils/toilSshCluster.py, src/toil/utils/toilStats.py, src/toil/utils/toilStatus.py
I think there is still stuff in `toil debug-file` that can't work since the file job store layout reorganization, but I don't want to chase too far from my original issue here.
* `toil debug-job --printJobInfo` now actually prints some job info instead of crashing.
* You can now use `toil debug-job --printJobInfo` without actually trying to execute a job.
* Toil subcommands now report their names in their usage documentation.
* Attempting to list or copy files out of job stores that don't yet support it with `toil debug-job` and `toil debug-file` will produce an informative error.
```
```
=> Fix --printJobInfo

src/toil/common.py
Fixes https://github.com/DataBiosphere/toil/issues/3955 
* add pure Python fallback for getDirSizeRecursively() for when the host environment has too many entries already.
```
```
=> add pure Python fallback for getDirSizeRecursively()

.gitlab-ci.yml, docs/appendices/architecture.rst, docs/cwl/running.rst, docs/wdl/running.rst, src/toil/cwl/cwltoil.py, src/toil/exceptions.py, src/toil/fileStores/abstractFileStore.py, src/toil/job.py, src/toil/leader.py, src/toil/statsAndLogging.py, src/toil/test/jobStores/jobStoreTest.py, src/toil/utils/toilStatus.py, src/toil/wdl/wdltoil.py, src/toil/worker.py
This changes CWL and WDL logging so that standard output and standard error from user commands, if they aren't captured, get thrown into the stats and logging system. Now you can see them without having to log at debug level and dig through Toil's logs.
This should fix #4657 (if you use `--writeLogs` and look in the directory, or if you don't mind *some* Toil log messages about jobs being run), and should also fix #2406 by letting you see command outputs/error logs there as well.
```
$ toil-wdl-runner --writeLogs logs https://raw.githubusercontent.com/DataBiosphere/toil/36b54c45e8554ded5093bcdd03edb2f6b0d93887/src/toil/test/wdl/miniwdl_self_test/self_test.wdl https://raw.githubusercontent.com/DataBiosphere/toil/36b54c45e8554ded5093bcdd03edb2f6b0d93887/src/toil/test/wdl/miniwdl_self_test/in …
```
=> Ship User Logs to Leader

src/toil/common.py
Yelling at everyone didn't make our Slurm cluster stop vanishing `XDG_RUNTIME_DIR` out from under jobs, and we already compensate for it on Slurm, so stop warning.
This fixes #4696.
* Toil will no longer warn about a missing `XDG_RUNTIME_DIR`
```
```
=> Stop complaining about XDG_RUNTIME_DIR

src/toil/options/common.py, src/toil/test/options/__init__.py, src/toil/test/options/options.py
This will resolve #4776.
I think previously, caching was set to `True` by default. This change will set the argparse default back to `None`, and the `default_caching()` function should return `False` for all cases, effectively setting `caching` to False by default.
This will however technically mean that the default `caching` value is now changed from `True` to `False.`
This also adds a test to ensure that when running on SLURM, `caching` will automatically be set to `False`. There's also another test that ensures command line arguments take priority over the internal default.
* Fix issue of default caching value not being respected
* `caching` will now be `False` by default
``` …
```
=> Fix default caching value not being respected

src/toil/test/wdl/wdltoil_test.py, src/toil/wdl/wdltoil.py
This fixes #4831 by making sure to make the output directory, and improves error reporting by checking that the directory we want to devirtualize into actually exists.
* `toil-wdl-runner` no longer fails cryptically when the output directory doesn't already exist.
```
```
=> Make sure output directory exists before using it

docs/running/debugging.rst, docs/running/utils.rst, src/toil/test/docs/scripts/example_alwaysfail.py, src/toil/utils/toilDebugJob.py, src/toil/utils/toilLaunchCluster.py, src/toil/utils/toilStatus.py
This will fix #4814 by pulling in some job store scanning logic from `toil status`. It also includes some fixes to `toil status`, which kind of didn't work.
* `toil status --printPerJobStats` actually reports per-job stats and not merged mega-stats.
*  `toil status --printPerJobStats` uses a new more-readable format and notes completely failed jobs (those with 0 tries left)
* `toil status` now has shorter flag names you can use
* `toil status --failed` now exists and can print all the completely failed jobs (those with 0 tries left)
* `toil debug-job` can now look up jobs by name and run them
* Documentation now exists showing how to use `toil status` and `toil debug-job` to …
=> Allow debugging jobs by name (and status improvements)

docs/running/cliOptions.rst, src/toil/batchSystems/abstractGridEngineBatchSystem.py, src/toil/batchSystems/options.py, src/toil/batchSystems/slurm.py, src/toil/common.py
This should fix #4853 by using the exponential backoff logic from `retry.py`.
It also has some miscellaneous fixes so that `make test_debug tests='src/toil/test/batchSystems/batchSystemTest.py::SlurmBatchSystemTest'` passes on the Phoenix cluster.
* Toil now has a `--statePollingTimeout` and will retry talking to Slurm or other HPC schedulers for that amount of time.
* Toil can now tolerate extra information in the Slurm state (e.g. `CANCELLED by 30065`).
* Toil will now stop and complain if Slurm shows a job in a state that Toil doesn't understand.
* Trying to run a job that asks for more than the configured maximum resource limits will no longer crash the Slurm batch system the …
=> Retry Slurm interactions more

docker/Dockerfile.py
Related to Dockerfile changes I made in #4824
For some reason, when I replaced the `get-pip` script with `ensurepip`, which should have been [included in the default python installation](https://docs.python.org/3/library/ensurepip.html), CI breaks on Python 3.10 on ARM:
```
> [linux/amd64 15/26] RUN python3.10 -m ensurepip --upgrade:
#28 0.622 
#28 0.622 Python modules for the system python are usually handled by dpkg and apt-get.
#28 0.622 
#28 0.622     apt install python3-<module name>
#28 0.622 
#28 0.622 Install the python3-pip package to use pip itself.  Using pip together
#28 0.622 with the system python might have unexpected results for any system installed
#28 0.622 module, so use it on your own risk, or make sure to only use it in virtual
#28 0.622 environments.
#28 0.622 
``` …
=> Revert ensurepip to get-pip to fix Python 3.10 ARM CI appliance builds

README.rst
This will fix #4896.
* Toil README now advertises supported workflow language versions
```
```
=> Add supported workflow language versions to README

src/toil/jobStores/abstractJobStore.py, src/toil/jobStores/aws/jobStore.py, src/toil/lib/aws/utils.py
This should fix #4867 by changing the logging and exception handling around bucket location finding.
We now announce finding the location at the same log level as failing to find it (DEBUG), and leave reporting at higher levels up to the caller. Most of the callers seem to have fallback approaches to use when a bucket location isn't available, and so don't have to log anything at a higher level.
Also, to keep the user from getting bored during file imports, I am logging them at INFO:
```
[2024-05-23T16:30:15-0400] [MainThread] [I] [toil.jobStores.abstractJobStore] Importing input s3://human-pangenomics/NHGRI_UCSC_panel/HG002/hpp_HG002_NA24385_son_v1/PacBio_HiFi/20kb/m64011_190901_095311.Q20.fastq...
``` …
=> Better logs when accessing large files from S3

src/toil/wdl/wdltoil.py
Closes #4959
We were caching already devirtualized files in the virtualized-to-devirtualized cache, which caused conflicts when the task/job cleaned up its files but the workflow attempts to access it again from the "virtualized" url.
This separates the caching a bit so it only adds it to the cache when we actually have a virtualized file to devirtualize.
This also lets the devirtualization step start using the cache, which it wasn't doing before.
* Fixed a bug where already devirtualized files get lost
```
```
=> Fix bad caching to prevent already devirtualized files getting lost

src/toil/batchSystems/slurm.py
This will fix #5010 by allowing Toil to select non-GPU job partitions on Slurm, in addition to allowing it to select a GPU job partition.
There's just one flat job runtime that is always used, pending a wall-clock resource system for jobs.
Runtime is also still ignored when selecting a partition for GPU jobs; the two selection methods eventually need to be unified so we can pick a partition that is a good match for the runtime *and* has/doesn't have GPUs *and* isn't unnecessarily high priority.
* New `--slurmTime`/`TOIL_SLURM_TIME` setting to set the time limit on Slurm jobs in a way TOil itself understands.
* New `--slurmPE` argument to allow setting a parallel-job Slurm partition …
=> Select Slurm partition for non-GPU jobs using runtime limit

docs/running/cliOptions.rst, src/toil/common.py, src/toil/jobStores/fileJobStore.py, src/toil/options/common.py, src/toil/test/jobStores/jobStoreTest.py
This fixes #4673 by adding a `--symlinkJobStoreReads` option.
If you set `--symlinkJobStoreReads=False`, we won't create symlinks pointing into a FileJobStore when jobs go to read from it. We will instead make copies or hardlinks (within a filesystem). So if you have a workload that does more I/O on a file mounted into a container than a single full copy would do, you can use this to make a copy happen instead of having everyone mount straight from the shared filesystem.
If you have caching enabled, you can make the cache actually cache a copy per node instead of symlinking all the way through just because it can.
* New `--symlinkJobStoreReads=False` option lets you force …
=> Limit reading/mounting from shared filesystem JobStore

src/toil/batchSystems/abstractGridEngineBatchSystem.py
I think all batch systems are meant to kill outstanding jobs at `shutdown()` like the Kuberentes one does, but the Grid Engine batch systems didn't seem to implement it.
This should fix that.
It would be nice to test this requirement across all batch systems somehow, but that's not in this.
This should fix #5082 but I think still needs some manual testing.
* Grid Engine batch systems now send the required job kills when shut down
```
```
=> Kill all grid engine jobs on shutdown

src/toil/wdl/wdltoil.py
#5055 
* Fixed a bug with conditional statements inside a WDL scatter
```
```
=> Change supertype calculation when combining scatters

src/toil/test/wdl/wdltoil_test.py, src/toil/wdl/wdltoil.py
This fixes #5094 by finding outputs for tasks inside control flow constructs. It should help with working around not having the workaround #5093 asks for.
This includes bumping the conformance tests with a test for this, which MiniWDL and Cromwell pass.
* `toil-wdl-runner` now correctly finds and returns outputs from tasks in scatters and conditionals when a WDL workflow lacks an `output` section.
```
```
=> Include outputs from tasks in scatters and conditionals when a workflow has no output section

docs/wdl/running.rst, src/toil/options/wdl.py, src/toil/test/wdl/testfiles/croo.wdl, src/toil/test/wdl/testfiles/not_enough_outputs.wdl, src/toil/test/wdl/wdltoil_test.py, src/toil/wdl/wdltoil.py
This is on top of #5095 and additionally fixes #5093.
* `toil-wdl-runner` now correctly finds and returns outputs from tasks in scatters and conditionals when a WDL workflow lacks an `output` section.
* `toil-wdl-runner` has a new `--allCallOutputs` option to allow including all calls' outputs in a workflow's output.
* `toil-wdl-runner` can now detect and try not to delete the outputs of a workflow that is meant to use the [Cromwell Output Organizer (`croo`)](https://github.com/ENCODE-DCC/croo). Note that `croo` still can't actually work on the output of `toil-wdl-runner`.
```
```
=> Sniffing for and workaround for keeping output of croo workflows

src/toil/cwl/cwltoil.py
Resolves #5137 
* Don't error when passing through input as the output
```
```
=> Don't error on collision

src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py, src/toil/test/cwl/not_run_required_input.cwl, src/toil/wdl/wdltoil.py
This will fix #4930 by patching a hole where we could run `fill_in_defaults()` for a CWL job's inputs before checking that its conditional was true.
* CWL jobs with dynamic requirements now have input type checking properly protected by their conditionals.
```
```
=> Fix unexecuted CWL jobs with dynamic requirements failing on missing inputs

src/toil/jobStores/fileJobStore.py
This might fix #1727 by definitively moving stats and logging files from a `stats/inbox` directory to a `stats/archive` directory when the leader processes them. It no longer renames them back to the `.new` suffix they had when they were being written, which avoids trying to directly undo a rename that just happened from another node, which is a thing that a very broken filesystem might find confusing.
This also means we don't need to scan through all previously-processed stats and logging files to find new ones; we only have to scan `stats/inbox`.
* Organize stats and logging files into `stats/inbox` and `stats/archive` and avoid a circular rename.
```
contrib/admin/test-pr …
```
=> Separate unread and read stats and logging files and avoid a circular rename

src/toil/common.py
The override of the coordination directory that a user could make was not applied correctly. Instead of setting `self.coordination_dir` the variable `self.workDir` would be modified. This has been fixed.
```
```
=> Fix bug in override of coordination directory

src/toil/cwl/cwltoil.py, src/toil/job.py
Resolves #5135 
* When importing on workers, fallback to import files on the leader when file sizes are not obtainable. Related to (#5133).
```
```
=> Add leader fallback for worker file imports

requirements-cwl.txt, src/toil/cwl/cwltoil.py, src/toil/test/cwl/cwlTest.py
I hit this bug while testing #5187 on a system that had podman but not docker.
* - CWL container prepull: no reason to if extensions are enabled, they are now supported by cwl-utils 0.36+
* - CWL container prepull: skip if --no-containers is specified
```
```
=> CWL: Fix --no-container & prepull

.gitlab-ci.yml, requirements-htcondor.txt
* Toil now uses htcondor 23.6 or 24, which are still on PyPI
```
```
=> Bump htcondor version everywhere to avoid vanished 10.x releases

.gitlab-ci.yml, MANIFEST.in, Makefile, pyproject.toml, setup.py, src/toil/cwl/cwltoil.py, src/toil/test/__init__.py, src/toil/test/cwl/cwlTest.py, src/toil/test/provisioners/aws/awsProvisionerTest.py, src/toil/test/provisioners/clusterTest.py, src/toil/test/provisioners/gceProvisionerTest.py, src/toil/test/utils/ABCWorkflowDebug/debugWorkflow.py, src/toil/test/utils/toilDebugTest.py, src/toil/test/utils/toilKillTest.py, src/toil/test/utils/utilsTest.py, src/toil/test/wdl/wdltoil_test.py
Also fixes https://github.com/DataBiosphere/toil/issues/3996 
* tests now load their data more flexibly
```
```
=> Make tests more independent

setup.py, src/toil/common.py, src/toil/jobStores/fileJobStore.py, src/toil/lib/accelerators.py, src/toil/lib/io.py, src/toil/test/__init__.py, src/toil/test/wdl/testfiles/string_file_coercion.json, src/toil/test/wdl/testfiles/string_file_coercion.wdl, src/toil/test/wdl/wdltoil_test.py, src/toil/wdl/wdltoil.py
This should fix #5265.
Broad likes to write workflows that coerce Files to Strings and back again. Apparently when we go File to String we always include a file: URI prefix, and the String-to-FIle coercion was thinking that was a nonexistent bare path, and also the caching code was not dealing with a file: URI that didn't have a known cache path.
This fixes both of these issues at workflow scope, by revising the file URI normalization and abs-pathing code to go through one true implementation, and by making sure to find files we're making from strings at workflow scope and hook up their shared-filesystem paths.
At task scope we really shouldn't be going from String to File for anything except what's on the task's filesystem; there might still be dragons there because I'm not sure this is …
=> Handle coercing file: URIs to files

src/toil/options/wdl.py, src/toil/test/wdl/md5sum/md5sum-gs.json, src/toil/wdl/wdltoil.py
This will give us MiniWDL relaxed quant check parity.
The only place we use MiniWDL's type checking seems to be in the initial document load, which is where any type errors will result in the workflow crashing. We don't actually use MiniWDL's type checking for evaluation since we have our own evaluation logic, so our existing code seems to be fairly robust to coercing from optional types, ex:
```wdl
workflow testWorkflow {
input {
String? in
}
call testTask {input: test=in}
output {
String out = testTask.out
}
}
task testTask {
input {
String test
}
command <<<
>>>
output {
String out = test
}
}
```
A downside to this seems to be that even with relaxed type checking, we don't have full behavioral parity with MiniWDL as MiniWDL seems to coerce any nonexistent optional type (at least …
=> Support relaxing quant checks in WDL
